### ISSUE TITLE
Add semantic versioning

### ISSUE THREAD

**Issue by mehalter** [williamboman/mason.nvim#1000]
### I've searched open issues for similar requests

Yes

### Is your feature request related to a problem? Please describe.

This isn't really related to a problem, but just improves the design a little bit. With the rise of package managers like [lazy.nvim](https://github.com/folke/lazy.nvim) which support semantic versioning based updating, it would be great to have Mason tag versions that follow this. This would allow users to update mason safely to get newly added packages without the worry of breaking changes to the underlying API.

### Describe the solution you'd like

Tag versions following semantic versioning. Use major versions when changing the Mason user facing API or removing packages, use minor versions when adding new features such as adding a new packages, and use patch versions when revising bugs either within Mason or when refactoring/updating existing packages installation. Then in our package managers I can tag my Mason install to the major version and guarantee that I will not receive any breaking changes to the API but can make sure I have the most up to date list of packages.

**Comment by jay-babu** [comment]
@williamboman, I can do the work for this if you agree with it. recently did it for my mason plugins

example: 
https://github.com/jay-babu/mason-nvim-dap.nvim/blob/main/.github/workflows/ci.yml#L29-L45

**Comment by jay-babu** [comment]
https://github.com/williamboman/mason.nvim/pull/1213

**Comment by williamboman** [comment]
v1.0.0 released now https://github.com/williamboman/mason.nvim/releases
