### ISSUE TITLE
bash-debug-adapter failed installation

### ISSUE THREAD

**Issue by GreatNewHope** [williamboman/mason.nvim#1008]
### I've searched open issues for similar requests

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

  Failed
    ◍ bash-debug-adapter
      ▼ Displaying full log
        Downloading file "https://github.com/rogalmic/vscode-bash-debug/releases/download/untagged-438733f35feb8659d939/bash-debug-0.3.9.vsix"...
        spawn: unzip failed with exit code - and signal -. unzip is not executable

### Expected behavior

Installed bash debug adapter

### Affected packages

bash-debug-adapter

### Mason output

```Text
Failed
    ◍ bash-debug-adapter
      ▼ Displaying full log
        Downloading file "https://github.com/rogalmic/vscode-bash-debug/releases/download/untagged-438733f35feb8659d939/bash-debug-0.3.9.vsix"...
        spawn: unzip failed with exit code - and signal -. unzip is not executable
```

### Installation log

```Text
[ERROR vie 10 feb 2023 00:38:22] ...acker/start/mason.nvim/lua/mason-core/installer/init.lua:159: Installation failed for Package(name=bash-language-server) error=spawn: npm failed with exit code - and signal -. npm is not executable
```

### Neovim version (>= 0.7)

NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

### Operating system/version

Linux shinu 5.15.91-1-MANJARO #1 SMP PREEMPT Wed Feb 1 12:03:19 UTC 2023 x86_64 GNU/Linux

### Healthcheck

```Text
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - WARNING: **Go**: not available
  - WARNING: **cargo**: not available
  - WARNING: **luarocks**: not available
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - OK: **PHP**: `PHP 8.2.2 (cli) (built: Feb  1 2023 08:33:04) (NTS)`
  - OK: **npm**: `9.3.1`
  - OK: **node**: `v18.14.0`
  - OK: **python3**: `Python 3.10.9`
  - OK: **pip3**: `pip 22.3.1 from /usr/lib/python3.10/site-packages/pip (python 3.10)`
  - WARNING: **javac**: not available
  - OK: **java**: `openjdk version "19.0.2" 2023-01-17`
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: **curl**: `curl 7.87.0 (x86_64-pc-linux-gnu) libcurl/7.87.0 OpenSSL/3.0.7 zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.10.0 nghttp2/1.51.0`
  - OK: **gzip**: `gzip 1.12`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - WARNING: **pwsh**: not available
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 0. Remaining: 5000. Limit: 5000. Reset: sáb 18 feb 2023 17:17:05.
```

**Comment by Qpernicus** [comment]
I have the same error " all of a sudden "  (probably after a mason update?)

If i can test anything? (quite a noob, but willing)

**Comment by Mikkolehtimaki** [comment]
Running into the same, as well as "Cannot find package" error everytime I start nvim. Haven't even loaded this debugger.

**Comment by williamboman** [comment]
As for OPs issue, you need `unzip` to be installed in order to install `bash-debug-adapter` (it needs to unpack a `.vsix` archive). As for the other commenters, your issue is/was probably that the registry was not successfully downloaded. You should be see an error message in the `:Mason` window if this is the case.
