### ISSUE TITLE
Config item toggle_package_expand is not respected on failed installations

### ISSUE THREAD

**Issue by rrunner** [williamboman/mason.nvim#1030]
### I've searched open issues for similar requests

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

When a package installations fails, this is visualized in the Mason UI. To toggle the item to get more information about the failure, you currently must press the enter key despite you have remapped toggle_package_expand to a different key.

I would expect that you could use the remapped key (in my case "o").

My config looks like:

ui = {
    keymaps = {
      toggle_package_expand = "o",
    },
}

### Expected behavior

In my case, use "o" to also toggle failed items in the UI.

### Steps to reproduce

1. Failed installation
2. Toggle menu item (you must use enter)

### Neovim version (>= 0.7)

NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

### Operating system/version

Linux arch 6.1.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 14 Feb 2023 22:08:08 +0000 x86_64 GNU/Linux

### Healthcheck output

```shell
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - OK: **Go**: `go version go1.20.1 linux/amd64`
  - OK: **cargo**: `cargo 1.67.1`
  - WARNING: **luarocks**: not available
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.19.2`
  - OK: **node**: `v19.7.0`
  - OK: **python3**: `Python 3.10.9`
  - OK: **pip3**: `pip 23.0.1 from /usr/lib/python3.10/site-packages/pip (python 3.10)`
  - OK: **javac**: `javac 11.0.18`
  - OK: **java**: `openjdk version "11.0.18" 2023-01-17`
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: **curl**: `curl 7.88.1 (x86_64-pc-linux-gnu) libcurl/7.88.1 OpenSSL/3.0.8 zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.10.0 nghttp2/1.52.0`
  - OK: **gzip**: `gzip 1.12`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - WARNING: **pwsh**: not available
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: 2023-02-25T18:04:40
```

**Comment by williamboman** [comment]
New setting added in #1268.
