### ISSUE TITLE
Installing zls, unrecognized archive format tar failed  with exit code 1 and signal 0 

### ISSUE THREAD

**Issue by PorcoRosso85** [williamboman/mason.nvim#1032]
### I've searched open issues for similar requests

Yes

### I've manually reviewed logs to find potential errors

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

macos
unrecognized archive format tar failed  with exit code 1 and signal 0 
when installing zls for zig

![image](https://user-images.githubusercontent.com/40359643/221389081-a21adea5-e24d-4ffd-8743-a93588d8a068.png)
<img width="1089" alt="スクリーンショット 2023-02-26 11 30 19" src="https://user-images.githubusercontent.com/40359643/221389101-98c8829c-ac69-4c19-9789-18300ecb1964.png">

### Expected behavior

done installing

### Steps to reproduce

1. on macos 10.15.7

### Affected packages

zls

### Neovim version (>= 0.7)

neovim 0.8.3

### Operating system/version

10.15.7

### Healthcheck

```Text
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - WARNING: **Go**: not available
  - WARNING: **cargo**: not available
  - WARNING: **luarocks**: not available
  - OK: **Ruby**: `ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]`
  - OK: **RubyGem**: `3.0.3`
  - WARNING: **Composer**: not available
  - OK: **PHP**: `PHP 7.3.29 (cli) (built: Aug 15 2021 23:10:16) ( NTS )`
  - OK: **npm**: `9.5.0`
  - OK: **node**: `v18.14.2`
  - OK: **python3**: `Python 3.8.2`
  - OK: **pip3**: `pip 19.2.3 from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip (python 3.8)`
  - WARNING: **javac**: not available
  - WARNING: **java**: not available
  - WARNING: **julia**: not available
  - ERROR: **wget**: not available
  - OK: **curl**: `curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2`
  - OK: **gzip**: `Apple gzip 287.100.2`
  - OK: **tar**: `bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.6`
  - WARNING: **pwsh**: not available
  - OK: **bash**: `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)`
  - OK: **sh**: `Ok`
  - OK: **python3_host_prog**: `Python 3.10.9`
  - WARNING: **python3_host_prog pip**: not available
```

### Screenshots or recordings

![image](https://user-images.githubusercontent.com/40359643/221389224-45ee7128-81ea-4cbc-9ab1-6a7cf8190600.png)

**Comment by PorcoRosso85** [comment]
add info:

`❯ tar --version
bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.6`

**Comment by williamboman** [comment]
Hey! `zls` is the only package that uses `zstd` as their compression algo for release files. To decompress it I believe it should be enough to simply have [`zstd`](https://github.com/facebook/zstd) installed on your system

**Comment by PorcoRosso85** [comment]
Done.

Thanks so much.
We of course need to check each lsp requirements to install.

**Comment by williamboman** [comment]
@rwboyer What version of BSD tar do you have installed? My understanding is that it should recognize zstd compression automatically
