### ISSUE TITLE
`Cannot find package "bash-debug-adapter"` error on startup

### ISSUE THREAD

**Issue by kofteistkofte** [williamboman/mason.nvim#1045]
### I've searched open issues for similar requests

Yes

### I've manually reviewed logs to find potential errors

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

In my setup, I configured dap with mason-nvim-dap with automatic_setup. After updating every package, I started to get error `...pack/packer/start/mason.nvim/lua/mason-registry/init.lua:76: Cannot find package "\"bash-debug-adapter\"".`.
Tried to understand why this message triggers but couldn't find any reason for it. And also `bash-debug-adapter` shows up in the `:Mason` and I can install it. This error only shows at startup.
I'm not sure if this problem caused by Mason or mason-nvim-dap.

### Expected behavior

Not getting this error

### Steps to reproduce

- configure mason-nvim-dap with automatic_setup
- open neovim

### Affected packages

Mason, mason-nvim-dap

### Neovim version (>= 0.7)

NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Operating system/version

Linux Dumah 6.2.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 26 Feb 2023 03:39:23 +0000 x86_64 GNU/Linux

### Healthcheck

```Text
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - OK: **Go**: `go version go1.20.1 linux/amd64`
  - OK: **cargo**: `cargo 1.65.0 (4bc8f24d3 2022-10-20)`
  - OK: **luarocks**: `/usr/bin/luarocks 3.9.2`
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.19.2`
  - OK: **node**: `v19.7.0`
  - OK: **python3**: `Python 3.10.9`
  - OK: **pip3**: `pip 23.0.1 from /usr/lib/python3.10/site-packages/pip (python 3.10)`
  - WARNING: **javac**: not available
  - WARNING: **java**: not available
  - OK: **julia**: `julia version 1.8.5`
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: **curl**: `curl 7.88.1 (x86_64-pc-linux-gnu) libcurl/7.88.1 OpenSSL/3.0.8 zlib/1.2.13 brotli/1.0.9 zstd/1.5.4 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.10.0 nghttp2/1.52.0`
  - OK: **gzip**: `gzip 1.12`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - WARNING: **pwsh**: not available
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - WARNING: **JAVA_HOME**: not available
  - OK: GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: Thu 02 Mar 2023 14:57:56 +03.
```

**Comment by williamboman** [comment]
You're probably setting up Mason too late. If you're using a plugin manager to set up your plugins you need to tell it in which order to load the plugins (Mason needs to be set up before any other dependents).

**Comment by kofteistkofte** [comment]
Yes it seems to be the issue.
