### ISSUE TITLE
Cmakelint filetype

### ISSUE THREAD

**Issue by TroySigX** [williamboman/mason.nvim#1068]
### I've searched open issues for similar requests

Yes

### I've manually reviewed logs to find potential errors

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

In #1050, I notice that cmakelint is associated with python filetype (in file [lua/mason/mappings/language.lua](https://github.com/williamboman/mason.nvim/blob/main/lua/mason/mappings/language.lua)). I think that cmakelint should be associated with cmake filetype instead?

### Expected behavior

Cmakelint package should be associated with cmake filetype.

### Steps to reproduce

Read this [file](https://github.com/williamboman/mason.nvim/blob/main/lua/mason/mappings/language.lua).

### Affected packages

cmakelint

### Neovim version (>= 0.7)

0.8.3

### Operating system/version

6.2.2-arch1-1

### Healthcheck

```Text
Everything is ok
```

**Comment by williamboman** [comment]
That's correct, thanks!
