### ISSUE TITLE
not spawning ruff-lsp on windows

### ISSUE THREAD

**Issue by russarr** [williamboman/mason.nvim#1105]
### I've searched open issues for similar requests

Yes

### I've manually reviewed logs to find potential errors

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

I'm getting error "spawning server ruff-lsp failed, missed from path..."
Other servers(lua_ls, pyright) work correctly.
I tried :!ruff-lsp and it does not cause errors(so ruff-lsp in the Path).
This config work correctly:
`require('lspconfig').ruff_lsp.setup {
      on_attach = on_attach,
      cmd = { [[C:\Users\Necros\AppData\Local\nvim-data\mason\packages\ruff-lsp\venv\Scripts\ruff-lsp.exe]]},}`
So i think the problem with `nvim-data\mason\bin\ruff-lsp.cmd'

### Expected behavior

Spawning ruff-lsp server

### Steps to reproduce

Install ruff-lsp from Mason
use standart config 
`require('lspconfig').ruff_lsp.setup { on_attach = on_attach,}`
open .py file in nvim

### Affected packages

ruff-lsp

### Neovim version (>= 0.7)

NVIM v0.9.0-dev-1234+g5a38e951e
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system/version

Windows 10 Pro 22H2

### Healthcheck

```Text
mason.nvim report ~
- OK neovim version >= 0.7.0
- WARNING **Go**: not available
- WARNING **cargo**: not available
- WARNING **luarocks**: not available
- WARNING **Ruby**: not available
- WARNING **RubyGem**: not available
- WARNING **Composer**: not available
- WARNING **PHP**: not available
- OK **npm**: `9.5.0`
- OK **node**: `v18.15.0
`
- WARNING **python3**: not available
- WARNING **pip3**: not available
- WARNING **javac**: not available
- WARNING **java**: not available
- WARNING **julia**: not available
- ERROR **wget**: not available
- OK **curl**: `curl 7.83.1 (Windows) libcurl/7.83.1 Schannel
`
- WARNING **gzip**: not available
- OK **tar**: `bsdtar 3.5.2 - libarchive 3.5.2 zlib/1.2.5.f-ipp 
`
- ERROR **pwsh**: not available
- OK **python**: `Python 3.11.2
`
- OK **pip**: `pip 22.3.1 from C:\Python\Python311\Lib\site-packages\pip (python 3.11)

`
- WARNING **7z**: not available
- OK GitHub API rate limit. Used: 3. Remaining: 57. Limit: 60. Reset: 17.03.2023 12:30:37.
```

**Comment by russarr** [comment]
But i don't have problems with pyright and lua_ls, and they are installed the same way using Mason. And perfectly works with default setup `require('lspconfig')['pyright'].setup {    on_attach = on_attach,}`
Because of this, I think there may be a problem with the ruff-lsp.
Thanks for your anwer `cmd = { vim.fn.exepath("ruff-lsp") }` works for me.

**Comment by williamboman** [comment]
Do you have these LSPs installed elsewhere perhaps? Anyways, this applies to all language servers. If you use `vim.lsp.start()` you will have to `vim.fn.expand()` (or some equivalent) _all_ executables provided by Mason. If you use `nvim-lspconfig` you'll have to expand _most_ cmds (mason-lspconfig.nvim does this for you).

**Comment by russarr** [comment]
There are no other installations except through Mason.
I tried to use new clean nvim config(to exclude the influence of others plugins) only with `Mason` and `nvim-lspconfig'. The situation is the same: pyright and lua works, ruff-lsp not.
I checked `:lua print(vim.env.PATH)` - "C:\Users\Necros\AppData\Local\nvim-data\mason\bin" is in the PATH.
Config text:
```
require('lspconfig')['pyright'].setup {
    on_attach = on_attach}
require("lspconfig").ruff_lsp.setup({
    on_attach = on_attach,
    init_options = {
          settings = { ... }
     }
}
```
The full text of notification: "Spawning language server with cmd: `ruff-lsp` failed. The language server is either not installed, missing from PATH, or not executable."
LspInfo: 
```
 Client: pyright (id: 1, bufnr: [1])
 	filetypes:       python
 	autostart:       true
 	root directory:  C:/coding/projects/parsing
 	cmd:             cmd.exe /C pyright-langserver --stdio
 Other clients that match the filetype: python
 Config: ruff_lsp
 	Refer to :h lspconfig-root-detection for help.
 	filetypes:         python
 	root directory:    Not found.
 	cmd:               ruff-lsp
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
```
For some reason ruff-lsp doesn't see `root_dir`, but pyright with default settings detect it as pwd normally.
setting `require("lspconfig").ruff_lsp.setup({root_dir=...}`
to [[C:\Users\Necros\AppData\Local\nvim-data\mason\packages\ruff-lsp\venv\Scripts\]] works,
but to [[C:\Users\Necros\AppData\Local\nvim-data\mason\bin]] not working.
Perhaps the problem is in the `nvim-lspconfig' plugin.
That's all information what I have.
As I wrote in the previous post `cmd = { vim.fn.exepath("ruff-lsp") }` works for me, so you don't have to waste time on this issue.

**Comment by williamboman** [comment]
It seems like they spawn those servers through a shell, instead of directly via libuv, so that explains why they work.

- https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/pyright.lua#L7
- https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/lua_ls.lua#L17

But yeah as a Windows user you need to make sure to expand `.cmd` executables (which all executables installed by Mason are) when launching LSP servers (again, this is done automatically by mason-lspconfig).
