### ISSUE TITLE
Fourmolu not installing on darwin-arm64

### ISSUE THREAD

**Issue by ggranberry** [williamboman/mason.nvim#1130]
### I've searched open issues for similar requests

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

I'm trying to install fourmolu through mason in nvchad on my m1 macbook and I've been getting the following error:
<img width="677" alt="Screen Shot 2023-03-24 at 2 31 33 PM" src="https://user-images.githubusercontent.com/5805744/227534590-1ebe2ff6-c5e7-4826-9e25-d2795bf85773.png">

### Expected behavior

I expected a successful install of the formatter

### Affected packages

fourmolu

### Mason output

```Text
<img width="677" alt="Screen Shot 2023-03-24 at 2 31 33 PM" src="https://user-images.githubusercontent.com/5805744/227534590-1ebe2ff6-c5e7-4826-9e25-d2795bf85773.png">
```

### Installation log

```Text
ok
```

### Neovim version (>= 0.7)

NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.3/share/nvim"

Run :checkhealth for more info

### Operating system/version

Darwin Georges-MacBook-Pro.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64

### Healthcheck

```Text
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - WARNING: **Go**: not available
  - WARNING: **cargo**: not available
  - OK: **luarocks**: `/opt/homebrew/bin/luarocks 3.9.2`
  - OK: **Ruby**: `ruby 3.2.0 (2022-12-25 revision a528908271) [arm64-darwin21]`
  - OK: **RubyGem**: `3.4.2`
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `9.2.0`
  - OK: **node**: `v19.4.0`
  - OK: **python3**: `Python 3.10.9`
  - OK: **pip3**: `pip 22.3.1 from /opt/homebrew/lib/python3.10/site-packages/pip (python 3.10)`
  - OK: **javac**: `javac 19.0.1`
  - OK: **java**: `openjdk version "19.0.1" 2022-10-18`
  - WARNING: **julia**: not available
  - ERROR: **wget**: not available
  - OK: **curl**: `curl 7.77.0 (x86_64-apple-darwin21.0) libcurl/7.77.0 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.42.0`
  - OK: **gzip**: `Apple gzip 352.40.6`
  - OK: **tar**: `bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
  - WARNING: **pwsh**: not available
  - OK: **bash**: `GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 8. Remaining: 4992. Limit: 5000. Reset: Fri Mar 24 14:48:49 2023.
```

### Screenshots

<img width="677" alt="Screen Shot 2023-03-24 at 2 31 33 PM" src="https://user-images.githubusercontent.com/5805744/227534590-1ebe2ff6-c5e7-4826-9e25-d2795bf85773.png">

**Comment by williamboman** [comment]
Try pulling the latest plugin version

**Comment by ggranberry** [comment]
That worked!
