### ISSUE TITLE
rust-analyzer release file not found for Linux x64

### ISSUE THREAD

**Issue by Gelio** [williamboman/mason.nvim#1142]
### I've searched open issues for similar requests

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes (I'm at 1f8e3a51d6370304ad29ca4f22fcb374018840db)

### Problem description

I'm trying to update [rust-analyzer](https://github.com/rust-lang/rust-analyzer) from [release 2023-03-13](https://github.com/rust-lang/rust-analyzer/releases/tag/2023-03-13) to [release 2023-03-27](https://github.com/rust-lang/rust-analyzer/releases/tag/2023-03-27). I get the following message in the update log:

```
Could not find which release file to download.
Most likely the current operating system or architecture is not supported (Linux_x64).
```

I didn't have any problems updating rust-analyzer (or any other package) before. I was able to update other packages today but not rust-analyzer.

I compared the names of release artifacts between these 2 releases. I selected the `ul` HTML element which holds the list of artifacts on the releases page and used the following code to get the names `Array.from($0.querySelectorAll('a')).map(x => x.textContent.trim())`.  They are identical:

```json
[
  "rust-analyzer-aarch64-apple-darwin.gz",
  "rust-analyzer-aarch64-pc-windows-msvc.gz",
  "rust-analyzer-aarch64-pc-windows-msvc.zip",
  "rust-analyzer-aarch64-unknown-linux-gnu.gz",
  "rust-analyzer-alpine-x64.vsix",
  "rust-analyzer-arm-unknown-linux-gnueabihf.gz",
  "rust-analyzer-darwin-arm64.vsix",
  "rust-analyzer-darwin-x64.vsix",
  "rust-analyzer-i686-pc-windows-msvc.gz",
  "rust-analyzer-i686-pc-windows-msvc.zip",
  "rust-analyzer-linux-arm64.vsix",
  "rust-analyzer-linux-armhf.vsix",
  "rust-analyzer-linux-x64.vsix",
  "rust-analyzer-no-server.vsix",
  "rust-analyzer-win32-arm64.vsix",
  "rust-analyzer-win32-ia32.vsix",
  "rust-analyzer-win32-x64.vsix",
  "rust-analyzer-x86_64-apple-darwin.gz",
  "rust-analyzer-x86_64-pc-windows-msvc.gz",
  "rust-analyzer-x86_64-pc-windows-msvc.zip",
  "rust-analyzer-x86_64-unknown-linux-gnu.gz",
  "rust-analyzer-x86_64-unknown-linux-musl.gz",
  "Source code\n    (zip)",
  "Source code\n    (tar.gz)"
]
```

I don't think I changed anything in my system that would affect version resolution. Thus, I suspect that something in Mason changed between 2023-03-13 and today that causes it to miss the Linux version. I assume it should download https://github.com/rust-lang/rust-analyzer/releases/download/2023-03-27/rust-analyzer-x86_64-unknown-linux-gnu.gz for me.

### Expected behavior

rust-analyzer is updated to the latest version.

### Affected packages

rust-analyzer

### Mason output

```Text
Could not find which release file to download.
Most likely the current operating system or architecture is not supported (Linux_x64).
```

### Installation log

```Text
[INFO  pon, 27 mar 2023, 10:25:48] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:166: Executing installer for Package(name=rust-analyzer) version="latest"
[DEBUG pon, 27 mar 2023, 10:25:48] .../.local/share/nvim/lazy/mason.nvim/lua/mason-core/fs.lua:71: fs: mkdirp /home/voreny/.local/share/nvim/mason/.packages/rust-analyzer
[DEBUG pon, 27 mar 2023, 10:25:48] ...ocal/share/nvim/lazy/mason.nvim/lua/mason-core/fetch.lua:34: Fetching URL "https://api.mason-registry.dev/api/github/rust-lang/rust-analyzer/releases/latest"
[DEBUG pon, 27 mar 2023, 10:25:48] ...al/share/nvim/lazy/mason.nvim/lua/mason-core/process.lua:116: Spawning cmd="curl", spawn_opts={
  args = { "-H", "Accept: application/vnd.mason-registry.v1+json; q=1.0, application/json; q=0.8", "-H", "User-Agent: mason.nvim (+https://github.com/williamboman/mason.nvim)", "-fsSL", "-X", "GET", "https://api.mason-registry.dev/api/github/rust-lang/rust-analyzer/releases/latest" }
}
[DEBUG pon, 27 mar 2023, 10:25:48] ...al/share/nvim/lazy/mason.nvim/lua/mason-core/process.lua:162: Spawned with pid 331243
[DEBUG pon, 27 mar 2023, 10:25:48] ...al/share/nvim/lazy/mason.nvim/lua/mason-core/process.lua:148: Job pid=331243 exited with exit_code=0, signal=0
[ERROR pon, 27 mar 2023, 10:25:48] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:200: Installation failed for Package(name=rust-analyzer) error="Could not find which release file to download.\nMost likely the current operating system or architecture is not supported (Linux_x64)."
[DEBUG pon, 27 mar 2023, 10:25:48] .../.local/share/nvim/lazy/mason.nvim/lua/mason-core/fs.lua:47: fs: rmrf /home/voreny/.local/share/nvim/mason/.packages/rust-analyzer
[DEBUG pon, 27 mar 2023, 10:25:48] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:39: Building receipt for Package(name=rust-analyzer)
```

### Neovim version (>= 0.7)

NVIM v0.9.0-dev-1291+gbad218cd6
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system/version

Linux grzegorz-lenovo 5.19.0-35-generic #36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Healthcheck

```Text
==============================================================================
mason: require("mason.health").check()

mason.nvim report ~
- OK neovim version >= 0.7.0
- OK Registry `require("mason-registry.index")` is installed.
- OK Registry `github.com/mason-org/mason-registry version: 2023-03-26-abaft-knot` is installed.
- OK **unzip**: `UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.`
- OK **Go**: `go version go1.20.1 linux/amd64`
- OK **cargo**: `cargo 1.68.0 (115f34552 2023-02-26)`
- OK **luarocks**: `/usr/local/bin/luarocks 3.3.1`
- OK **Ruby**: `ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]`
- OK **RubyGem**: `3.3.5`
- WARNING **Composer**: not available
- WARNING **PHP**: not available
- OK **npm**: `9.6.2`
- OK **node**: `v18.12.1`
- OK **python3**: `Python 3.10.6`
- OK **pip3**: `pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)`
- WARNING **javac**: not available
- OK **java**: `openjdk version "11.0.18" 2023-01-17`
- WARNING **julia**: not available
- OK **wget**: `GNU Wget 1.21.2 built on linux-gnu.`
- OK **curl**: `curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.14`
- OK **gzip**: `gzip 1.10`
- OK **tar**: `tar (GNU tar) 1.34`
- WARNING **pwsh**: not available
- OK **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
- OK **sh**: `Ok`
- OK GitHub API rate limit. Used: 2. Remaining: 58. Limit: 60. Reset: pon, 27 mar 2023, 11:18:48.
```

**Comment by williamboman** [comment]
That sounds a bit odd. Could you try pulling the latest plugin version again and run `:MasonUpdate` to fetch the latest version of https://github.com/mason-org/mason-registry/ and see if that fixes things?

**Comment by williamboman** [comment]
> Thanks for fixing the problem!

[No problem!](https://user-images.githubusercontent.com/6705160/227924982-66f8bd3d-75a4-45b6-9986-df6b6ff3b4cf.jpg)

**Comment by lucasgrvarela** [comment]
Just for info, I'm facing the same issue.

**Comment by williamboman** [comment]
That error message suggests you're not running the latest version of mason.nvim

**Comment by grpineiro** [comment]
I think I understand what's going on here. For some reason, in my case, mason is downloading the musl version, when it should be downloading the gnu version. I downloaded the binary directly and went to the .local/share/nvim/mason/binary/rust-analyzer folder and changed the binary and renamed it to musl at the end of the file, and it worked again. Mason should be downloading the gnu version.

**Comment by grpineiro** [comment]
Ignore my message above, apparently uninstalling and reinstalling Mason itself ended up solving my problem.


> With myself updating Mason and uninstalling and installing rust-analyzer, neovim says it can't find the binary. Before it was working. ![Screenshot_20230327_203238](https://user-images.githubusercontent.com/19599330/228090192-0659de7a-5ea4-4077-9fdc-ff7a1de455ff.png)

**Comment by IndianBoy42** [comment]
> > With myself updating Mason and uninstalling and installing rust-analyzer, neovim says it can't find the binary. Before it was working. ![Screenshot_20230327_203238](https://user-images.githubusercontent.com/19599330/228090192-0659de7a-5ea4-4077-9fdc-ff7a1de455ff.png)
> 
> Ignore my message above, apparently uninstalling and reinstalling Mason itself ended up solving my problem.

Could you elaborate on how you fixed this? I uninstalled and reinstalled mason and its still not working

**Comment by aslicedbanjo** [comment]
I'm having the same problem as @grpineiro and @IndianBoy42.

I have the latest Mason. But when I update to the latest `rust-analyzer`, neovim starts reporting that it can't run it - just like @grpineiro's screenshot.

After a little digging, I found that `~/.local/share/nvim/mason/packages/rust-analyzer` contained `rust-analyzer-x86_64-unknown-linux-musl`, which is unexpected as the system is GNU/Linux (actually Ubuntu (GNU/Linux) 22.04.2 LTS x86_64).

Do others have the same in `~/.local/share/nvim/mason/packages/rust-analyzer`?

A work around is to install a slightly older `rust-analyzer`, like so:

`:MasonInstall rust-analyzer@2023-03-20`

which did install the GNU `rust-analyzer`.

https://github.com/rust-lang/rust-analyzer/releases lists the releases. Both 2023-03-20 and 2023-03-27 have a `rust-analyzer-x86_64-unknown-linux-gnu.gz` asset.

**Comment by grpineiro** [comment]
@aslicedbanjo @IndianBoy42 Practically, I really just deleted and installed Mason, but I didn't run "MasonUpdate". It must be because I'm using the older registry.

Now that you two pointed it out, the newer registry is actually downloading the musl version of rust-analyzer, when it should be downloading the gnu version if we're using glibc.

So my error is not completely resolved.

**Comment by aslicedbanjo** [comment]
There is now a new version of `rust-analyzer`, version 2023-04-03, and mason has correctly installed it. So it seems like the problem is gone now :crossed_fingers:.
