### ISSUE TITLE
pylsp does not respect root_dir

### ISSUE THREAD

**Issue by jswinarton** [williamboman/mason.nvim#1201]
### I've searched open issues for similar requests

Yes

### I've manually reviewed logs to find potential errors

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

When installing the python-lsp-server with mason, certain settings (such as `root_dir`) are not respected, if they are installed with mason.nvim.

I don't experience this issue if I install python-lsp-server myself with pip (either with system Python or in a virtualenv), which leads me to believe the reason this is happening has something to do with the fact that Mason installs the package into its own virtualenv.

### Expected behavior

When installing pylsp with Mason, I should get the same behavior as when I install manually.

### Steps to reproduce

1. Create some kind of Python project. Add a `pyproject.toml` file. In this file, change some kind of pylint setting.
2. Open a Python file and write code in a way that violates the standard pylint rules but respects your custom rule.
3. Observe that the custom pylint rule is not respected.

### Affected packages

pylsp

### Neovim version (>= 0.7)

NVIM v0.9.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-10 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/__w/neovim/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/__w/neovim/neovim/.deps/usr/include -I/__w/neovim/neovim/build/src/nvim/auto -I/__w/neovim/neovim/build/include -I/__w/neovim/neovim/build/cmake.config -I/__w/neovim/neovim/src -I/usr/include -I/__w/neovim/neovim/.deps/usr/include -I/__w/neovim/neovim/.deps/usr/include -I/__w/neovim/neovim/.deps/usr/include -I/__w/neovim/neovim/.deps/usr/include -I/__w/neovim/neovim/.deps/usr/include -I/__w/neovim/neovim/.deps/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info

### Operating system/version

Linux dionysus 5.19.0-38-generic #39-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 17:33:16 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Healthcheck

```Text
mason: require("mason.health").check()

mason.nvim report ~
- OK neovim version >= 0.7.0
- OK Registry `require("mason-registry.index")` is installed.
- OK Registry `github.com/mason-org/mason-registry version: 2023-04-08-puffy-spain` is installed.
- OK **unzip**: `UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.`
- OK **Go**: `go version go1.19.5 linux/amd64`
- OK **cargo**: `cargo 1.66.1 (ad779e08b 2023-01-10)`
- WARNING **luarocks**: not available
- WARNING **Ruby**: not available
- WARNING **RubyGem**: not available
- WARNING **Composer**: not available
- WARNING **PHP**: not available
- OK **npm**: `9.6.2`
- OK **node**: `v19.8.1`
- OK **python3**: `Python 3.10.7`
- OK **pip3**: `pip 23.0.1 from /home/jeremy/.local/lib/python3.10/site-packages/pip (python 3.10)`
- WARNING **javac**: not available
- WARNING **java**: not available
- WARNING **julia**: not available
- OK **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
- OK **curl**: `curl 7.85.0 (x86_64-pc-linux-gnu) libcurl/7.85.0 OpenSSL/3.0.5 zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.3 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.49.0 librtmp/2.3`
- OK **gzip**: `gzip 1.12`
- OK **tar**: `tar (GNU tar) 1.34`
- WARNING **pwsh**: not available
- OK **bash**: `GNU bash, version 5.2.2(1)-release (x86_64-pc-linux-gnu)`
- OK **sh**: `Ok`
- OK GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: Sat 08 Apr 2023 06:51:50 PM.
```

### Screenshots or recordings

The following `pyproject.toml` file:

![screenshot-2023-04-08-17-55-07](https://user-images.githubusercontent.com/1616117/230744184-0aa53ee0-26f3-4335-aea5-602959a3d5c3.png)

Produces the following error in a Python file in the same `root_dir`:

![screenshot-2023-04-08-17-54-56](https://user-images.githubusercontent.com/1616117/230744170-3e849073-1e50-40ff-a1a3-72ba44d4fbb1.png)

This error does not appear if I uninstall Mason and install the `python-lsp-server` package and configure it "manually" (i.e. with `nvim-lspconfig`).

**Comment by jswinarton** [comment]
My apologies, this was premature -- turns out I was seeing errors for the wrong linter and didn't have my LSP settings correctly configured.

**Comment by PBHDK** [comment]
@jswinarton how did you end up solving it? 

I'm getting the same error as you, and am suspecting that my config isn't being respected because I'm probably missing something.

```
  require 'lspconfig'.pylsp.setup {
          settings = {
                  pylsp = {
                          plugins = {
                                  ruff = { enabled = true },
                                  pyflakes = { enabled = true },
                                  yapf = {
                                          enabled = true,
                                          based_on_style = "pep8",
                                          column_limit = 120
                                  },
                                  mypy = {
                                          enabled = true,
                                          live_mode = true,
                                          strict = true
                                  },
                                  isort = { enabled = true },
                                  rope = { enabled = true }
                          },
                  },
          },
  }
```

Plugins where installed with `PylspInstall <plugin>`.

Any pointers?

CC: @williamboman
