### ISSUE TITLE
npm: support tag(version)

### ISSUE THREAD

**Issue by 2nthony** [williamboman/mason.nvim#1205]
### I've searched open issues for similar requests

Yes

### Is your feature request related to a problem? Please describe.

https://github.com/williamboman/mason.nvim/blob/3fb2be48864b7850a26c54c04cedb54e95dcdf3f/lua/mason/providers/client/npm.lua#L8

my case is for `vue-language-server`, the latest version now is in `next` tag, in VS Code I can use the `next` version by `switch to pre-release version`.

### Describe the solution you'd like

actually I have no idea for this, but maybe have the `npm` option:

```lua
mason.setup {
	npm = {
		package_version = {
			['vue-language-server'] = '@next', --defaults to @latest
			-- others ...
			}
	}
}
```

### Additional context

<img width="773" alt="image" src="https://user-images.githubusercontent.com/19513289/231245665-c7556ca0-ad15-4bad-8ef3-3b1cb294b55c.png">

**Comment by williamboman** [comment]
Hey! So `latest` and `next` have distinct meanings in the npm versioning scheme. `next` usually refers to a pre-release or a release candidate, not yet ready to be considered stable. If you think the vue-language-service have made an error in their tagging you should report it to them

**Comment by williamboman** [comment]
You can always install it through mason by providing a version specifier, for example: `:MasonInstall vue-language-server@next`

**Comment by 2nthony** [comment]
just let you know:

I was installed the 1.3.4 version: `:MasonInstall vue-language-server@1.3.4`, if I check the version again, will get this:

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/19513289/231351810-cdefa50b-a237-48a5-94fd-92fb18bfbdb7.png">
