### ISSUE TITLE
Cannot install js-debug-adapter@v1.76.1

### ISSUE THREAD

**Issue by Tiseno** [williamboman/mason.nvim#1250]
### I've searched open issues for similar requests

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

The latest version of js-debug-adapter introduced breaking changes for my dap setup, but I cannot install the working version 1.76.1, or any other older version for that matter. I noticed the isse https://github.com/williamboman/mason.nvim/pull/1122 and https://github.com/williamboman/mason.nvim/issues/1120 and https://github.com/mason-org/mason-registry/pull/930, so it seems there has been a change in how the package is installed.

### Expected behavior

That the install succeeds for specific versions.

### Affected packages

js-debug-adapter

### Mason output

```Text
Fetching available versions…
        Downloading file "https://github.com/microsoft/vscode-js-debug/releases/download/v1.76.1/js-debug-dap-v1.76.1.tar.gz"...
        spawn: wget failed with exit code 8 and signal 0. 
        Failed to download file "https://github.com/microsoft/vscode-js-debug/releases/download/v1.76.1/js-debug-dap-v1.76.1.tar.gz".
```

### Installation log

```Text
[DEBUG sön 23 apr 2023 10:00:56] .../tiseno/.vim/plugged/mason.nvim/lua/mason-core/fetch.lua:34: Fetching URL "https://api.mason-registry.dev/api/github/mason-org/mason-registry/releases/latest"
[DEBUG sön 23 apr 2023 10:00:56] ...iseno/.vim/plugged/mason.nvim/lua/mason-core/process.lua:116: Spawning cmd="curl", spawn_opts={
  args = { "-H", "Accept: application/vnd.mason-registry.v1+json; q=1.0, application/json; q=0.8", "-H", "User-Agent: mason.nvim (+https://github.com/williamboman/mason.nvim)", "-fsSL", "-X", "GET", "https://api.mason-registry.dev/api/github/mason-org/mason-registry/releases/latest" }
}
[DEBUG sön 23 apr 2023 10:00:56] ...iseno/.vim/plugged/mason.nvim/lua/mason-core/process.lua:162: Spawned with pid 22401
[DEBUG sön 23 apr 2023 10:00:56] ...iseno/.vim/plugged/mason.nvim/lua/mason-core/process.lua:148: Job pid=22401 exited with exit_code=0, signal=0
[DEBUG sön 23 apr 2023 10:00:56] .../tiseno/.vim/plugged/mason.nvim/lua/mason-core/fetch.lua:34: Fetching URL "https://github.com/mason-org/mason-registry/releases/download/2023-04-23-irate-factor/registry.json.zip"
[DEBUG sön 23 apr 2023 10:00:56] ...iseno/.vim/plugged/mason.nvim/lua/mason-core/process.lua:116: Spawning cmd="curl", spawn_opts={
  args = { "-H", "User-Agent: mason.nvim (+https://github.com/williamboman/mason.nvim)", "-fsSL", "-X", "GET", "-o", "/home/tiseno/.local/share/nvim/mason/registries/github/mason-org/mason-registry/registry.json.zip", "https://github.com/mason-org/mason-registry/releases/download/2023-04-23-irate-factor/registry.json.zip" }
}
[DEBUG sön 23 apr 2023 10:00:56] ...iseno/.vim/plugged/mason.nvim/lua/mason-core/process.lua:162: Spawned with pid 22403
[DEBUG sön 23 apr 2023 10:00:57] ...iseno/.vim/plugged/mason.nvim/lua/mason-core/process.lua:148: Job pid=22403 exited with exit_code=0, signal=0
[DEBUG sön 23 apr 2023 10:00:57] /home/tiseno/.vim/plugged/mason.nvim/lua/mason-core/fs.lua:59: fs: unlink /home/tiseno/.local/share/nvim/mason/registries/github/mason-org/mason-registry/registry.json.zip
[DEBUG sön 23 apr 2023 10:00:57] .../tiseno/.vim/plugged/mason.nvim/lua/mason-core/fetch.lua:34: Fetching URL "https://github.com/mason-org/mason-registry/releases/download/2023-04-23-irate-factor/checksums.txt"
[DEBUG sön 23 apr 2023 10:00:57] ...iseno/.vim/plugged/mason.nvim/lua/mason-core/process.lua:116: Spawning cmd="curl", spawn_opts={
  args = { "-H", "User-Agent: mason.nvim (+https://github.com/williamboman/mason.nvim)", "-fsSL", "-X", "GET", "https://github.com/mason-org/mason-registry/releases/download/2023-04-23-irate-factor/checksums.txt" }
}
[DEBUG sön 23 apr 2023 10:00:57] ...iseno/.vim/plugged/mason.nvim/lua/mason-core/process.lua:162: Spawned with pid 22406
[DEBUG sön 23 apr 2023 10:00:58] ...iseno/.vim/plugged/mason.nvim/lua/mason-core/process.lua:148: Job pid=22406 exited with exit_code=0, signal=0
[INFO  sön 23 apr 2023 10:01:03] ...vim/plugged/mason.nvim/lua/mason-core/installer/init.lua:166: Executing installer for Package(name=js-debug-adapter) {
  version = "v1.76.1"
}
[DEBUG sön 23 apr 2023 10:01:03] /home/tiseno/.vim/plugged/mason.nvim/lua/mason-core/fs.lua:71: fs: mkdirp /home/tiseno/.local/share/nvim/mason/.packages/js-debug-adapter
[DEBUG sön 23 apr 2023 10:01:03] ...ed/mason.nvim/lua/mason-core/installer/registry/init.lua:145: Compiling installer. js-debug-adapter {
  version = "v1.76.1"
}
[DEBUG sön 23 apr 2023 10:01:03] ...ed/mason.nvim/lua/mason-core/installer/registry/init.lua:107: Parsing spec js-debug-adapter {
  version = "v1.76.1"
}
[DEBUG sön 23 apr 2023 10:01:03] .../tiseno/.vim/plugged/mason.nvim/lua/mason-core/fetch.lua:34: Fetching URL "https://api.mason-registry.dev/api/github/microsoft/vscode-js-debug/releases/all"
[DEBUG sön 23 apr 2023 10:01:03] ...iseno/.vim/plugged/mason.nvim/lua/mason-core/process.lua:116: Spawning cmd="curl", spawn_opts={
  args = { "-H", "Accept: application/vnd.mason-registry.v1+json; q=1.0, application/json; q=0.8", "-H", "User-Agent: mason.nvim (+https://github.com/williamboman/mason.nvim)", "-fsSL", "-X", "GET", "https://api.mason-registry.dev/api/github/microsoft/vscode-js-debug/releases/all" }
}
[DEBUG sön 23 apr 2023 10:01:03] ...iseno/.vim/plugged/mason.nvim/lua/mason-core/process.lua:162: Spawned with pid 22409
[DEBUG sön 23 apr 2023 10:01:03] .../tiseno/.vim/plugged/mason.nvim/lua/mason-core/fetch.lua:34: Fetching URL "https://api.mason-registry.dev/api/github/mason-org/mason-registry/releases/latest"
[DEBUG sön 23 apr 2023 10:01:03] ...iseno/.vim/plugged/mason.nvim/lua/mason-core/process.lua:116: Spawning cmd="curl", spawn_opts={
  args = { "-H", "Accept: application/vnd.mason-registry.v1+json; q=1.0, application/json; q=0.8", "-H", "User-Agent: mason.nvim (+https://github.com/williamboman/mason.nvim)", "-fsSL", "-X", "GET", "https://api.mason-registry.dev/api/github/mason-org/mason-registry/releases/latest" }
}
[DEBUG sön 23 apr 2023 10:01:03] ...iseno/.vim/plugged/mason.nvim/lua/mason-core/process.lua:162: Spawned with pid 22411
[DEBUG sön 23 apr 2023 10:01:03] ...iseno/.vim/plugged/mason.nvim/lua/mason-core/process.lua:148: Job pid=22409 exited with exit_code=0, signal=0
[DEBUG sön 23 apr 2023 10:01:03] ...ged/mason.nvim/lua/mason-core/installer/managers/std.lua:95: std: downloading file "https://github.com/microsoft/vscode-js-debug/releases/download/v1.76.1/js-debug-dap-v1.76.1.tar.gz"
[DEBUG sön 23 apr 2023 10:01:03] .../tiseno/.vim/plugged/mason.nvim/lua/mason-core/fetch.lua:34: Fetching URL "https://github.com/microsoft/vscode-js-debug/releases/download/v1.76.1/js-debug-dap-v1.76.1.tar.gz"
[DEBUG sön 23 apr 2023 10:01:03] ...iseno/.vim/plugged/mason.nvim/lua/mason-core/process.lua:116: Spawning cmd="curl", spawn_opts={
  args = { "-H", "User-Agent: mason.nvim (+https://github.com/williamboman/mason.nvim)", "-fsSL", "-X", "GET", "-o", "/home/tiseno/.local/share/nvim/mason/.packages/js-debug-adapter/./js-debug-dap-v1.76.1.tar.gz", "https://github.com/microsoft/vscode-js-debug/releases/download/v1.76.1/js-debug-dap-v1.76.1.tar.gz" }
}
[DEBUG sön 23 apr 2023 10:01:03] ...iseno/.vim/plugged/mason.nvim/lua/mason-core/process.lua:162: Spawned with pid 22413
[DEBUG sön 23 apr 2023 10:01:03] ...iseno/.vim/plugged/mason.nvim/lua/mason-core/process.lua:148: Job pid=22411 exited with exit_code=0, signal=0
[DEBUG sön 23 apr 2023 10:01:03] .../tiseno/.vim/plugged/mason.nvim/lua/mason-core/fetch.lua:34: Fetching URL "https://github.com/mason-org/mason-registry/releases/download/2023-04-23-irate-factor/registry.json.zip"
[DEBUG sön 23 apr 2023 10:01:03] ...iseno/.vim/plugged/mason.nvim/lua/mason-core/process.lua:116: Spawning cmd="curl", spawn_opts={
  args = { "-H", "User-Agent: mason.nvim (+https://github.com/williamboman/mason.nvim)", "-fsSL", "-X", "GET", "-o", "/home/tiseno/.local/share/nvim/mason/registries/github/mason-org/mason-registry/registry.json.zip", "https://github.com/mason-org/mason-registry/releases/download/2023-04-23-irate-factor/registry.json.zip" }
}
[DEBUG sön 23 apr 2023 10:01:03] ...iseno/.vim/plugged/mason.nvim/lua/mason-core/process.lua:162: Spawned with pid 22415
[DEBUG sön 23 apr 2023 10:01:03] ...iseno/.vim/plugged/mason.nvim/lua/mason-core/process.lua:148: Job pid=22413 exited with exit_code=22, signal=0
[DEBUG sön 23 apr 2023 10:01:03] ...iseno/.vim/plugged/mason.nvim/lua/mason-core/process.lua:116: Spawning cmd="wget", spawn_opts={
  args = { "--header=User-Agent: mason.nvim (+https://github.com/williamboman/mason.nvim)", "-nv", "-o", "/dev/null", "-O", "/home/tiseno/.local/share/nvim/mason/.packages/js-debug-adapter/./js-debug-dap-v1.76.1.tar.gz", "--method=GET", "https://github.com/microsoft/vscode-js-debug/releases/download/v1.76.1/js-debug-dap-v1.76.1.tar.gz" }
}
[DEBUG sön 23 apr 2023 10:01:03] ...iseno/.vim/plugged/mason.nvim/lua/mason-core/process.lua:162: Spawned with pid 22419
[DEBUG sön 23 apr 2023 10:01:04] ...iseno/.vim/plugged/mason.nvim/lua/mason-core/process.lua:148: Job pid=22415 exited with exit_code=0, signal=0
[DEBUG sön 23 apr 2023 10:01:04] /home/tiseno/.vim/plugged/mason.nvim/lua/mason-core/fs.lua:59: fs: unlink /home/tiseno/.local/share/nvim/mason/registries/github/mason-org/mason-registry/registry.json.zip
[DEBUG sön 23 apr 2023 10:01:04] .../tiseno/.vim/plugged/mason.nvim/lua/mason-core/fetch.lua:34: Fetching URL "https://github.com/mason-org/mason-registry/releases/download/2023-04-23-irate-factor/checksums.txt"
[DEBUG sön 23 apr 2023 10:01:04] ...iseno/.vim/plugged/mason.nvim/lua/mason-core/process.lua:116: Spawning cmd="curl", spawn_opts={
  args = { "-H", "User-Agent: mason.nvim (+https://github.com/williamboman/mason.nvim)", "-fsSL", "-X", "GET", "https://github.com/mason-org/mason-registry/releases/download/2023-04-23-irate-factor/checksums.txt" }
}
[DEBUG sön 23 apr 2023 10:01:04] ...iseno/.vim/plugged/mason.nvim/lua/mason-core/process.lua:162: Spawned with pid 22420
[DEBUG sön 23 apr 2023 10:01:04] ...iseno/.vim/plugged/mason.nvim/lua/mason-core/process.lua:148: Job pid=22419 exited with exit_code=8, signal=0
[ERROR sön 23 apr 2023 10:01:04] ...vim/plugged/mason.nvim/lua/mason-core/installer/init.lua:200: Installation failed for Package(name=js-debug-adapter) error='spawn: wget failed with exit code 8 and signal 0. \nFailed to download file "https://github.com/microsoft/vscode-js-debug/releases/download/v1.76.1/js-debug-dap-v1.76.1.tar.gz".'
[DEBUG sön 23 apr 2023 10:01:04] /home/tiseno/.vim/plugged/mason.nvim/lua/mason-core/fs.lua:47: fs: rmrf /home/tiseno/.local/share/nvim/mason/.packages/js-debug-adapter
[DEBUG sön 23 apr 2023 10:01:04] ...vim/plugged/mason.nvim/lua/mason-core/installer/init.lua:39: Building receipt for Package(name=js-debug-adapter)
[DEBUG sön 23 apr 2023 10:01:04] ...iseno/.vim/plugged/mason.nvim/lua/mason-core/process.lua:148: Job pid=22420 exited with exit_code=0, signal=0
```

### Neovim version (>= 0.7)

NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az183-550

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info

### Operating system/version

Linux 5.19.0-38-generic #39~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 21:16:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Healthcheck

```Text
mason: require("mason.health").check()
========================================================================
## mason.nvim
  - OK: neovim version >= 0.7.0

## mason.nvim [Registries]
  - OK: Registry `require("mason-registry.index")` is installed.
  - OK: Registry `github.com/mason-org/mason-registry version: 2023-04-23-irate-factor` is installed.

## mason.nvim [Core utils]
  - OK: unzip: `UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.`
  - OK: wget: `GNU Wget 1.21.2 built on linux-gnu.`
  - OK: curl: `curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.14`
  - OK: gzip: `gzip 1.10`
  - OK: tar: `tar (GNU tar) 1.34`
  - OK: bash: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: sh: `Ok`

## mason.nvim [Languages]
  - WARNING: Ruby: not available
    - ADVICE:
      - spawn: ruby failed with exit code - and signal -. ruby is not executable
  - WARNING: Composer: not available
    - ADVICE:
      - spawn: composer failed with exit code - and signal -. composer is not executable
  - WARNING: PHP: not available
    - ADVICE:
      - spawn: php failed with exit code - and signal -. php is not executable
  - WARNING: RubyGem: not available
    - ADVICE:
      - spawn: gem failed with exit code - and signal -. gem is not executable
  - OK: Go: `go version go1.19 linux/amd64`
  - OK: node: `v18.15.0`
  - OK: cargo: `cargo 1.64.0 (387270bc7 2022-09-16)`
  - WARNING: julia: not available
    - ADVICE:
      - spawn: julia failed with exit code - and signal -. julia is not executable
  - OK: python3: `Python 3.10.6`
  - OK: python3_host_prog: `Python 3.10.6`
  - OK: java: `openjdk version "11.0.18" 2023-01-17`
  - OK: luarocks: `/usr/bin/luarocks 3.8.0`
  - OK: javac: `javac 17.0.6`
  - OK: npm: `9.5.0`
  - OK: pip3: `pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)`
  - OK: python3_host_prog pip: `pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)`

## mason.nvim [GitHub]
  - OK: GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: sön 23 apr 2023 11:04:48.
    Install and authenticate via gh-cli to increase rate limit.
```

**Comment by williamboman** [comment]
Update mason.nvim!

**Comment by Tiseno** [comment]
I can only assume that you misread my issue, updating the registry does not help.
I am not trying to install the latest version, but the 1.76.1 version, and my guess is that the latest registry does not allow for it (as described [in this issue](https://github.com/williamboman/mason.nvim/issues/1120) where you couldnt install the latest version before you updated to the latest registry).

Is this intended behavior? i.e. not being fully backwards compatible, am I supposed to downgrade to an earlier registry to install earlier versions?

**Comment by williamboman** [comment]
Ah I didn't realize you were trying to install a different version. Installing a different version won't work if the provided version isn't compatible with the source definition in the mason registry, which is what's happening in this case.

I was under the impression that the new release asset was the preferred way of installation, as it's also documented in the [nvim-dap wiki](https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#vscode-js-debug) (it also works perfectly fine for me). I'm unsure why they've only published it for 1.77.0 and not subsequent releases though.

> To me it seems like it would be impossible to install a previous version as soon as the install strategy is changed?

In general, installing different versions works fine for the vast majority of packages as most have a stable history of releases. While it is possible to define overrides for specific version ranges (to maintain backwards compatibility), it's not something that is done yet for maintainability purposes.

**Comment by Tiseno** [comment]
We share the same impression, 1.77 has a real dap implementation and I have now configured it correctly.
So I have no need to install the previous version any more but I would think saving the install strategy for previous versions would be the default way to do it when the strategy changes for a realese?

The mason registry should maybe have changed to a different name altogether for 1.77 as it is a totally different executable than 1.76.

**Comment by williamboman** [comment]
> Not only did this change break the configuration for everyone using it, there was no way of installing the previous version (if I understand everything correctly), which is a bit problematic I think 😄

Hm really 😱? I figured the CLI interface was the same between the two executables. I didn't have to make any changes. Were you perhaps reaching into the internal package structure, for example by specifying the full path to the .js script or similar? Doing so is prone to breaking across versions and is not a stable interface (instead, the `$MASON/bin`, `$MASON/share`, etc. locations are considered stable).

**Comment by Tiseno** [comment]
@williamboman So this should probably be an issue in the registry instead

**Comment by williamboman** [comment]
@Tiseno Would you like there to be a supplementary package for the "old" js-debug-adapter? I agree that suddenly moving the `js-debug-adapter` to use the new executable might've not been the best idea in hindsight, I assumed it'd be seamless but after you pointed it out I saw that it broke usage with the `nvim-dap-vscode-js` plugin.

I think the fundamental problem here is that we're pulling the assets of a VSCode plugin which is unstable in nature because there's no contract with outside usage. I don't think reverting the change in mason-registry would be a good idea because it's been live for 1+ month now. Am I right in assuming that `nvim-dap-vscode-js` is no longer needed, with the introduction of the DAP compatible executable? In that case I feel like there's not much to do, other than users migrating to it?

**Comment by Tiseno** [comment]
I do not use `nvim-dap-vscode-js` anymore but I think it added some other nice features like default settings and other stuff, but I never used them.

My point is that the registry is incomplete, it does not support installing older versions of the package anymore (and probably others) and in this particular instance I would propose adding the old configuration for installing for versions before 1.77, and that should have been, in my opinion, the default way of handling a change in configuration of **any package in the registry**. And that will fix the issue for users in this case, as they then can just actually install the older version which they relied on.

But for me as a user of mason and the mason-registry I am concerned about the strategy of not by default keeping old configurations around for previous versions. In my opinion it should be a top priority for a package manager / package registry to keep a history of old configurations. Is there just no support for doing this in a nice way yet?
You mentioned
> While it is possible to define overrides for specific version ranges (to maintain backwards compatibility), it's not something that is done yet for maintainability purposes.

so it seems to be doable? :shrug: I dont understand the point about "maintainability purposes" though.

Should I put it up as an issue in the registry to do this for this package?
Why is it not, or rather, should it not be the default to pin the old configuration when it changes?
Are there any drawbacks to this?

**Comment by williamboman** [comment]
> My point is that the registry is incomplete, it does not support installing older versions of the package anymore (and probably others) and in this particular instance I would propose adding the old configuration for installing for versions before 1.77, and that should have been, in my opinion, the default way of handling a change in configuration of **any package in the registry**. And that will fix the issue for users in this case, as they then can just actually install the older version which they relied on.

Installing versions other than the latest is not guaranteed to work. I don't think this is stated clearly anywhere at the moment, but that's always been the case. The registry tracks latest versions and only guarantees that these work, one can always pin the registry version itself to essentially freeze all package versions.

> so it seems to be doable? 🤷 I dont understand the point about "maintainability" though, it is just a history of configurations 🤔
> 
> Should I put it up as an issue in the registry to do this for this package? Why is it not, or rather, should it not be the default to pin the old configuration when it changes? Are there any drawbacks to this?

It's simply a feature that hasn't been properly built out yet, so before package definitions starts to broadly make use of it there needs to be some more work done.

**Comment by Tiseno** [comment]
> The registry tracks latest versions and only guarantees that these work, one can always pin the registry version itself to essentially freeze all package versions.
Alright! That is the solution then :)

**Comment by williamboman** [comment]
> How is it done? I don't find it in the help docs.

Ah, you can do it when setting up mason:

```lua
require("mason").setup {
  registries = {
     "github:mason-org/mason-registry@version"
  }
}
```

**Comment by williamboman** [comment]
So it turns out I had already written the code to support version overrides, was just a matter of fixing the schema in the registry to allow this in the package specifications themselves. FWIW, js-debug-adapter [now supports the previous version](https://github.com/mason-org/mason-registry/pull/1891)

**Comment by Tiseno** [comment]
Haha ok! That is awesome
