### ISSUE TITLE
LSP[puppet][Warning] An error occured while starting the Language Server. The server has been disabled.

### ISSUE THREAD

**Issue by techsk8** [williamboman/mason.nvim#1258]
### Problem description

![0](https://i.imgur.com/SufcOdZ.png)

I am trying to use the [puppet-editor-services](https://github.com/puppetlabs/puppet-editor-services) LSP and I'm getting the error that you see in the title. I've tried running the LSP manually and it works. 
```console
root@puppet-server:~/.local/share/lvim/mason/packages/puppet-editor-services# ./puppet-languageserver
LANGUAGE SERVER RUNNING localhost:37571

…

[mac@mac] ➜ bin ./puppet-languageserver
LANGUAGE SERVER RUNNING localhost:53529
```

I would really appreciate if this would work on `lunarvim` since I don't use other IDEs, besides `lunarvim / neovim`, and puppet lsp doesn't work on any of them.

I have bumped into this thing on both my Ubuntu 20.04 puppet-server and my MacOS 13 machine.
I have the same versions of `nvim` and `lunarvim` installed on both
Mention: I have built `neovim` from [source](https://github.com/LunarVim/nvim-basic-ide#install-neovim-09).

The interesting fact is that while yesterday I was getting this error which is tied to the puppet LSP:
```console
[START][2023-04-24 11:57:15] LSP logging initiated
   30 [ERROR][2023-04-24 11:57:15] .../vim/lsp/rpc.lua:734  "rpc" "puppet-languageserver" "stderr"  "/usr/bin/env: ‘ruby’: No such file or directory\n"
   29 [START][2023-04-24 11:57:42] LSP logging initiated
   28 [ERROR][2023-04-24 11:57:42] .../vim/lsp/rpc.lua:734  "rpc" "puppet-languageserver" "stderr"  "/usr/bin/env: ‘ruby’: No such file or directory\n"
   27 [ERROR][2023-04-24 11:59:03] .../vim/lsp/rpc.lua:734  "rpc" "puppet-languageserver" "stderr"  "/usr/bin/env: ‘ruby’: No such file or directory\n"
   26 [START][2023-04-25 03:48:29] LSP logging initiated
```

Today I'm not getting any error, only some other irrelevant errors coming from bashls regarding my .bashrc

Regarding the logs: on my Ubuntu 20.04 instance I have ruby installed from apt:
```console
root@puppet-server:~/production# ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
``` 

And on the macOS I'm using rvm
```console
[mac@mac] ➜ ~ rvm list
   ruby-2.7.6 [ arm64 ]
   ruby-2.7.8 [ arm64 ]
   ruby-3.0.0 [ arm64 ]
=* ruby-3.2.2 [ arm64 ]

# => - current
# =* - current && default
#  * - default

[mac@mac] ➜ ~ ruby -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
```

### Expected behavior

To just work: 

![1](https://i.imgur.com/miyfd33.png) 

### Steps to reproduce
1. lvim test.pp
2. The LSP for puppet will be installed automatically if you're opening a .pp file for the first time
3. And whenever you open a .pp file the LSP will get disabled for some reason, see the error I pasted

### Affected packages
```console
puppet-editor-services
```

### Neovim version (>= 0.7)
```console
NVIM v0.9.0-dev-1338+g9e7426718
Build type: Release
LuaJIT 2.1.0-beta3
```
### Operating system/version
```console
Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103 arm64

# and

Linux puppet-server 5.4.0-147-generic #164-Ubuntu SMP Tue Mar 21 14:23:17 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Healthcheck

```Text
![2](https://i.imgur.com/PxsRYPR.png)
```

**Comment by techsk8** [comment]
The workaround worked for 1 days, now I'm back to point 0 and it's showing no logs…

**Comment by techsk8** [comment]
Update: I have it up and running again: What I had to do was to reinstall the gems using ruby 3.1.0
```console
root@puppet-server:~# rbenv global 3.1.0
root@puppet-server:~# rbenv version
3.1.0 (set by /root/.rbenv/version)
root@puppet-server:~# ruby -v
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-linux]
```
So, if you have the 3.1.0 version or higher I presume, it will work
But you need to reinstall the gems with that version.


Otherwise I was getting this error
```console
root@puppet-server:~/.local/share/lvim/mason/bin# ./puppet-languageserver --debug=stdout
I, [2023-04-26T11:00:07.927392 #49710]  INFO -- : Language Server is v1.3.1
D, [2023-04-26T11:00:07.927472 #49710] DEBUG -- : Loading gems...
E, [2023-04-26T11:00:07.983464 #49710] ERROR -- : Error while loading a critical gem: cannot load such file -- puppet ["<internal:/root/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'", "<internal:/root/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'", "/root/.local/share/lvim/mason/packages/puppet-editor-services/lib/puppet_languageserver.rb:74:in `require_gems'", "/root/.local/share/lvim/mason/packages/puppet-editor-services/lib/puppet_languageserver.rb:215:in `init_puppet'", "./puppet-languageserver:14:in `<main>'"]
I, [2023-04-26T11:00:07.984240 #49710]  INFO -- : Starting RPC Server...
I, [2023-04-26T11:00:07.984305 #49710]  INFO -- : Configured the Language Server to use the Disabled Message Router
D, [2023-04-26T11:00:07.984326 #49710] DEBUG -- : Using TCP Server
D, [2023-04-26T11:00:08.010854 #49710] DEBUG -- : TCPSRV: Services running. Press ^C to stop
D, [2023-04-26T11:00:08.013460 #49710] DEBUG -- : TCPSRV: Will stop the server in 10 seconds if no connection is made.
D, [2023-04-26T11:00:08.013706 #49710] DEBUG -- : TCPSRV: Will stop the server when client disconnects
LANGUAGE SERVER RUNNING localhost:44471
D, [2023-04-26T11:00:08.011941 #49710] DEBUG -- : TCPSRV: Started listening on localhost:44471.
D, [2023-04-26T11:00:18.023997 #49710] DEBUG -- : TCPSRV: No connection has been received in 10 seconds.  Shutting down server.
D, [2023-04-26T11:00:18.024237 #49710] DEBUG -- : TCPSRV: Stopping services
D, [2023-04-26T11:00:18.024374 #49710] DEBUG -- : TCPSRV: Stopped listening on localhost:44471
D, [2023-04-26T11:00:18.024528 #49710] DEBUG -- : TCPSRV: Started shutdown process. Press ^C to force quit.
D, [2023-04-26T11:00:18.024659 #49710] DEBUG -- : TCPSRV: Stopping services
D, [2023-04-26T11:00:18.024805 #49710] DEBUG -- : TCPSRV: Waiting for workers to cycle down
I, [2023-04-26T11:00:18.042659 #49710]  INFO -- : Language Server exited.
```

And now it all works
```console
root@puppet-server:~/.local/share/lvim/mason/packages/puppet-editor-services# ./puppet-languageserver --debug=stdout
I, [2023-04-26T11:01:38.772401 #49932]  INFO -- : Language Server is v1.3.1
D, [2023-04-26T11:01:38.772507 #49932] DEBUG -- : Loading gems...
I, [2023-04-26T11:01:39.837403 #49932]  INFO -- : Using Puppet v8.0.0
I, [2023-04-26T11:01:39.837475 #49932]  INFO -- : Using Facter v4.4.0
D, [2023-04-26T11:01:39.837583 #49932] DEBUG -- : Detected additional puppet settings []
I, [2023-04-26T11:01:39.851245 #49932]  INFO -- : Initializing settings...
I, [2023-04-26T11:01:39.852194 #49932]  INFO -- : Starting RPC Server...
D, [2023-04-26T11:01:39.852951 #49932] DEBUG -- : Using TCP Server
D, [2023-04-26T11:01:39.855072 #49932] DEBUG -- : TCPSRV: Services running. Press ^C to stop
D, [2023-04-26T11:01:39.856122 #49932] DEBUG -- : TCPSRV: Will stop the server in 10 seconds if no connection is made.
D, [2023-04-26T11:01:39.857739 #49932] DEBUG -- : TCPSRV: Will stop the server when client disconnects
LANGUAGE SERVER RUNNING localhost:35533
D, [2023-04-26T11:01:39.856053 #49932] DEBUG -- : TCPSRV: Started listening on localhost:35533.
D, [2023-04-26T11:01:49.869290 #49932] DEBUG -- : TCPSRV: No connection has been received in 10 seconds.  Shutting down server.
D, [2023-04-26T11:01:49.869540 #49932] DEBUG -- : TCPSRV: Stopping services
D, [2023-04-26T11:01:49.869592 #49932] DEBUG -- : TCPSRV: Stopped listening on localhost:35533
D, [2023-04-26T11:01:49.869633 #49932] DEBUG -- : TCPSRV: Started shutdown process. Press ^C to force quit.
D, [2023-04-26T11:01:49.869680 #49932] DEBUG -- : TCPSRV: Stopping services
D, [2023-04-26T11:01:49.869727 #49932] DEBUG -- : TCPSRV: Waiting for workers to cycle down
I, [2023-04-26T11:01:49.891129 #49932]  INFO -- : Language Server exited.
```

**Comment by williamboman** [comment]
Hey! This is not the place to get support with individual servers. The Puppet language server seems to depend on puppet, make sure you have that installed. You also shouldn't manually modify contents in the Mason installation directory as that will have undefined behaviour (if you want to install the puppet LSP manually place it elsewhere)

**Comment by techsk8** [comment]
Hey @williamboman! 

> This is not the place to get support with individual servers.
Well, the puppet LSP is being installed by Mason after all, right? And this is the section for Mason issues 😄 
Where should I put the Mason related issue otherwise? Especially now that I found that the version installed by Mason is not working correctly, but the original LSP is working nicely!

> The Puppet language server seems to depend on puppet, make sure you have that installed.
That is not correct from what I see.
From what I just posted above you can see that the puppet LSP only depends on having the correct ruby version installed which neeeds to be above ruby-3.1.0

**Comment by williamboman** [comment]
So the issue with `"/usr/bin/env: ‘ruby’: No such file or directory\n"` should be fixed in their latest release, at least (see https://github.com/puppetlabs/puppet-editor-services/issues/318).

Currently, Mason will use whatever `ruby` and `gem` version that is activated in your PATH when installing a gem package. The same applies when executing the associated executables.

I was under the impression that the executables they provide patch the gem load path so that the vendored gems are included - maybe `bundle exec` is still a requirement?

**Comment by techsk8** [comment]
It seems that yes, that is still a requirement as I could see [here](https://github.com/puppetlabs/puppet-editor-services#setting-up-editor-services-for-development):
```console
git clone https://github.com/puppetlabs/puppet-editor-services.git

cd puppet-editor-services

bundle install

bundle exec rake gem_revendor
```

I'm not an expert by any means. Just tried many times different things and I've seen what works and what doesn't.

**Comment by techsk8** [comment]
And more, I have to have at least ruby 3.1.0 running at the moment I'm installing and running the LSP. Otherwise it fails like this
```
Error while loading a critical gem: cannot load such file -- puppet ["<internal:/root/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'", "<internal:/root/.rbenv/versions/3.1.0/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'", "/root/.local/share/lvim/mason/packages/puppet-editor-services/lib/puppet_languageserver.rb:74:in `require_gems'", "/root/.local/share/lvim/mason/packages/puppet-editor-services/lib/puppet_languageserver.rb:215:in `init_puppet'", "./puppet-languageserver:14:in `<main>'"]
```

**Comment by williamboman** [comment]
> It seems that yes, that is still a requirement as I could see [here](https://github.com/puppetlabs/puppet-editor-services#setting-up-editor-services-for-development):

You seem to be running the server in development mode. For "production" they recommend running it via the Puppet agent. I again don't believe there's an issue with Mason, but rather with how the LSP is started. The VSCode extension takes care of identifying the Puppet environment, there's no corresponding "plugin" for Neovim afaik (the closest would be the default config provided by nvim-lspconfig).
