### ISSUE TITLE
Lsp clients dont attach if I lazyload nvim-lspconfig 

### ISSUE THREAD

**Issue by siduck** [williamboman/mason.nvim#126]
### Problem description

If I lazyload `nvim-lspconfig` then the clients dont attach to buffer, but they work when I dont lazyload nvim-lspconfig 

Check the video : 

https://user-images.githubusercontent.com/59060246/180675213-6c156a19-9cd7-4b8d-b0a9-80cf4410269f.mp4

 

### Neovim version (>= 0.7)

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by void-buildslave@a-fsn-de

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Operating system/version

Linux sid 5.18.9_1 #1 SMP PREEMPT_DYNAMIC Sat Jul 2 15:17:21 UTC 2022 x86_64 GNU/Linux

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Affected packages

all

### Actual behavior

lazyloading `nvim-lspconfig` plugin doesnt attach the lsp clients to the buffer 

### Expected behavior

Clients should attach to the buffer

### Healthcheck output

```shell
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - WARNING: **Go**: not available
  - OK: **cargo**: `cargo 1.62.0 (a748cf5a3 2022-06-08)`
  - WARNING: **luarocks**: not available
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.12.1`
  - OK: **node**: `v18.5.0`
  - OK: **python3**: `Python 3.10.5`
  - OK: **pip3**: `pip 22.1.2 from /usr/lib/python3.10/site-packages/pip (python 3.10)`
  - WARNING: **javac**: not available
  - WARNING: **java**: not available
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: **curl**: `curl 7.83.1 (x86_64-unknown-linux-gnu) libcurl/7.83.1 OpenSSL/1.1.1q zlib/1.2.12 zstd/1.5.2 libssh2/1.10.0 nghttp2/1.48.0`
  - OK: **gzip**: `gzip 1.12`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-unknown-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 1. Remaining: 59. Limit: 60. Reset: Mon 25 Jul 2022 01:47:59 AM UTC.
```

**Comment by Johnsiras** [comment]
Hello! :D, i got the same problem here too and can't fix it lazy loaded or not doesn't attach on the buffer

**Comment by siduck** [comment]
> Hello! :D, i got the same problem here too and can't fix it lazy loaded or not doesn't attach on the buffer

yea i saw your astronvim issue xd

**Comment by siduck** [comment]
@Johnsiras do `:LspRestart`, that works weirdly

**Comment by Johnsiras** [comment]
> @Johnsiras `:LspStart` or `:LspRestart` works tho

That didn't worked for me, am i still using nvim-lsp-installer? wth???

![image](https://user-images.githubusercontent.com/102006493/180676241-c9aea180-86e8-4a7a-9607-0ebfccc5c7ce.png)

Or is this with the mason-lspconfig?

**Comment by siduck** [comment]
yes its with mason-lspconfig. I just use mason.nvim

**Comment by Johnsiras** [comment]
Well that's so weird i use mason-lspconfig cause astronvim uses lspconfig, but doesn't work tho...

**Comment by Johnsiras** [comment]
@siduck But is lspconfig installed for you?

**Comment by siduck** [comment]
> @siduck But is lspconfig installed for you?

nvim-lspconfig is installed, see the video above

**Comment by siduck** [comment]
Been trying to fix this issue since last night :/.

I will not work until this issue is fixed xD

**Comment by Johnsiras** [comment]
> > @siduck But is lspconfig installed for you?
> 
> nvim-lspconfig is installed, see the video above

Yeah i was blind lol

**Comment by siduck** [comment]
@Johnsiras another weird thing, go into insert mode and the lsp server will start automatically. Does this happen with you too?

**Comment by siduck** [comment]
Ok this is not a mason.nvim issue at all. I was able to reproduce the same issue without mason.nvim. We have issue with our way of lazyloading lspconfig

**Comment by Johnsiras** [comment]
> @Johnsiras another weird thing, go into insert mode and the lsp server will start automatically. Does this happen with you too?

For some reason it doesn't work for me

**Comment by Johnsiras** [comment]
even when doing the `:LspStart`/`:LspRestart`

**Comment by siduck** [comment]
@Johnsiras remove lazyloading of lspconfig and it will work

**Comment by Johnsiras** [comment]
> @Johnsiras remove lazyloading of lspconfig and it will work

Yeah i removed it still doesn't work?

**Comment by Johnsiras** [comment]
![image](https://user-images.githubusercontent.com/102006493/180693077-2a32729e-5eb4-4c42-8cfc-a6c2e636256f.png)

**Comment by siduck** [comment]
weird, ig thats an astronvim issue. This happens when you switch from NvChad XD!!

**Comment by Johnsiras** [comment]
> weird, ig thats an astronvim issue. This happens when you switch from NvChad XD!!

Lol

**Comment by Johnsiras** [comment]
> weird, ig thats an astronvim issue. This happens when you switch from NvChad XD!!

Well then i'll switch to nvchad even tho astronvim is still awesome

**Comment by williamboman** [comment]
Hello! lspconfig uses the `FileType` autocmd to attach to new buffers (or `BufReadPost` I think if starting in single file mode). If you lazy load lspconfig to load after `FileType`, you'll have to manually dispatch it, some options are:

- `:e`
- `:do FileType`

**Comment by siduck** [comment]
> Hello! lspconfig uses the `FileType` autocmd to attach to new buffers (or `BufReadPost` I think if starting in single file mode). If you lazy load lspconfig to load after `FileType`, you'll have to manually dispatch it, some options are:
> 
> * `:e`
> * `:do FileType`

yea that was it, i added ```e %``` which worked

**Comment by williamboman** [comment]
Also see https://github.com/neovim/neovim/pull/18631 as an alternative to using lspconfig. You'll have to provide all server configs yourself, but it completely removed the need of lspconfig and you can "lazily" start the server in a `ftplugin`/`FileType` autocmd (more details in the link)

**Comment by siduck** [comment]
> Also see [neovim/neovim#18631](https://github.com/neovim/neovim/pull/18631) as an alternative to using lspconfig. You'll have to provide all server configs yourself, but it completely removes the need of lspconfig and you can "lazily" start the server in a `ftplugin`/`FileType` autocmd (more details in the link)

ah np thats too much xD, btw can we are these even clickable or can we cycle through a mapping within these 

![image](https://user-images.githubusercontent.com/59060246/180716498-8a271bd1-9e8d-4ea2-8542-190e41ca5d1d.png)

**Comment by williamboman** [comment]
Not clickable but you can switch view by pressing its number
