### ISSUE TITLE
Problems with installing omnisharp-mono

### ISSUE THREAD

**Issue by fum1h1ro** [williamboman/mason.nvim#1280]
### I've searched open issues for similar requests

- [X] Yes

### I've manually reviewed logs to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

When installing omnisharp-mono, the startup script is not generated correctly.

When various servers are installed, startup scripts are prepared in `$(HOME)/.local/share/nvim/mason/bin`, but in the case of omnisharp-mono, none are created.

Try to manually generate a symbolic link to `$(HOME)/.local/share/nvim/mason/packages/omnisharp-mono/run`.

At this stage, `LspInfo` shows that the server seems to be running, but `LspLog` shows that `OmniSharp.exe` failed because it could not be started from within run.

Next, modify `$(HOME)/.local/share/nvim/mason/packages/omnisharp-mono/run`.

Specifically, modify line 4 as follows

```
omnisharp_dir=${base_dir}/.. /packages/omnisharp-mono/omnisharp
```

Now the server will start and we can confirm that LSP is working correctly.

### Expected behavior

* Create a symbolic link to `run` in `$(HOME)/.local/share/nvim/mason/bin`.
* Modify `$(HOME)/.local/share/nvim/mason/packages/omnisharp-mono/run` so that it can be started

Alternatively, you may place a script that modifies run instead of a symbolic link.

### Steps to reproduce

1. Install omnisharp-mono(without omnisharp)
2. Open mono-project like Unity project.
3. See LspInfo and LspLog

### Affected packages

All

### Neovim version (>= 0.7)

NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

Darwin mai.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:58 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6020 arm64

### Healthcheck

```Text
==============================================================================
mason: require("mason.health").check()

mason.nvim ~
- OK mason.nvim version v1.0.1
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- OK Registry `github.com/mason-org/mason-registry version: 2023-04-30-delightful-potato` is installed.

mason.nvim [Core utils] ~
- OK unzip: `UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send`
- WARNING wget: not available
  - ADVICE:
    - spawn: wget failed with exit code - and signal -. wget is not executable
- OK curl: `curl 7.87.0 (x86_64-apple-darwin22.0) libcurl/7.87.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.51.0`
- OK gzip: `Apple gzip 403.100.6`
- OK tar: `bsdtar 3.5.3 - libarchive 3.5.3 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
- OK bash: `GNU bash, version 3.2.57(1)-release (arm64-apple-darwin22)`
- OK sh: `Ok`

mason.nvim [Languages] ~
- WARNING Go: not available
  - ADVICE:
    - spawn: go failed with exit code - and signal -. go is not executable
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer failed with exit code - and signal -. composer is not executable
- WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. php is not executable
- WARNING cargo: not available
  - ADVICE:
    - spawn: cargo failed with exit code - and signal -. cargo is not executable
- WARNING luarocks: not available
  - ADVICE:
    - spawn: luarocks failed with exit code - and signal -. luarocks is not executable
- WARNING javac: not available
  - ADVICE:
    - spawn: javac failed with exit code 1 and signal 0. The operation couldn’t be completed. Unable to locate a Java Runtime.
      Please visit http://www.java.com for information on installing Java.
      
- WARNING java: not available
  - ADVICE:
    - spawn: java failed with exit code 1 and signal 0. The operation couldn’t be completed. Unable to locate a Java Runtime.
      Please visit http://www.java.com for information on installing Java.
      
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- OK node: `v20.0.0`
- OK Ruby: `ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]`
- OK RubyGem: `3.4.10`
- OK npm: `9.6.4`
- OK python3: `Python 3.9.6`
- OK pip3: `pip 21.2.4 from /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/pip (python 3.9)`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 0. Remaining: 5000. Limit: 5000. Reset: Tue May  2 13:01:57 2023.
```

**Comment by williamboman** [comment]
Seems like the bin entry was commented out for some reason, fixed in https://github.com/mason-org/mason-registry/pull/1430.

**Comment by fum1h1ro** [comment]
Thank you!
