### ISSUE TITLE
rust-analyzer on neovim not working on macOS using nvim-lsp and Mason

### ISSUE THREAD

**Issue by TirtharajPramanik** [williamboman/mason.nvim#1289]
### I've searched open issues for similar requests

- [X] Yes

### I've manually reviewed logs to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

I am using NeoVim with NvChad default configs on a M1 mac. Trying to edit a `.rs` file. 

***TLDR;*** Although Installing rust-analyzer with homebrew works just fine. 👍
```
brew install rust-analyzer    

# ~/.config/nvim/lua/custom/configs/lspconfig.lua
local servers=(... "rust_analyzer")

cargo init
# nvim do whatever
``` 
***BUT;*** Installing `rust-analyzer` with `Mason` does not! Neovim lsp shows snippets but no error or autocompletion.

### What I did

I have installed `rust-analyzer` with Mason and configured
```
# ~/.config/nvim/lua/custom/configs/lspconfig.lua
local servers=(... "rust_analyzer")
``` 
That caused Error:
```
[lspconfig] unhandled error: ...ig/lua/lspconfig/server_configurations/rust_analyzer.lua:41: Expected value but found T_END at character 1`
```

The problem was empty string was being passed to `line 41: vim.json.decode` that came from here 👇
```
# ~/.local/share/nvim/lazy/nvim-lspconfig/lua/lspconfig/server_configurations/rust_analyzer.lua
   18   local jobid = vim.fn.jobstart(cmd, {
   19   │ on_stdout = function(_, data, _)
-->20   │ │ stdout[#stdout + 1] = table.concat(data, '\n')
   21   │ end,
...
-->41   stdout = vim.json.decode(table.concat(stdout, ''))
   42   return stdout and stdout['workspace_root'] or nil
```
Creating a `Cargo.toml` solved the problem.

But **`Client 1 quit with exit code 1 and signal 0`** was the new error. It means for some reason the `rust-analyzer` crashed! The log
```
# ~/.local/state/nvim/lsp.log
[ERROR][2023-05-07 21:37:38] .../vim/lsp/rpc.lua:734    "rpc"   "rust-analyzer" "stderr"        "error: 'rust-analyzer' is not installed for the toolchain 'stable-aarch64-apple-darwin'"
```
I have installed it though with `Mason` , but does not work. Not even with `:!rust-analyzer` command. Error msg same as the log.

`:!which rust-analyzer` command outputs `~/.cargo/bin/rust-analyzer` should be `~/.local/share/nvim/mason/bin/rust-analyzer`. So the package installed with `Mason` is not recognised as it is later it the PATH. (see [this issue](https://github.com/williamboman/mason.nvim/issues/1289#issuecomment-1544448868))

### Affected packages

rust-analyzer Mason

### Neovim version (>= 0.7)

NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

**rust-analyzer version**: 2023-05-01 (nightly or older versions does not work either)
**rustc version**: 1.69.0 (84c898d65 2023-04-16)

### Operating system/version

macOS Ventura M1

### Conclusion

- Mason installs the correct packages of rust-analyzer for 'stable-aarch64-apple-darwin' toolchain.
- If rustup version of rust-analyzer exists in ~/.cargo/bin/rust-analyzer it will be used. Uninstall that package and everything works fine!

- `rust-analyzer` does not work if `Cargo.toml` is not at **project root**. (according to developers this is expected. see [this reply](https://github.com/rust-lang/rust-analyzer/issues/14759#issuecomment-1539720043))

**Comment by williamboman** [comment]
Hello! Are you running a fork of nvim-lspconfig? The snippet you posted doesn't correspond with what's in the default server config for `rust_analyzer` in nvim-lspconfig.

The error message suggests you're running a binary provided by rustup, not Mason, can you verify this by for example doing `:!which rust-analyzer`?

**Comment by ethangumin** [comment]
I'm running into the same issue. when I run `:!which rust-analyzer` my output is `/Users/goom/.local/share/nvim/mason/bin/rust-analyzer`

**Comment by williamboman** [comment]
@ethangumin Would you mind creating a new issue with more details? It would also be helpful if you provide information how you start/setup the server (presumably you do this via nvim-lspconfig or directly via `vim.lsp.start()`), along with LSP configured to log INFO logs (default is `WARN`, set `vim.lsp.set_log_level(vim.log.levels.INFO)` and then check the `:LspLog`).

**Comment by TirtharajPramanik** [comment]
> The error message suggests you're running a binary provided by rustup, not Mason, can you verify this by for example doing `:!which rust-analyzer`?

my previous setup showed `~/.cargo/bin/rust-analyzer`
after removing that binary I'm using `~/.local/share/nvim/mason/bin/rust-analyzer`
works fine. thanks for your work. ☺️

**Comment by TirtharajPramanik** [comment]
btw, how can i get mason to load before others?

**Comment by TirtharajPramanik** [comment]
I should mention
- Mason installs the correct packages of rust-analyzer for 'stable-aarch64-apple-darwin' toolchain.
- If rustup version of rust-analyzer exists in ~/.cargo/bin/rust-analyzer it will be used. Uninstall that package and everything works fine! 

also see [this reply](https://github.com/rust-lang/rust-analyzer/issues/14759#issuecomment-1539720043)

**Comment by tirzasrwn** [comment]
> > The error message suggests you're running a binary provided by rustup, not Mason, can you verify this by for example doing `:!which rust-analyzer`?
> 
> my previous setup showed `~/.cargo/bin/rust-analyzer` after removing that binary I'm using `~/.local/share/nvim/mason/bin/rust-analyzer` works fine. thanks for your work. relaxed

Thanks, after removing ~/.cargo/bin/rust-analyzer, work fine for me too.

**Comment by williamboman** [comment]
If it ended up using that binary over Mason's, it's probably a sign you're setting up servers before setting up Mason, btw. Generally you want to set up Mason first.On 12 May 2023, at 21:28, Tirza ***@***.***> wrote:﻿


The error message suggests you're running a binary provided by rustup, not Mason, can you verify this by for example doing :!which rust-analyzer?

my previous setup showed ~/.cargo/bin/rust-analyzer after removing that binary I'm using ~/.local/share/nvim/mason/bin/rust-analyzer works fine. thanks for your work. relaxed

Thanks, after removing ~/.cargo/bin/rust-analyzer, work fine for me too.

**Comment by IzioDev** [comment]
I ran into a similar issue, on a Ubuntu.

```
:!which rust-analyzer
/home/izio/.cargo/bin/rust-analyzer
```

We can see that is uses the shipped binary by `rustup`.
After removing this binary, it worked.

Is that what is expected? What if I want to execute `rust-analyzer` locally without opening it in `nvim`, would I have to put the binary at another location that's not within my `PATH`, or shall I rename it?

**Comment by TirtharajPramanik** [comment]
> Do you know a way to specify a preferred directory or binary to nvim?

Found the Solution:

```lua
--   ~/.config/nvim/lua/core/init.lua
     59 -- add binaries installed by mason.nvim to path
...
---> 61 vim.env.PATH = vim.env.PATH .. (is_windows and "; " or ":") .. vim.fn.stdpath "data" .. "/mason/bin"
+++> 61 vim.env.PATH = vim.fn.stdpath "data" .. "/mason/bin" .. (is_windows and "; " or ":") .. vim.env.PATH
```

In your **~/.config/nvim/lua/core/init.lua** file replace **line:61** with `vim.env.PATH = vim.fn.stdpath "data" .. "/mason/bin" .. (is_windows and "; " or ":") .. vim.env.PATH`. This will add **~/.local/share/nvim/mason/bin/** at the beginning of your PATH.

**Maintainers** Do you think this should be **Default Behaviour**?

**Comment by williamboman** [comment]
> Do you know a way to specify a **preferred directory or binary** to nvim?

By default, Mason will prepend the `PATH` environment with Mason's bin directory when you call `require("mason").setup()`. This effectively gives executables provided by Mason precedence in all Neovim interfaces involved with spawning processes (`jobstart()`, `vim.loop.spawn()`, etc.). The canonical name of an executable, for example `rust-analyzer`, is not a complete reference to a program. The convention is to leverage the `PATH` environment to provide the program responsible for spawning processes with a set of directories on your system where it should look for `rust-analyzer` - the same mechanism applied by interactive shells such as bash.

If you want to use a specific installation of rust-analyzer you could provide the full path to it, for example `vim.fn.expand("$MASON/bin/rust-analyzer")`. If Neovim ends up using `~/.cargo/bin/rust-analyzer` you either:

1) set up Mason too late
2) you've changed the default PATH setting to `append` or `skip`
3) don't have rust-analyzer installed through Mason

**Comment by TirtharajPramanik** [comment]
Putting `~/.local/share/nvim/mason/bin/` in the beginning of `vim.env.PATH`

```lua
--  ~/.config/nvim/lua/core/init.lua
    59 -- add binaries installed by mason.nvim to path
│-->61 vim.env.PATH = vim.env.PATH .. (is_windows and ";" or ":") .. vim.fn.stdpath "data" .. "/mason/bin"
│++>61 vim.env.PATH = vim.fn.stdpath "data" .. "/mason/bin" .. (is_windows and ";" or ":") .. vim.env.PATH
```

**Comment by stevenewald** [comment]
Had the same issue, fixed by installing through Mason and uninstalling ~/.cargo/rust-analyzer

**Comment by TirtharajPramanik** [comment]
[Fix](https://github.com/NvChad/NvChad/pull/2031) have been successfully merged 👍

**Comment by andr1337228** [comment]
On Windows i had 2 wust alalyzers, 1 in .cargo directory and second in AppData/Local/nvim-data/mason/packages. Reinstalling the rust-analyzer in AppData directory helped for me

**Comment by KnightChaser** [comment]
> > The error message suggests you're running a binary provided by rustup, not Mason, can you verify this by for example doing `:!which rust-analyzer`?
> 
> my previous setup showed `~/.cargo/bin/rust-analyzer` after removing that binary I'm using `~/.local/share/nvim/mason/bin/rust-analyzer` works fine. thanks for your work. ☺️

Thanks, it also helped my case, even though I was not using macOS, but Debian.
