### ISSUE TITLE
Add ensure_installed option

### ISSUE THREAD

**Issue by siduck** [williamboman/mason.nvim#130]
### Is your feature request related to a problem? Please describe.

installing multiple binaries of lspservers/formatters etc will be kinda tiresome if we do it manually ( by clicking their names in the Mason floating window)

It would be nicer to have `ensure_installed` option in the config so we can write all the needed package names. 

### Describe the solution you'd like

```
ensure_installed = { "stylua, "pyright" "efm" , "deno"  }
```

and a command should be added : `MasonInstallAll`

So running that command will install all the servers from the `ensure_installed` option 

@williamboman any plans on adding this option? :thinking:

**Comment by thanhvule0310** [comment]
Maybe [this](https://github.com/williamboman/mason.nvim/wiki/Extensions) is what you need. 
But I think it would be better to add this feature directly to the project.

**Comment by siduck** [comment]
> Maybe [this](https://github.com/williamboman/mason.nvim/wiki/Extensions) is what you need. But I think it would be better to add this feature directly to the project.

yea its better to have this feature in this project itself

**Comment by shaeinst** [comment]
```
:MasonInstall stylua pyright efm deno
```
Mason supports multiple installation.

**Comment by siduck** [comment]
> ```
> :MasonInstall stylua pyright efm deno
> ```
> 
> Mason supports multiple installation.

seems good but an option in the config would be nice too, so we dont have to type all of the packages manually. It might get hard when the user has like 50+ packages!! :exploding_head:

**Comment by siduck** [comment]
also @williamboman go and rust is needed to install shfmt,stylua, is this normal?  I thought this plugin was fetching the binaries from the releases

**Comment by shaeinst** [comment]
@siduck 
>seems good but an option in the config would be nice too, so we dont have to type all of the packages manually. It might get hard when the user has like 50+ packages!! exploding_head

i think autocmd would be good choice for such task.
like:
1. get all installed packages 
2. if package isn't in the installed list then install it.

**Comment by siduck** [comment]
seems good, closing this. Thx! @shaeinst

**Comment by siduck** [comment]
@xsteadfastx 

```lua
local present, mason = pcall(require, "mason")

if not present then
  return
end

local options = {
  ensure_installed = { "lua-language-server" }, -- not an option from mason.nvim
  max_concurrent_installers = 10,
}

mason.setup(options)

vim.api.nvim_create_user_command("MasonInstallAll", function()
  vim.cmd("MasonInstall " .. table.concat(options.ensure_installed, " "))
end, {})
```

**Comment by xdevfaheem** [comment]
very sublte improvement, never mind if it's silly.
 
define this to **only** install the packages which were not installed already. since MasonInstall would use pkg:install async function for both single/multi args, installation speed would be same compared to MasonInstall with multi pkg

```lua
vim.api.nvim_create_user_command("MasonInstallAll", function()
	for _, pkg_name in ipairs(pkgs_to_be_installed) do
		local pkg = registry.get_package(pkg_name)
		if not pkg:is_installed() then
			vim.cmd("MasonInstall " .. pkg_name)
		end
	end
end, {})
```
