### ISSUE TITLE
need a way to configure mason to download registries from mirror site

### ISSUE THREAD

**Issue by gongfarmer** [williamboman/mason.nvim#1300]
### Discussed in https://github.com/williamboman/mason.nvim/discussions/1295

<div type='discussions-op-text'>

<sup>Originally posted by **gongfarmer** May 11, 2023</sup>
I am using neovim on a corporate intranet without general internet access.
There is a mirror site which provides access to GitHub projects and releases.

My problem is that Mason cannot download it's registry.
I am configuring mason to download assets from my corporate mirror like this:
```lua
require('mason').setup({
  log_level = vim.log.levels.DEBUG,
  providers = {
    -- omitting registry-api provider, because it connects to https://api.mason-registry.dev/api/github/mason-org/mason-registry/releases/latest
    "mason.providers.client",
  },
  github = {
    download_url_template = 'https://proxy.corporate.com/generic-github-releases/%s/releases/download/%s/%s',
  }
})
```

When I run `:Mason`,  I get this message:
```
Uninstalled registries
Packages from the following registries are unavailable. Press C to install.
 - github.com/mason-org/mason-registry [uninstalled]
 - github.com/mason-org/mason-registry [uninstalled]
 - github.com/mason-org/mason-registry [uninstalled]

Registry installation failed with the following error:
  GitHubRegistrySource(repo=mason-org/mason-registry) failed to install: Failed to fetch latest registry version from GitHub API.
```

The mason.log file shows this:
```
[DEBUG Thu 11 May 2023 12:02:41 PM EDT] ...al/share/nvim/lazy/mason.nvim/lua/mason-core/process.lua:116: Spawning cmd="wget", spawn_opts={
  args = { "--header=Accept: application/vnd.github.v3+json; q=1.0, application/json; q=0.8", "--header=User-Agent: mason.nvim (+https://github.com/williamboman/mason.nvim)", "-nv", "-o", "/dev/null", "-O", "-", "--method=GET", "https://api.github.com/repos/mason-org/mason-registry/releases/latest" }
}
[DEBUG Thu 11 May 2023 12:02:41 PM EDT] ...al/share/nvim/lazy/mason.nvim/lua/mason-core/process.lua:162: Spawned with pid 1280754
[DEBUG Thu 11 May 2023 12:02:41 PM EDT] ...al/share/nvim/lazy/mason.nvim/lua/mason-core/process.lua:148: Job pid=1280754 exited with exit_code=4, signal=0
[ERROR Thu 11 May 2023 12:02:41 PM EDT] ...e/nvim/lazy/mason.nvim/lua/mason-core/providers/init.lua:75: Provider "github" "get_latest_release" failed: spawn: wget failed with exit code 4 and signal 0.
[ERROR Thu 11 May 2023 12:02:41 PM EDT] ...e/nvim/lazy/mason.nvim/lua/mason-core/providers/init.lua:86: No provider implementation succeeded for github.get_latest_release
[ERROR Thu 11 May 2023 12:02:41 PM EDT] ...im/lazy/mason.nvim/lua/mason-registry/sources/github.lua:181: Failed to install registry GitHubRegistrySource(repo=mason-org/mason-registry). "Failed to fetch latest registry version from GitHub API."
```

The solution is probably that I need to configure the registries during `setup()`, something like this:
```lua
  registries =  {
      "https://proxy.corporate.com/generic-github-releases/mason-org/mason-registry/releases/",
  },
```

However I can't get Mason to accept a specific URL for the registry.
If I prepend 'github:' to the url above, then Mason adds a GitHub url onto the front before downloading.
Prepending 'lua:' doesn't help either.  
These are the only prefixes allowed by `lua/mason-registry/sources/init.lua`, anything else causes a 'Malformed registry id' error.

How can I configure Mason to download registries from a mirror site?</div>

**Comment by gongfarmer** [comment]
Regardless of whether the registry provider type is 'github' or 'lua', every registry update goes through `lua/mason-registry/api.lua' which uses `local BASE_URL = "https://api.mason-registry.dev"` as the basis for every request.  So currently there is no way to configure the registries to download from a mirror site.

Probably the simplest solution would be to make BASE_URL configurable in mason `setup()`.
This way the default registry configuration line `"github:mason-org/mason-registry",` would be able to work as long as a mirror of 'mason-org/mason-registry' is provided as the BASE_URL.

Another option would be to add a new registry provider type with a name like `url`,  and have `lua/mason-registry/api.lua` not prepend anything to the front of this URL.

**Comment by williamboman** [comment]
Hello! When the registry is downloaded, the latest available version needs to be resolved first. It seems like you're struggling with this step (with `mason.providers.client` it will try to talk to `api.github.com` directly). What you could do is try setting  the`http_proxy` and `https_proxy` environment variables and ensuring that either `curl` or `gh` is installed.

Another workaround would be to pin the registry version to a specific version, effectively bypassing the version lookup step:

```lua
require("mason").setup {
  registries = {
    "github:mason-org/mason-registry@2023-05-15-next-towel"
  }
}
```

**Comment by gongfarmer** [comment]
I tried configuring pinning the registry version as you suggested but this didn't work for me.  With the exact configuration you suggested above, I got these log messages:
```
[DEBUG Thu 18 May 2023 07:34:46 PM EDT] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:48: Failed to scan installation root dir .../.local/share/nvim/lazy/mason.nvim/lua/mason-core/fs.lua:128: ENOENT: no such file or directory: /usr/local/ldr/.local/share/nvim/mason/packages
[DEBUG Thu 18 May 2023 07:34:46 PM EDT] ...ocal/share/nvim/lazy/mason.nvim/lua/mason-core/fetch.lua:34: Fetching URL "https://api.mason-registry.dev/api/github/mason-org/mason-registry/releases/latest"
[DEBUG Thu 18 May 2023 07:34:46 PM EDT] ...al/share/nvim/lazy/mason.nvim/lua/mason-core/process.lua:116: Spawning cmd="curl", spawn_opts={
  args = { "-H", "Accept: application/vnd.mason-registry.v1+json; q=1.0, application/json; q=0.8", "-H", "User-Agent: mason.nvim (+https://github.com/williamboman/mason.nvim)", "-fsSL", "-X", "GET", "https://api.mason-registry.dev/api/github/mason-org/mason-registry/releases/latest" }
}
[DEBUG Thu 18 May 2023 07:34:46 PM EDT] ...al/share/nvim/lazy/mason.nvim/lua/mason-core/process.lua:162: Spawned with pid 32272
```

 I haven't tried setting the `http_proxy` environment variable for curl yet.  I am hesitant to set that in my command shells as I already use curl for other tasks that do not involve the proxy, and don't want it rewriting my requests.

**Comment by gongfarmer** [comment]
During the registry download step the following requests are logged:
  [DEBUG Thu 18 May 09:41:11 2023] ...ocal/share/nvim/lazy/mason.nvim/lua/mason-core/fetch.lua:34: Fetching URL "https://api.mason-registry.dev/api/github/mason-org/mason-registry/releases/latest"
  [DEBUG Thu 18 May 09:41:12 2023] ...ocal/share/nvim/lazy/mason.nvim/lua/mason-core/fetch.lua:34: Fetching URL "https://github.com/mason-org/mason-registry/releases/download/2023-05-18-early-desire/registry.json.zip"
  [DEBUG Thu 18 May 09:41:12 2023] ...ocal/share/nvim/lazy/mason.nvim/lua/mason-core/fetch.lua:34: Fetching URL "https://github.com/mason-org/mason-registry/releases/download/2023-05-18-early-desire/checksums.txt"

The first request retrieves a few lines of JSON containing the urls from which to download registry.json.zip and checksums.txt.
The second and third requests download those assets.

None of this works at a firewalled secure site. 
We can't make a web request to https://api.mason-registry.dev, and even if we made an exception and allowed that, we can't access the https://github.com/ urls that it returns within the json.

It is possible to fetch the latest `registry.json.zip` and `checksums.txt` files without first requesting their URLs from api.mason-registry.dev, and without knowing the release name.
GitHub project releases provide the 'latest' url which always points to the latest release.
I can make web requests like this to fetch the latest assets:

```
$ wget https://proxy.corporate.com/generic-github-releases/mason-org/mason-registry/releases/latest/download/registry.json.zip
 
--2023-05-18 15:43:01--  https://proxy.corporate.com/generic-github-releases/mason-org/mason-registry/releases/latest/download/registry.json.zip
Resolving proxy.corporate.com (proxy.corporate.com)... 10.251.21.117
Connecting to proxy.corporate.com (proxy.corporate.com)|10.251.21.117|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 35797 (35K) [application/zip]
Saving to: ‘registry.json.zip’
 
registry.json.zip                      100%[============================================================================>]  34.96K  --.-KB/s    in 0.001s
 
2023-05-18 15:43:01 (67.1 MB/s) - ‘registry.json.zip’ saved [35797/35797]
```

Would this be a suitable basis for a solution?

I am picturing a third mason registry source type which can be configured to download the registry from a URL, without prepending the BASE_URL as is currently done in `lua/mason-registry/api.lua` for both the `github` and `lua` registry source types.

So, I would configure it like this:
```
    registries = {
        "url: https://proxy.corporate.com/generic-github-releases/mason-org/mason-registry/releases/",
        "github:mason-org/mason-registry",
    },
```

When it is time to download registries, it would make 2 requests based on this configured url:
 https://proxy.corporate.com/generic-github-releases/mason-org/mason-registry/releases/latest/download/registry.json.zip
 https://proxy.corporate.com/generic-github-releases/mason-org/mason-registry/releases/latest/download/checksums.txt
 
This is as minimal a solution as I can think of to let Mason work for people stuck behind a firewall.

**Comment by williamboman** [comment]
Are you sure you've provided the settings correctly? The error output you provided in your first message suggests the registry is being registered thrice (i.e. 3 identical entries to the `registries` setting). There should also not be any interactions with api.mason-registry.dev if you're using the `mason.providers.client` provider.

**Comment by gongfarmer** [comment]
I re-did this to check and it does seem to work now.

Here's my configuration for mason:
```
require('mason').setup({
  log_level = vim.log.levels.DEBUG,
  registries = {    "github:mason-org/mason-registry@2023-05-15-next-towel" },
  providers = { "mason.providers.client", },
  github = {
    download_url_template = 'https://proxy.corporate.com/generic-github-releases/%s/releases/download/%s/%s',
  }
})
```

Actually when I retried it with this configuration, it failed the same as before.  
Because of your comment that the registry is being registered thrice, I reviewed my neovim config and found that Mason `setup()` was being called in 3 separate places, only one of which was receiving my custom configuration.

I didn't think that would matter since 2 of those calls to setup() were given no arguments.
However after eliminating those calls, it started working.

This solves my immediate problem of being able to bootstrap into a working neovim with Mason, starting from just `~/.config/nvim`.

Thank you!

Using this version-pinned configuration for the registry, will it be able to discover newer versions of the assets to install?

**Comment by williamboman** [comment]
> I didn't think that would matter since 2 of those calls to setup() were given no arguments. However after eliminating those calls, it started working.

Yeah it should actually be fine in terms of applying the settings correctly, but calling setup more than once does carry somewhat undefined behavior.

> Using this version-pinned configuration for the registry, will it be able to discover newer versions of the assets to install?

No. Pinning the registry version essentially freezes all packages to the latest version at the time. If you host your config somewhere online you could leverage something like Renovate to automate upgrading the pinned version, although this might be a bit tricky because it must be able to parse an arbitrary Lua file where you set up Mason.

**Comment by gongfarmer** [comment]
I found a way around this limitation, so that I can keep up-to-date with the latest registry without having to update the pinned version.

```lua
require('mason').setup({
  providers = { "mason.providers.client" },
  registries = { "github:mason-org/mason-registry@latest" },
  github = {
    download_url_template = "https://proxy.corporate.com/generic-github-releases/%s/releases/%s/download/%s",
  }
})
```
On startup:
*  client provider is used to bypass the check to https://api.mason-registry.dev
* version pin to "latest" means that the registry version check in GitHubRegistrySource:install() always fails so it always downloads the latest registry
* url template changes both the root URL and also the order in which "releases" and "download" are inserted into the URL.

Combining the version string "latest" with the changed download_url_template makes it download from the "latest release" url, which is kept up-to-date by our internal mirror.

Thank you so much for all the help!

**Comment by williamboman** [comment]
Ah, interesting. The download_url_template needs to be compatible with the "regular release" URL format in order to access release assets, but it sounds like you made it work somehow?

**Comment by gongfarmer** [comment]
I was mistaken.  My solution is broken for exactly the reason you pointed out. 

With my solution, Mason is able to download the latest registry from the mirror, but it fails to install assets that come from GitHub releases.

I fooled myself into thinking I had solved it because the packages that I had Mason install during my test were not coming from GitHub.  They were ruby gems, which do not come from GitHub releases. This week as I use my solution more, I find that several packages cannot install.

Back to the drawing board.  I'm back to believing that it will take a code change to resolve this.

**Comment by glyh** [comment]
Is it possible for mason to respect

**Comment by pka420** [comment]
> 
Had the same issue when running nvim in a container. (Because I cannot install software on a shared server :)  

Turns out, this command was throwing error, because tls certificates were missing inside the container. 
```bash
curl https://api.mason-registry.dev/
```

copying the certs fixed it.

**Comment by TheCreatorAMA** [comment]
> Hello! When the registry is downloaded, the latest available version needs to be resolved first. It seems like you're struggling with this step (with `mason.providers.client` it will try to talk to `api.github.com` directly). What you could do is try setting the`http_proxy` and `https_proxy` environment variables and ensuring that either `curl` or `gh` is installed.
> 
> Another workaround would be to pin the registry version to a specific version, effectively bypassing the version lookup step:
> 
> ```lua
> require("mason").setup {
>   registries = {
>     "github:mason-org/mason-registry@2023-05-15-next-towel"
>   }
> }
> ```

For others who may run into this issue when working from withing a corporate proxy etc. (not trying to reopen this) this solution helped me. Just specify a specific registry version and make sure your proxy settings are set up correctly.

**Comment by devd79** [comment]
Setting http_proxy and https_proxy resolved for me. THANKS!

**Comment by Holmes7** [comment]
I solved this by downloading `https://curl.se/ca/cacert.pem` and running `export SSL_CERT_FILE=~/Downloads/cacert.pem`
