### ISSUE TITLE
Provide an option to toggle the notification of installation status of mason-installed tools (LSPs, linters, formatters, debuggers etc)

### ISSUE THREAD

**Issue by krishnakumarg1984** [williamboman/mason.nvim#1309]
### I've searched open issues for similar requests

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

It would be helpful to have an option key along the lines of `notifications_enabled = false`  to enable or disable the notifications regarding the installation status of mason-installed tools (LSPs, debuggers, linters, formatters etc).

For a fresh install of neovim with a fully kitted out list of such tools, the notifications overwhelm the UI, and basically requires the user to interact with keystrokes etc to dismiss them. The installation status can anyway be viewed by invoking the mason dashboard, and hence, it does not diminish the ability to view such information in the absence of notifications. 

For a better user experience, there ought to be a way for users to opt out of these notifications. See the attached screenshot below for a description of the problem.

### Expected behavior

When the configuration key is set to `notifications_enabled = false`, no notifications are visiable. The installation status of various tools can be checked by pulling up the Mason dashboard.

### Affected packages

All

### Mason output

```Text
Please see screenshot
```

### Installation log

```Text
N/A
```

### Neovim version (>= 0.7)

NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

Ubuntu 22.10 x86_64 Kernel 5.19.0-42-generic

### Healthcheck

```Text
mason: require("mason.health").check()

mason.nvim ~
- OK mason.nvim version v1.1.0
- OK PATH: prepend
- OK Providers: 
  mason.providers.registry-api
  mason.providers.client
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- OK Registry `github.com/mason-org/mason-registry version: 2023-05-18-early-desire` is installed.

mason.nvim [Core utils] ~
- OK unzip: `UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.`
- OK wget: `GNU Wget 1.21.4 built on linux-gnu.`
- OK curl: `curl 8.1.0 (x86_64-pc-linux-gnu) libcurl/8.1.0 OpenSSL/1.1.1t zlib/1.2.13 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.4 libssh2/1.10.0 nghttp2/1.53.0 librtmp/2.3`
- OK gzip: `gzip 1.12`
- OK tar: `tar (GNU tar) 1.34`
- OK bash: `GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)`
- OK sh: `Ok`

mason.nvim [Languages] ~
- OK Go: `go version go1.20.4 linux/amd64`
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer failed with exit code - and signal -. composer is not executable
- WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. php is not executable
- OK Ruby: `ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]`
- OK luarocks: `/home/linuxbrew/.linuxbrew/bin/luarocks 3.9.2`
- WARNING javac: not available
  - ADVICE:
    - spawn: javac failed with exit code - and signal -. javac is not executable
- OK node: `v20.1.0`
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- OK cargo: `cargo 1.69.0 (6e9a83356 2023-04-12)`
- OK python3: `Python 3.10.11`
- OK java: `openjdk version "18.0.2-ea" 2022-07-19`
- OK RubyGem: `3.4.10`
- OK npm: `9.6.4`
- OK pip3: `pip 23.1.2 from /home/krishnakumar/miniforge3/lib/python3.10/site-packages/pip (python 3.10)`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 0. Remaining: 5000. Limit: 5000. Reset: Thu May 18 20:09:20 2023.
```

### Screenshots

![image](https://github.com/williamboman/mason.nvim/assets/15239509/f3638f08-de7c-460d-a49c-2926574b122e)
![image](https://github.com/williamboman/mason.nvim/assets/15239509/f9f50adb-a321-4edc-bc1b-09c78655a2af)

**Comment by williamboman** [comment]
Hello! Indicating when a package is automatically installed is pretty important for transparency. I'd be open to customizing messages/notifications if it'd be something that happens regularly. For the most part, Mason only really sits in the background and does very little during normal usage (it basically only enhances `PATH` and sets up some commands).

The automatic installation features of mason-lspconfig and mason-null-ls are very basic and is something you can implement yourself with very few lines to avoid notifications:

```lua
local registry = require "mason-registry"

local packages = {
    "rust-analyzer",
    "lua-language-server",
    "stylua"
}

registry.refresh(function ()
    for _, pkg_name in ipairs(packages) do
        local pkg = registry.get_package(pkg_name)
        if not pkg:is_installed() then
            pkg:install()
        end
    end
end)
```

**Comment by krishnakumarg1984** [comment]
@williamboman 

> Indicating when a package is automatically installed is pretty important for transparency. 

Yes. Fully agree with you. However, if the user intentionally opts out of notifications in their configuration, the question of transparency doesn't arise at all, right?  It is about enabling people to make the choice. The notifications are very spammy for someone who works on multi-language projects.   There is always the Mason dashboard which the user can pull-up to know the complete current status of automatic tool installations.

Per language, there are at least 5-6 tools, and even if you are interested in couple of programming plus one or two scripting languages, and add in language-agnostic general purpose tools like commit linters, spell-checkers, github-actions etc, it is easily 30 tools to install.  I feel that the plugin should empower users to make an informed decision-making on this.  It is fine to leave notifications enabled as default to keep current behaviour., but might be important to respect their choice to opt-out of such notifications with a boolean option.

>you can implement yourself with very few lines to avoid notifications:

Thank you for providing a workaround for this. I think this is less useful for someone on a pre-configured instance of neovim e.g. I am using AstroNvim for all the conveniences and syntax sugars, and the generally very solid base it provides for further customisation. It is harder for such users to disable notifications. If it was just a boolean toggle in Mason, then it is made accessible to users for customisation.

Could you please reconsider inclusion of this `disable_notifications` flag?

**Comment by williamboman** [comment]
I might be missing something here, but isn't this something that happens very rarely? How often do you set up a new system?

**Comment by krishnakumarg1984** [comment]
@williamboman Thank you for asking. I am a HPC engineer in academia, and have to login/SSH into a wide variety of machines across the world. Even for the same machines, the user accounts are different since they are allocated on a project-specific basis and tied to a particular research grant. For example, see the details here on the UK's national supercomputer: https://www.archer2.ac.uk/support-access/access.html. 

Since neovim doesn't currently have a great remote-editing experience (i.e. LSPs running locally, but indexing the remote filesystem and reporting back diagnostics translated relative to that), I just sync my dotfiles across through git, and just setup the same environment everywhere.

To compond matters further, I am the sysadmin for my group, and since other researchers  really liked my neovim setup, they borrowed my config or ask me to set it up for them. It annoys them a lot when they get spammed with the notifications.

Finally, there is another point. For a local development machine running on a Nvme secondary storage, the install times are not too bad, and the notifications go away soon enough.  But the HPC machines I work on always use a networked filesystem , something like Lustre or GPFS for the work drive (or even worse, an NFS for the home drive), which are extremely slow for I/O operations.  Thus, the first install occupies the whole screen and the editor is unusable for nearly an hour or so while all the tools get installed. 

Final point is that, with every new release of neovim (which is approx every 6 months), I wipe my local state `rm -rf ~/.local/share/nvim ~/.local/state/nvim ~/.local/cache/nvim` to get a clean slate to start with. Together all this leads to a difficult first install experience. 

All I am asking is for a notifications_enabled opt-in flag for those who need it. You may leave it as enabled to maintain compatibility with the current user experience.

**Comment by williamboman** [comment]
Ok I see. To me it sounds like a good use case for customization via Mason's Lua API. You might also want to move the default Mason install location to somewhere outside of `~/.local/share/nvim` so that you can keep installed packages between wipes. Anyways there won't be a new setting added for this, I want to avoid settings bloat, and either way these messages don't originate from `mason.nvim` itself.
