### ISSUE TITLE
Mason successfully install all the lsp server, but when writing scripts it still not work

### ISSUE THREAD

**Issue by EdwardWong1994** [williamboman/mason.nvim#1325]
### I've searched open issues for similar requests

- [X] Yes

### I've manually reviewed logs to find potential errors

- [ ] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [ ] Yes

### Problem description

I have changed `mason.nvim` from `nvim-lsp-installer`.  I successfully download all the `lsp` server that i need but when i try to write scripts, it will not work at all.  

![image](https://github.com/williamboman/mason.nvim/assets/96438179/314424eb-aaee-468d-b698-3a66bbe78b0c)

for example, i open a `lua` file, i type `LspInfo` , it gives me `0 clients attached to this buffer`.   And in the bottom of lualine plugin, it shows "No active Lsp"

![image](https://github.com/williamboman/mason.nvim/assets/96438179/c217c9ff-e233-48d4-a964-98563f4730a8)

![image](https://github.com/williamboman/mason.nvim/assets/96438179/c0bd84e7-c508-4e93-a03c-479e37380d62)

### Expected behavior

If it works, it should give me grammar suggestion, give me error information and something

### Steps to reproduce

I have been struggeled for several days about the LSP server not working. I try to sort out my configuration from begining to end.  But i still do not know what is the proble.

Would be anyone to have a check on my configuration file?

[configuration_link]{https://github.com/EdwardWong1994/neovim_configuration.git}

The structure is like this:

![image](https://github.com/williamboman/mason.nvim/assets/96438179/fd58955c-325a-48e1-8770-4d3885912d2a)

### Affected packages

all

### Neovim version (>= 0.7)

![image](https://github.com/williamboman/mason.nvim/assets/96438179/53b02c5c-5a52-4b07-9063-7061be8ad342)

### Operating system/version

Linux Kali 5.18.0-kali5-arm64

### Healthcheck

```Text
It seems most of the conditions are ok, with Go language, javac and julia missing. But i can not download them using `apt-get install`
```

### Screenshots or recordings

![image](https://github.com/williamboman/mason.nvim/assets/96438179/d1e2a2d6-335b-490f-b77e-4f391d5f3f91)

**Comment by williamboman** [comment]
Hey! I'm afraid I can't offer support for personal configs. It seems like packages are successfully installed, which is also where Mason's involvement sort of ends (unless there are problems with the packages themselves).

It seems like you've successfully set up the server but it's not initializing. I'd recommend reviewing the `:LspLog` for potential issues (also see `:h lspconfig-debugging`)
