### ISSUE TITLE
netcoredbg coming with a wrong path on windows 10

### ISSUE THREAD

**Issue by WillEhrendreich** [williamboman/mason.nvim#1335]
### I've searched open issues for similar requests

- [X] Yes

### I've manually reviewed logs to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

i can't find where to change this for the life of me now, otherwise i'd just make a pr, but in the netcoredbg.CMD file it has this line,

`endLocal & goto #_undefined_# 2>NUL || title %COMSPEC% & "C:\.local\share\LazyVim-data\mason\packages\netcoredbg\netcoredbg/netcoredbg.exe" %*
`
which due to path slash issues is not a good thing, it simply brings up a new cmd window that has that bad path in it, and then gets cancelled by neovim with exit code 1. 

The way to get around it is simply having all the "\" changed to "/". so you get this in the end.

`
endLocal & goto #_undefined_# 2>NUL || title %COMSPEC% & "C:/.local/share/nvim-data/mason/packages/netcoredbg/netcoredbg/netcoredbg.exe" %*
`
or by entering that into the command argument in the first place, while setting up dap adapters. 

### Expected behavior

that it would properly be able to start and communicate with the server. it can't, on windows at least, because the path isn't correct. 

### Steps to reproduce

be on windows, install netcoredbg though mason, make sure it points at the cmd, the try to debug something dotnet.

### Affected packages

netcoredbg

### Neovim version (>= 0.7)

10+

### Operating system/version

Windows 10

### Healthcheck

```Text
==============================================================================
mason: require("mason.health").check()

mason.nvim ~
- OK mason.nvim version v1.1.1
- OK PATH: prepend
- OK Providers: 
    mason.providers.registry-api
    mason.providers.client
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- OK Registry `github.com/mason-org/mason-registry version: 2023-06-01-smug-link` is installed.

mason.nvim [Core utils] ~
- WARNING unzip: not available
  - ADVICE:
    - spawn: unzip failed with exit code - and signal -. unzip is not executable
- WARNING wget: not available
  - ADVICE:
    - spawn: wget failed with exit code - and signal -. wget is not executable
- OK curl: `curl 8.1.1 (x86_64-w64-mingw32) libcurl/8.1.1 OpenSSL/3.1.0 (Schannel) zlib/1.2.13 brotli/1.0.9 zstd/1.5.5 WinIDN libssh2/1.10.0 nghttp2/1.53.0 ngtcp2/0.15.0 nghttp3/0.11.0 libgsasl/2.2.0
`
- OK gzip: `gzip 1.3.12
`
- OK tar: `bsdtar 3.5.2 - libarchive 3.5.2 zlib/1.2.5.f-ipp 
`
- OK pwsh: `7.3.4 Microsoft Windows 6.2.9200 Win32NT
`
- OK 7z: `7-Zip 21.07 (x86) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26
`

mason.nvim [Languages] ~
- WARNING Ruby: not available
  - ADVICE:
    - spawn: ruby failed with exit code - and signal -. ruby is not executable
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer.bat failed with exit code - and signal -. composer.bat is not executable
- WARNING RubyGem: not available
  - ADVICE:
    - spawn: gem.cmd failed with exit code - and signal -. gem.cmd is not executable
- WARNING luarocks: unsupported version `luarocks 2.0.2
`
  - ADVICE:
    - Luarocks version must be >= 3.0.0.
- OK PHP: `PHP 8.2.6 (cli) (built: May  9 2023 16:07:30) (NTS Visual C++ 2019 x64)`
- OK Go: `go version go1.20.4 windows/amd64`
- OK node: `v20.2.0
`
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- WARNING python: not available
  - ADVICE:
    - spawn: python failed with exit code - and signal -. python is not executable
- OK java: `openjdk version "11.0.19" 2023-04-18
`
- WARNING pip: not available
  - ADVICE:
    - spawn: python failed with exit code - and signal -. python is not executable
- OK cargo: `cargo 1.68.0 (115f34552 2023-02-26)`
- OK JAVA_HOME: `openjdk version "20.0.1" 2023-04-18
`
- OK javac: `javac 11.0.19
`
- OK npm: `9.6.3`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 0. Remaining: 5000. Limit: 5000. Reset: 6/1/2023 5:17:55 PM.
```

**Comment by williamboman** [comment]
Hey, thanks! Yeah I can reproduce this. I don't think it's a path issue though? I get the same results regardless of which path separator is used. I think it's a combination of different issues, let me investigate a bit further (any help appreciated).

**Comment by williamboman** [comment]
Try setting `detached = false` in the nvim-dap settings, like so:

```lua
dap.adapters.coreclr = {
  type = 'executable',
  command = vim.fn.exepath 'netcoredbg',
  args = {'--interpreter=vscode'},
  options = {
    detached = true
  }
}

```

**Comment by williamboman** [comment]
Are you sure it's being applied? Do you still get a console window?

**Comment by williamboman** [comment]
Hm idk. But to me it sounds like `detached = false` fixed things for you as well, no?

**Comment by WillEhrendreich** [comment]
`detached = false ` seems to fix the separate window popping up, but not the issue that lazyvim based configs don't seem to work unless I point directly to netcoredbg.exe. 

There doesn't seem like there should be much difference between pointing at the cmd and the exe.  

I'm not familiar enough with command prompt to parse out exactly what's happening, but from what I can tell the cmd doesn't really look like it does anything but point at the downloaded location of the exe, isn't that correct? That's the only real thing going on, right? Or is it doing some environment variable setting or evaluating something special that wouldn't be obvious to someone who doesn't understand cmd well?

**Comment by williamboman** [comment]
I'm not sure why lazyvim wouldn't work, but it sounds like that might be unrelated to mason? The gif renders too fast and I can't pause/rewind to see what's going on 😆

**Comment by WillEhrendreich** [comment]
yeah fair enough, lol. sorry about the gif too fast, though. legit thanks so much for your work, it's such a great advantage for Neovim!
