### ISSUE TITLE
DAP binaries on Windows not working

### ISSUE THREAD

**Issue by jay-babu** [williamboman/mason.nvim#1339]
### I've searched open issues for similar requests

- [X] Yes

### I've manually reviewed logs to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

![image](https://github.com/williamboman/mason.nvim/assets/36803168/e0047013-6cb2-4acf-a4b5-a73244fb1f89)

Hello, when using some of the binaries vended via mason on Windows, they fail to execute. This issue is focused on Windows DAPs. Example of the error message is above. The dap config is as follows https://github.com/jay-babu/mason-nvim-dap.nvim/blob/main/lua/mason-nvim-dap/mappings/adapters/python.lua#L1. However when manually specifying the arguments 
![image](https://github.com/williamboman/mason.nvim/assets/36803168/ad94ff07-e47d-4a30-a6f7-e09d4f5d9316), it seems to work fine

### Expected behavior

DAPs to work on windows via binaries

### Steps to reproduce

configure dap on windows as shown. run dap

### Affected packages

All

### Neovim version (>= 0.7)

0.9.1

### Operating system/version

Windows 11

### Healthcheck

```Text
should be fine
```

**Comment by williamboman** [comment]
> However when manually specifying the arguments
image, it seems to work fine

I'm not sure I'm following?

nvim-dap launches processes in detached mode (so they become session leader) for some reason. Disabling this by setting `detached = false` in the configuration of an nvim-dap server should fix the issue on Windows. I'm not entirely sure whether this is a nvim-dap + Windows issue, or a Mason + Windows issue (all linked executables are .cmd wrapper scripts on Windows, might be problematic in some instances)

**Comment by jay-babu** [comment]
`detached = false`, added for a couple of the adapters and it works. `debugpy-adapter` and `node` don't work. I did not see detached = false as an option per their spec.

https://github.com/jay-babu/mason-nvim-dap.nvim/blob/main/lua/mason-nvim-dap/mappings/adapters/python.lua

this fails to work on windows

https://github.com/A-Lamia/AstroNvim-conf/blob/main/plugins/dap.lua#L32-L33. this works though. note `detached` is spelled incorrectly on line 34, so can be ignored

**Comment by williamboman** [comment]
> detached = false, added for a couple of the adapters and it works. debugpy-adapter and node don't work. I did not see detached = false as an option per their spec.

Hm `detached` should be a generic setting that can be applied to all DAP configs. I'm not entirely sure what the issue is, but it's related to spawning detached batch scripts that spawn processes themselves. The stdout/in streams seem to disconnect somewhere along the line.

I can't really reproduce on Windows with detached = false, can you confirm it's still an issue with detached = false applied?

**Comment by williamboman** [comment]
Here's an example configuration that works for me:

https://github.com/williamboman/mason.nvim/assets/6705160/2608a288-abe9-4f38-848d-266fe1cb4c7e
