### ISSUE TITLE
[New package]: vale-ls

### ISSUE THREAD

**Issue by UtkarshVerma** [williamboman/mason.nvim#1383]
### I've searched open & closed issues for similar requests

- [X] Yes

### Package name

vale-ls

### Package homepage

https://github.com/errata-ai/vale-ls

### Languages

markdown, plaintext

### How is this package distributed?

This has been added to `nvim-lspconfig`:
https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#vale_ls

Having this in `mason.nvim` would be a huge help. It does GitHub releases of the compiled binaries.

**Comment by UtkarshVerma** [comment]
Thanks a lot :+1: 

I noticed it isn't mapped in mason-lspconfig yet. Shall I make a PR, or is it underway?

**Comment by williamboman** [comment]
Added in https://github.com/williamboman/mason-lspconfig.nvim/pull/246!
