### ISSUE TITLE
Codelldb exits with error 127

### ISSUE THREAD

**Issue by ozoromo** [williamboman/mason.nvim#1384]
### I've searched open issues for similar requests

- [X] Yes

### I've manually reviewed logs to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

When trying to debug c code using codelldb after selecting the binary to be debugged an error message appears, stating:
`Codelldb exited with code 127`
and then a few seconds later another error when nvim-dap tries to connect to the exited debugger:
`Failed to connect to 127.0.0.1:${PORT}: ERRCONNREFUSED`

### Expected behavior

The program and debugging session should start.

### Steps to reproduce

1. Open mason menu with :Mason
2. Install codelldb in the dap section
3. Set a breakpoint
4. Start debugging and select executable to be debugged
5. Error appears

### Affected packages

codelldb

### Neovim version (>= 0.7)

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

Linux hostname 6.3.9 #1-NixOS SMP PREEMPT_DYNAMIC Wed Jun 21 14:02:19 UTC 2023 x86_64 GNU/Linux

### Healthcheck

```Text
mason: require("mason.health").check()

mason.nvim ~
- OK mason.nvim version v1.5.0
- OK PATH: prepend
- OK Providers: 
  mason.providers.registry-api
  mason.providers.client
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- OK Registry `github.com/mason-org/mason-registry version: 2023-06-29-invisible-sphynx` is installed.

mason.nvim [Core utils] ~
- OK unzip: `UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send`
- WARNING wget: not available
  - ADVICE:
    - spawn: wget failed with exit code - and signal -. wget is not executable
- OK curl: `curl 8.1.1 (x86_64-pc-linux-gnu) libcurl/8.1.1 OpenSSL/3.0.9 zlib/1.2.13 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.4 libssh2/1.11.0 nghttp2/1.51.0`
- OK gzip: `gzip 1.12`
- OK tar: `tar (GNU tar) 1.34`
- OK bash: `GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)`
- OK sh: `Ok`

mason.nvim [Languages] ~
- WARNING Go: not available
  - ADVICE:
    - spawn: go failed with exit code - and signal -. go is not executable
- WARNING luarocks: not available
  - ADVICE:
    - spawn: luarocks failed with exit code - and signal -. luarocks is not executable
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer failed with exit code - and signal -. composer is not executable
- WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. php is not executable
- OK Ruby: `ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [x86_64-linux]`
- OK cargo: `cargo 1.70.0`
- OK node: `v20.3.1`
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- OK python: `Python 3.9.17`
- OK java: `openjdk version "19.0.2" 2023-01-17`
- OK python3_host_prog: `Python 3.10.12`
- OK JAVA_HOME: `openjdk version "19.0.2" 2023-01-17`
- OK RubyGem: `3.4.13`
- WARNING python3_host_prog pip: not available
  - ADVICE:
    - spawn: /nix/store/zhsm2kwkas3gf2iiwh9k284i7n2m88xa-neovim-0.9.1/bin/nvim-python3 failed with exit code 1 and signal 0. /nix/store/b44cj8npybjl6qr2xw0snz5s80vclysx-python3-3.10.12-env/bin/python3.10: No module named pip

- WARNING pip: not available
  - ADVICE:
    - spawn: python3 failed with exit code 1 and signal 0. /home/ozoromo/.nix-profile/bin/python3: No module named pip

- OK python venv: `Ok`
- OK javac: `javac 19.0.2`
- OK npm: `9.6.7`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 22. Remaining: 38. Limit: 60. Reset: Thu 29 Jun 2023 02:20:39 PM CEST.
  Install and authenticate via gh-cli to increase rate limit.
```

**Comment by alishewn** [comment]
same question here, might be the glibc problem

**Comment by alishewn** [comment]
> same question here, might be the glibc problem

have you solved bro? @ozoromo

**Comment by williamboman** [comment]
You're on NixOS, right? Package installation _should_ fail with a "Platform is not supported." error message on NixOS because the `codelldb` package in Mason doesn't support it - are you running it with a GNU linker (`ldd`) in PATH?

> same question here, might be the glibc problem

glibc 2.18+ should be supported by codelldb, which is an old version. If you're on NixOS you will undoubtedly run into issues trying to run the binary as-is and I'm afraid I won't be able to help with that, nor is there anything that can be done in Mason to mitigate it (there is some more info in #428, Mason _might_ eventually provide an escape hatch that would allow patching installed package binaries via `patchelf`).

**Comment by williamboman** [comment]
Also, if you are on NixOS I'd personally recommend you use their native package manager for everything (or switch OS 😆), Mason will be pretty much redundant in that case.
