### ISSUE TITLE
Errors when opening/closing a file via headless

### ISSUE THREAD

**Issue by brycepg** [williamboman/mason.nvim#1389]
### I've searched open issues for similar requests

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

When calling from headless I'm getting a number of errors relating to the LSP. I've been unable to repro after removing mason so I'm posting it here -- it could definitely be a lspconfig issue however.

My guess is this has something to do with async - with the file closing during LSP server loading

### Expected behavior

I'd like to call nvim headless commands without error. 

No errors, the LSP wrapper should check whether the document session has ended before loading symbols or whether the document has been closed if there has been and error or before attaching the LSP

### Steps to reproduce

nvim --headless ~/.config/nvim/init.lua  -c ':wq!'
:MasonUpdate"dotfiles/nvim/init.lua" "dotfiles/nvim/init.lua" 784L, 27547B written
Error requesting document symbols
Error detected while processing command line:
[LSP] No client with id 1

### Neovim version (>= 0.7)

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

Linux DESKTOP-91JO4QM 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Healthcheck output

```shell
==============================================================================
mason: require("mason.health").check()

mason.nvim ~
- OK mason.nvim version v1.5.0
- OK PATH: prepend
- OK Providers: 
  mason.providers.registry-api
  mason.providers.client
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- OK Registry `github.com/mason-org/mason-registry version: 2023-07-02-ugly-base` is installed.

mason.nvim [Core utils] ~
- OK unzip: `UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.`
- OK wget: `GNU Wget 1.21.2 built on linux-gnu.`
- OK curl: `curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.14`
- OK gzip: `gzip 1.10`
- OK tar: `tar (GNU tar) 1.34`
- OK bash: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
- OK sh: `Ok`

mason.nvim [Languages] ~
- WARNING Go: not available
  - ADVICE:
    - spawn: go failed with exit code - and signal -. go is not executable
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer failed with exit code - and signal -. composer is not executable
- WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. php is not executable
- WARNING cargo: not available
  - ADVICE:
    - spawn: cargo failed with exit code - and signal -. cargo is not executable
- WARNING Ruby: not available
  - ADVICE:
    - spawn: ruby failed with exit code - and signal -. ruby is not executable
- WARNING javac: not available
  - ADVICE:
    - spawn: javac failed with exit code - and signal -. javac is not executable
- WARNING java: not available
  - ADVICE:
    - spawn: java failed with exit code - and signal -. java is not executable
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- WARNING RubyGem: not available
  - ADVICE:
    - spawn: gem failed with exit code - and signal -. gem is not executable
- OK python: `Python 3.10.6`
- OK luarocks: `/usr/bin/luarocks 3.8.0`
- WARNING node: unsupported version `v12.22.9`
  - ADVICE:
    - Node version must be >= 14
- OK npm: `9.5.1`
- OK pip: `pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)`
- OK python venv: `Ok`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: Sun Jul  2 21:03:23 2023.
  Install and authenticate via gh-cli to increase rate limit.
```

**Comment by williamboman** [comment]
Hello! At first glance this definitely doesn't seem like it's related to Mason. I also noticed you're running an old Node version, if you use a Node-based language server you'll want to upgrade it.

> nvim --headless ~/.config/nvim/init.lua -c ':wq!'
> :MasonUpdate "dotfiles/nvim/init.lua" "dotfiles/nvim/init.lua" 784L, 27547B written
> Error requesting document symbols
> Error detected while processing command line: [LSP] No client with id 1

I'm not sure how to interpret this. Where does `:MasonUpdate` come from? Is the issue the last two error logs? If you can't reproduce without Mason it might be because the LSP client doesn't start because you've only installed the language server via Mason.
