### ISSUE TITLE
Support rubocop as an LSP

### ISSUE THREAD

**Issue by gongfarmer** [williamboman/mason.nvim#1394]
### I've searched open issues for similar requests

- [X] Yes

### I've manually reviewed logs to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

Rubocop has long existed in the mason package list, as a linter.

Recent rubocop releases starting at v1.53 now [include built-in lsp support](https://github.com/rubocop/rubocop/pull/11926).

Please support rubocop as an lsp.

### Expected behavior

In the Mason UI, rubocop should appear as an option when filtered on "(2) LSP)"
When Mason has rubocop installed, opening a ruby source file should attach the rubocop lsp
Support the lsp capabilities listed here: https://github.com/rubocop/rubocop/blob/master/lib/rubocop/lsp/routes.rb

### Steps to reproduce

1. Install rubocop through mason
2. Hit Enter on rubocop to show package metadata
3. Notice "categories: Formatter, Linter" does not include LSP
4. Open a ruby source file, notice that rubocop is not an available LSP option even when installed

### Affected packages

rubocop

### Neovim version (>= 0.7)

NVIM v0.10.0-dev-309+g4e5061dba

### Operating system/version

Linux fhanson-eng 5.10.0-22-amd64 #1 SMP Debian 5.10.178-3 (2023-04-22) x86_64 GNU/Linux

### Healthcheck

```Text
==============================================================================
mason: require("mason.health").check()

mason.nvim ~
- OK mason.nvim version v1.6.0
- OK PATH: prepend
- OK Providers: 
    mason-x.provider
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- OK Registry `github.com/mason-org/mason-registry version: 2023-07-04-silly-china` is installed.

mason.nvim [Core utils] ~
- OK unzip: `UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.`
- OK wget: `GNU Wget 1.21 built on linux-gnu.`
- OK curl: `curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1n zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3`
- OK gzip: `gzip 1.10`
- OK tar: `tar (GNU tar) 1.34`
- OK bash: `GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)`
- OK sh: `Ok`

mason.nvim [Languages] ~
- WARNING luarocks: not available
  - ADVICE:
    - spawn: luarocks failed with exit code - and signal -. luarocks is not executable
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer failed with exit code - and signal -. composer is not executable
- OK Ruby: `ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]`
- OK PHP: `PHP 7.4.33 (cli) (built: Feb 22 2023 20:07:47) ( NTS )`
- OK node: `v20.0.0`
- WARNING javac: not available
  - ADVICE:
    - spawn: javac failed with exit code - and signal -. javac is not executable
- OK RubyGem: `3.2.5`
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- OK python: `Python 3.9.2`
- OK npm: `9.6.6`
- OK Go: `go version go1.19.8 linux/amd64`
- WARNING cargo: unsupported version `cargo 1.46.0`
  - ADVICE:
    - Some cargo installations require Rust >= 1.60.0.
- OK java: `openjdk version "11.0.18" 2023-01-17`
- OK pip: `pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)`
- OK python venv: `Ok`

mason.nvim [GitHub] ~
- WARNING Failed to check GitHub API rate limit status.
```

**Comment by williamboman** [comment]
Hello! So the category is really just a visual property, and may be changed in the package definition here https://github.com/mason-org/mason-registry. For the LSP configuration, assuming you use nvim-lspconfig, there needs to exist a server configuration in https://github.com/neovim/nvim-lspconfig (which is unrelated to this project). PRs welcome!

**Comment by gongfarmer** [comment]
The `nvim-lspconfig` project now has a rubocop lsp configuration:  https://github.com/neovim/nvim-lspconfig/pull/2700

**Comment by gongfarmer** [comment]
PR is up:  https://github.com/mason-org/mason-registry/pull/2084

**Comment by williamboman** [comment]
Thanks!
