### ISSUE TITLE
Mason is not working with Lazyvim on nixos 

### ISSUE THREAD

**Issue by Dimkar3000** [williamboman/mason.nvim#1396]
### I've searched open issues for similar requests

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

I just installed nixos on my laptop as a experiment. I would like to setup my development envirnoment using lazyvim as the ide. Following the instructions provided I managed to fully install it but mason still gives me toubles. 

## The problem
when i try to install packages I get an empty list and a error: 

## What I tried:
- reinstalling lazyvim 
- changing the default mason config with examples from other bugs solves in the issues. `GitHubRegistrySource(repo=mason-org/mason-registry) failed to install: Failed to download registry archive.`
- Trying to Run MasonUpdate the problem continiues. 

## Environment
Essentially a vanilla nixos install with gnome. My configuration file has just basic development programs. I also enabled the example lazyvim plugin to test it. 

### Expected behavior

Mason Packages list appearing and runnning `:MasonUpdate` returns the same error 

### Affected packages

All

### Mason output

```Text
Uninstalled registries
- github.com/mason-org/mason-registry [uninstalled]
```

### Installation log

```Text
[ERROR Πεμ 06 Ιουλ 2023 08:06:52 πμ EEST] ...im/lazy/mason.nvim/lua/mason-registry/sources/github.lua:181: Failed to install registry GitHubRegistrySource(repo=mason-org/mason-registry). "Failed to download registry archive."
```

### Neovim version (>= 0.7)

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/5gi551i7y5clpaqh8pgcj2xiwjb378g7-neovim-unwrapped-0.9.1/share/nvim
"

Run :checkhealth for more info

### Operating system/version

Linux nixos 6.1.37 #1-NixOS SMP PREEMPT_DYNAMIC Sat Jul  1 11:16:27 UTC 2023 x86_64 GNU/Linux

### Healthcheck

```Text
==============================================================================
mason: require("mason.health").check()

mason.nvim ~
- OK mason.nvim version v1.6.0
- OK PATH: prepend
- OK Providers: 
  mason.providers.registry-api
  mason.providers.client
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- ERROR Registry `github.com/mason-org/mason-registry [uninstalled]` is not installed.
  - ADVICE:
    - Run :MasonUpdate to install.

mason.nvim [Core utils] ~
- OK unzip: `UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send`
- OK wget: `GNU Wget 1.21.4 built on linux-gnu.`
- OK curl: `curl 8.1.1 (x86_64-pc-linux-gnu) libcurl/8.1.1 OpenSSL/3.0.9 zlib/1.2.13 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.4 libssh2/1.11.0 nghttp2/1.51.0`
- OK gzip: `gzip 1.12`
- OK tar: `tar (GNU tar) 1.34`
- OK bash: `GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)`
- OK sh: `Ok`

mason.nvim [Languages] ~
- WARNING Go: not available
  - ADVICE:
    - spawn: go failed with exit code - and signal -. go is not executable
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer failed with exit code - and signal -. composer is not executable
- WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. php is not executable
- WARNING cargo: not available
  - ADVICE:
    - spawn: cargo failed with exit code - and signal -. cargo is not executable
- WARNING luarocks: not available
  - ADVICE:
    - spawn: luarocks failed with exit code - and signal -. luarocks is not executable
- WARNING javac: not available
  - ADVICE:
    - spawn: javac failed with exit code - and signal -. javac is not executable
- WARNING java: not available
  - ADVICE:
    - spawn: java failed with exit code - and signal -. java is not executable
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- OK python: `Python 3.10.11`
- OK node: `v18.16.1`
- OK Ruby: `ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [x86_64-linux]`
- OK python3_host_prog: `Python 3.10.11`
- WARNING pip: not available
  - ADVICE:
    - spawn: python3 failed with exit code 1 and signal 0. /run/current-system/sw/bin/python3: No module named pip

- WARNING python3_host_prog pip: not available
  - ADVICE:
    - spawn: /nix/store/n74a7w39yh7cq7y9kf5fjld6d3wkhfsq-neovim-0.9.1/bin/nvim-python3 failed with exit code 1 and signal 0. /nix/store/zhhf5700f54azlh0kgkivz06gcx11mb6-python3-3.10.11-env/bin/python3.10: No module named pip

- OK python venv: `Ok`
- OK RubyGem: `3.4.13`
- OK npm: `9.5.1`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 0. Remaining: 5000. Limit: 5000. Reset: Πεμ 06 Ιουλ 2023 09:07:54 πμ EEST.
```

**Comment by davidSimek** [comment]
Hi, I just want to say I have same problem running vanilla nvim on voidOS with neovim 0.9.1.

**Comment by cartercanedy** [comment]
same issue here

**Comment by williamboman** [comment]
If you set DEBUG log level (`:h mason-debugging`) you should be able to see more information. Most likely you either have some network issues or file permission issues.

**Comment by davidSimek** [comment]
thank you so much @williamboman. I checked out logs and I didn't have wget installed. @cartercanedy and @Dimkar3000 maybe you could have same problem.
