### ISSUE TITLE
Failed to install texlab on Alpine Linux

### ISSUE THREAD

**Issue by foxyseta** [williamboman/mason.nvim#1400]
### I've searched open issues for similar requests

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

When trying to install the `texlab` LSP with Mason on Alpine Linux, I get an error message. May be related to #995?

### Expected behavior

The `texlab` LSP gets correctly installed.

### Affected packages

texlab

### Installation log

```Text
`[ERROR Sat Jul  8 20:57:41 2023] ...ck/paks/opt/mason.nvim/lua/mason-core/installer/init.lua:249: Installation failed for Package(name=texlab) error="The current platform is unsupported."`
```

### Neovim version (>= 0.7)

NVIM v0.9.1
Build type: MinSizeRel
LuaJIT 2.1.0-beta3

### Operating system/version

Linux foxy-thinkpad 6.1.38-0-lts #1-Alpine SMP PREEMPT_DYNAMIC Wed, 05 Jul 2023 18:57:35 +0000 x86_64 GNU/Linux

### Healthcheck

```Text
All is `OK`.
```

**Comment by fauust** [comment]
@foxyseta did you by any chance found a workaround for this?

I must admit that I am very new to neovim (lazyvim) and I am not sure how to tell to mason not to try to install texlab and use the one already installed by apk...

**Comment by foxyseta** [comment]
I am not on lazyvim, personally. I'm using the in-house package manager of my own indie neovim distribution ([visimp](https://visimp.teapot.ovh)). That has an option to do what you're looking for: https://visimp.teapot.ovh/docs/layers/languages/#configuration.
