### ISSUE TITLE
Angular Language Server Wrong Typescript version

### ISSUE THREAD

**Issue by Fabyao** [williamboman/mason.nvim#1404]
### I've searched open issues for similar requests

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

I have noticed some incompatibilities between AngularLS and Typescript. That is when installing the Angular Language Server via Mason, the latest Typescript version (currently 5.1.6) is installed. This can be verified by going in `.local/share/nvim/mason/packages/angular-language-server/package.json` .

Regardless on the Angular Language Server version installed, Mason always installs the latest Typescript version. This causes issues where the AngularLsp seems to successfully attache to the buffer however, no suggestion, or go to definition from template actully work.

To overcome this, I have edited `.local/share/nvim/mason/packages/angular-language-server/package.json` and lowered to version to 4.6.4 and did an `npm i`. This fixed the go to definition and suggestions issues.

I am not sure this is an issue with Mason as I dont know where Mason works out the TypeScript version to install with AngularLS

### Expected behavior

Angular Language Server should work without editing  `.local/share/nvim/mason/packages/angular-language-server/package.json` to lower the Typescript version.

Actually TypeScript should not be a dependency and should not be installed. The language server will fall back on the locall typescript version

### Affected packages

Angular Language Server

### Installation log

```Text
No errors in the log
```

### Neovim version (>= 0.7)

NVIM v0.10.0-dev-653+gfbeef0d4e
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system/version

PopOs 22.04

### Healthcheck

```Text
blank
```

**Comment by williamboman** [comment]
The typescript version bundled with the Angular language server is only used as a fallback. Ideally you should have the correct typescript version installed in the project you're working on.

**Comment by Fabyao** [comment]
@williamboman thanks for looking into this. I have the correct typescript version installed in my project. To prove this is the case, I have navigated to `.local/share/nvim/mason/packages/angular-language-server` and ran `npm uninstall typescript`. This caused the Language Server to fall back on my local typescript version which worked. So it appears the global typescript version takes precedent over the local version.

**Comment by williamboman** [comment]
Ah I see. The setup mimics the [VSCode extension](https://github.com/angular/vscode-ng-language-service/blob/23dcaaa6fdb4aad4dea0d311a3c7719f8c1ecd31/client/src/client.ts#L389-L399), which also bundles typescript (version 4.8.2). It does seem like the bundled one takes precedence, I remembered incorrectly.

> Nevertheless, the typescript version bundled with the Language Server should be compatible with it

Yeah I think pinning the Typescript version to 4.8.2, similar to the VSCode extension, would be the solution here. I assumed they designed it this way to allow users to use a custom version of Typescript, but it seems like typescript is actually a hard dependency of the language server? Anyways, [this](https://github.com/mason-org/mason-registry/pull/2147) should fix it.

**Comment by Fabyao** [comment]
Thank you for the quick fix. Pinning the typescript version to 4.8.2 will work for the latest version of Angular Language Server. Howerver it will be incompatible with earlier versions of Angular Language Server.  For example, running `:MasonInstall angular-language-server@11.2.14` will cause the LSP to fail. To fix this, one has to navigate to `.local/share/nvim/mason/packages/angular-language-server/` and edit the `package.json` to the appropriate typescript version. In this case `4.1.5`. Then run `npm i`.

Ideally, Mason should work out the correct typescript version to install based on the Angular Language Server version. Here is a sample matrix showing the correct typescript versions for angularLs:

11.2.x --> 4.1.5
12.0.x --> 4.2.4
12.1.x --> 4.3.4
12.2.x --> 4.3.4
13.0.x --> 4.4.3
13.1.x --> 4.4.3
13.2.x --> 4.5.4
etc...

This information was taken from here: https://github.com/angular/vscode-ng-language-service/blob/13.3.x/package.json

Because these versions are unlikely to change, we could use it to work out the correct typescript version in Mason?

**Comment by williamboman** [comment]
Ugh this should really be a dependency included upstream instead. I added some mappings [here](https://github.com/mason-org/mason-registry/pull/2182) (PRs welcome for more).

**Comment by Fabyao** [comment]
Thank you @williamboman. I will raise a seperate PR for the remaining versions
