### ISSUE TITLE
tar check fails on openbsd

### ISSUE THREAD

**Issue by js0000** [williamboman/mason.nvim#1415]
### I've searched open issues for similar requests

- [X] Yes

### Is your feature request related to a problem? Please describe.

mason.nvim is great- thx!

in checkhealth i get this:

- ERROR tar: not available
  - ADVICE:
    - spawn: tar failed with exit code 1 and signal 0. tar: unknown option -- -
      usage: tar {crtux}[014578befHhjLmNOoPpqsvwXZz]
      [blocking-factor | archive | replstr] [-C directory] [-I file]
      [file ...]
      tar {-crtux} [-014578eHhjLmNOoPpqvwXZz] [-b blocking-factor]
      [-C directory] [-f archive] [-I file] [-s replstr] [file ...]

i am guessing this is because openbsd's tar executable does not use the same arguments as the gnu version of tar. i can install the gnu version (called "gtar"), but i am not at all sure if there is any way for mason to know this (maybe search for gtar if tar is not found ... ?)

### Describe the solution you'd like

for mason to check for gtar if tar does not support the necessary options

### Describe potential alternatives you've considered

i've thought about digging through the mason source, but if i don't have to, i'd rather not ...

### Additional context

i am running openbsd 7.3

**Comment by williamboman** [comment]
Hello! Is this only failing the health check or is it failing to unpack files as well (lua-language-server for example)?

**Comment by 3uryd1ce** [comment]
> Hello! Is this only failing the health check or is it failing to unpack files as well (lua-language-server for example)?

Hi @williamboman, I also use OpenBSD (I'm on 7.3-current) and can confirm that `gtar` isn't found. I'm also unable to install `lua-language-server` (along with some others: `shfmt`, `shellcheck`, ...). `lua-language-server` installation fails with this output:

```
[INFO  Fri Jul 28 19:35:43 2023] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:184: Executing installer for Package(name=lua-language-server) {}
[DEBUG Fri Jul 28 19:35:43 2023] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:58: Attempting to lock package Package(name=lua-language-server)
[DEBUG Fri Jul 28 19:35:43 2023] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:70: Wrote lockfile Package(name=lua-language-server)
[DEBUG Fri Jul 28 19:35:43 2023] .../.local/share/nvim/lazy/mason.nvim/lua/mason-core/fs.lua:71: fs: mkdirp /home/sylvia/.local/share/nvim/mason/staging/lua-language-server
[DEBUG Fri Jul 28 19:35:43 2023] ...zy/mason.nvim/lua/mason-core/installer/registry/init.lua:148: Compiling installer. lua-language-server {}
[DEBUG Fri Jul 28 19:35:43 2023] ...zy/mason.nvim/lua/mason-core/installer/registry/init.lua:109: Parsing spec lua-language-server {}
[DEBUG Fri Jul 28 19:35:43 2023] ...zy/mason.nvim/lua/mason-core/installer/registry/init.lua:140: Failed to parse spec spec lua-language-server PLATFORM_UNSUPPORTED
[DEBUG Fri Jul 28 19:35:43 2023] .../.local/share/nvim/lazy/mason.nvim/lua/mason-core/fs.lua:59: fs: unlink /home/sylvia/.local/share/nvim/mason/staging/lua-language-server.lock
[DEBUG Fri Jul 28 19:35:43 2023] .../.local/share/nvim/lazy/mason.nvim/lua/mason-core/fs.lua:47: fs: rmrf /home/sylvia/.local/share/nvim/mason/staging/lua-language-server
[DEBUG Fri Jul 28 19:35:43 2023] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:39: Building receipt for Package(name=lua-language-server)
[ERROR Fri Jul 28 19:35:43 2023] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:249: Installation failed for Package(name=lua-language-server) error="The current platform is unsupported."
```

Not sure what the specific problem is yet because I'm not as familiar with Lua compared to other languages or this codebase. But it appears to happen within the `M.parse` function in `lua/mason-core/installer/registry/init.lua`, before the log message about parsing purl can fire.

Two quick side notes:

1. Your tool is fantastic. Please feel free to @ me if you need anything else from me, I'm more than willing to help out. I only recently got into Neovim's LSP and it makes me wonder what I was doing before. xD
2. The tar health check issue will most likely affect other BSDs as well because they tend to use `gtar` to differentiate between tar in the base system and GNU tar from ports.

**Comment by 3uryd1ce** [comment]
I did manage to find a case in which mason's installer fails to unpack a tar file on OpenBSD due to calling tar with `--no-same-owner`.

```
[INFO  Fri Jul 28 22:35:54 2023] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:184: Executing installer for Package(name=ltex-ls) {}
[DEBUG Fri Jul 28 22:35:54 2023] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:58: Attempting to lock package Package(name=ltex-ls)
[DEBUG Fri Jul 28 22:35:54 2023] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:70: Wrote lockfile Package(name=ltex-ls)
[DEBUG Fri Jul 28 22:35:54 2023] .../.local/share/nvim/lazy/mason.nvim/lua/mason-core/fs.lua:71: fs: mkdirp /home/sylvia/.local/share/nvim/mason/staging/ltex-ls
[DEBUG Fri Jul 28 22:35:54 2023] ...zy/mason.nvim/lua/mason-core/installer/registry/init.lua:148: Compiling installer. ltex-ls {}
[DEBUG Fri Jul 28 22:35:54 2023] ...zy/mason.nvim/lua/mason-core/installer/registry/init.lua:109: Parsing spec ltex-ls {}
[DEBUG Fri Jul 28 22:35:54 2023] ...azy/mason.nvim/lua/mason-core/installer/managers/std.lua:95: std: downloading file "https://github.com/valentjn/ltex-ls/releases/download/16.0.0/ltex-ls-16.0.0.tar.gz"
[DEBUG Fri Jul 28 22:35:54 2023] ...ocal/share/nvim/lazy/mason.nvim/lua/mason-core/fetch.lua:37: Fetching URL "https://github.com/valentjn/ltex-ls/releases/download/16.0.0/ltex-ls-16.0.0.tar.gz"
[DEBUG Fri Jul 28 22:35:54 2023] ...al/share/nvim/lazy/mason.nvim/lua/mason-core/process.lua:116: Spawning cmd="curl", spawn_opts={
  args = { "-H", "User-Agent: mason.nvim v1.6.1 (+https://github.com/williamboman/mason.nvim)", "-fsSL", "-X", "GET", "-o", "/home/sylvia/.local/share/nvim/mason/staging/ltex-ls/./ltex-ls-16.0.0.tar.gz", "--connect-timeout", 30, "https://github.com/valentjn/ltex-ls/releases/download/16.0.0/ltex-ls-16.0.0.tar.gz" }
}
[DEBUG Fri Jul 28 22:35:54 2023] ...al/share/nvim/lazy/mason.nvim/lua/mason-core/process.lua:162: Spawned with pid 63916
[DEBUG Fri Jul 28 22:56:39 2023] ...al/share/nvim/lazy/mason.nvim/lua/mason-core/process.lua:148: Job pid=63916 exited with exit_code=0, signal=0
￼
[DEBUG Fri Jul 28 22:56:39 2023] ...azy/mason.nvim/lua/mason-core/installer/managers/std.lua:232: std: unpack "ltex-ls-16.0.0.tar.gz"
[DEBUG Fri Jul 28 22:56:39 2023] ...azy/mason.nvim/lua/mason-core/installer/managers/std.lua:109: std: untar "ltex-ls-16.0.0.tar.gz"
[DEBUG Fri Jul 28 22:56:39 2023] ...al/share/nvim/lazy/mason.nvim/lua/mason-core/process.lua:116: Spawning cmd="tar", spawn_opts={
  args = { "--no-same-owner", "-xvf", "ltex-ls-16.0.0.tar.gz" },
  cwd = "/home/sylvia/.local/share/nvim/mason/staging/ltex-ls/."
}
[DEBUG Fri Jul 28 22:56:39 2023] ...al/share/nvim/lazy/mason.nvim/lua/mason-core/process.lua:162: Spawned with pid 70204
[DEBUG Fri Jul 28 22:56:39 2023] ...al/share/nvim/lazy/mason.nvim/lua/mason-core/process.lua:148: Job pid=70204 exited with exit_code=1, signal=0
[DEBUG Fri Jul 28 22:56:39 2023] .../.local/share/nvim/lazy/mason.nvim/lua/mason-core/fs.lua:59: fs: unlink /home/sylvia/.local/share/nvim/mason/staging/ltex-ls.lock
[DEBUG Fri Jul 28 22:56:39 2023] .../.local/share/nvim/lazy/mason.nvim/lua/mason-core/fs.lua:47: fs: rmrf /home/sylvia/.local/share/nvim/mason/staging/ltex-ls
[DEBUG Fri Jul 28 22:56:39 2023] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:39: Building receipt for Package(name=ltex-ls)
[ERROR Fri Jul 28 22:56:39 2023] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:249: Installation failed for Package(name=ltex-ls) error=spawn: tar failed with exit code 1 and signal 0. 
```

It tries to use `--no-same-owner` which OpenBSD's tar doesn't have. I found that flag in these places.

```
tests/mason-core/installer/managers/std_spec.lua
25:        assert.spy(ctx.spawn.tar).was_called_with { "--no-same-owner", "-xvf", "file.tar" }
38:        assert.spy(ctx.spawn.tar).was_called_with { "--no-same-owner", "-xvf", "file.tar.bz2" }
51:        assert.spy(ctx.spawn.tar).was_called_with { "--no-same-owner", "-xvf", "file.tar.gz" }
64:        assert.spy(ctx.spawn.tar).was_called_with { "--no-same-owner", "-xvf", "file.tar.xz" }
77:        assert.spy(ctx.spawn.tar).was_called_with { "--no-same-owner", "-xvf", "file.tar.zst" }

lua/mason-core/installer/managers/std.lua
111:    return ctx.spawn.tar({ "--no-same-owner", "-xvf", rel_path }):on_success(function()

lua/mason-core/managers/std/init.lua
105:        "--no-same-owner",
```

**Comment by 3uryd1ce** [comment]
Well, I spent some time looking at the code and discovered that even if I get rid of `--no-same-owner` in your source code, compressed archives still cause OpenBSD's tar to exit with a non-zero exit code. This is because OpenBSD's tar implementation exits on compressed archives when no decompression related flag was passed, rather than automatically decompressing them like GNU tar does. Like this:

```
tar: input compressed with gzip; use the -z option to decompress it
```

I see different potential ways that this could be addressed, but don't know offhand how to accomplish these things in Lua. Regardless, here they are:

1) Depend on GNU tar and call `gtar` on the appropriate platforms, as well as updating documentation to be explicit about this.
2) Change the calls to tar so that they're more portable (use flags like -z on gzipped files. This would mean no `--no-same-owner`, though).
