### ISSUE TITLE
Semgrep needs to have `pysemgrep` in path as well

### ISSUE THREAD

**Issue by quantumfate** [williamboman/mason.nvim#1418]
### I've searched open issues for similar requests

- [X] Yes

### I've manually reviewed logs to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

Semgrep is a static code analysis tool and it's finally supported by mason. There is just a minor inconvenience with semgrep because using the default `semgrep` python script that mason symbolically links to `/bin` fails to run because the script `pysemgrep` needs to be there as well or in the path.

### Expected behavior

Semgrep should work out of the box for new users that don't know about experimental mode yet.

### Steps to reproduce

1. Install semgrep
2. Register semgrep via null-ls
3. Use the default configuration of null-ls

### Affected packages

semgrep

### Neovim version (>= 0.7)

NVIM v0.10.0-dev-653+gfbeef0d4ef
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system/version

Linux arcozen 6.4.2-x64v2-xanmod1-3 #1 SMP PREEMPT_DYNAMIC Fri, 07 Jul 2023 04:33:07 +0000 x86_64 GNU/Linux

### Healthcheck

```Text
mason: require("mason.health").check()

mason.nvim ~
- OK mason.nvim version v1.6.0
- OK PATH: skip
- OK Providers: 
    mason.providers.registry-api
    mason.providers.client
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- OK Registry `require("mason-registry.index")` is installed.
- OK Registry `github.com/mason-org/mason-registry version: 2023-07-19-loving-math` is installed.

mason.nvim [Core utils] ~
- OK unzip: `UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send`
- OK wget: `GNU Wget 1.21.4 built on linux-gnu.`
- OK curl: `curl 8.1.2 (x86_64-pc-linux-gnu) libcurl/8.1.2 OpenSSL/3.1.1 zlib/1.2.13 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.11.0 nghttp2/1.55.0`
- OK gzip: `gzip 1.12`
- OK tar: `tar (GNU tar) 1.34`
- OK bash: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
- OK sh: `Ok`

mason.nvim [Languages] ~
- OK cargo: `cargo 1.70.0`
- OK Ruby: `ruby 3.0.5p211 (2022-11-24 revision ba5cf0f7c5) [x86_64-linux]`
- OK Go: `go version go1.20.5 linux/amd64`
- OK PHP: `PHP 8.2.8 (cli) (built: Jul  5 2023 18:47:24) (NTS)`
- OK luarocks: `/usr/bin/luarocks 3.9.2`
- OK node: `v20.4.0`
- OK Composer: `Composer version 2.5.8 2023-06-09 17:13:21`
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- OK python: `Python 3.11.3`
- OK java: `openjdk version "17.0.7" 2023-04-18`
- OK JAVA_HOME: `openjdk version "17.0.7" 2023-04-18`
- OK RubyGem: `3.3.25`
- OK javac: `javac 17.0.7`
- OK npm: `9.8.0`
- OK pip: `pip 23.1.2 from /usr/lib/python3.11/site-packages/pip (python 3.11)`
- OK python venv: `Ok`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 3. Remaining: 57. Limit: 60. Reset: Mi 19 Jul 2023 16:37:58 CEST.
  Install and authenticate via gh-cli to increase rate limit.
```

**Comment by williamboman** [comment]
Should be fixed by https://github.com/mason-org/mason-registry/pull/2216!
