### ISSUE TITLE
cfn-lint gives no output when in nvim

### ISSUE THREAD

**Issue by V4G4X** [williamboman/mason.nvim#1430]
### I've searched open issues for similar requests

- [X] Yes

### I've manually reviewed logs to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

Having installed Mason, it works when I have to install LSPs of most languages.  
But when installing a linter for YAML files, specifically CloudFormation yaml templates it stops working out of the box. 

What I mean by this is there is no `cfn-lint` related prompts or warnings or errors where I expect them. 

But when I download `cfn-lint` myself, and run `cfn-lint template.yml` it works.

### Expected behavior

Errors about my CFN Template should pop up on my buffer the way it typically does in IDEs and for other languages.

### Steps to reproduce

1. Install Mason
2. Open Mason menu using `:Mason`
3. Look for `cfn-lint` in the list.
4. Install `cfn-lint`
5. Open a cloudformation template. Example [here](https://github.com/widdix/aws-cf-templates/blob/8efda5e6e8e0eeebb2acb650928731ef4a2f1ad3/wordpress/wordpress-ha.yaml)
6. Edit it to add mistakes
7. Save
8. Notice no errors pop up.

### Affected packages

cfn-lint

### Neovim version (>= 0.7)

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.1/share/nvim"

Run :checkhealth for more info

### Operating system/version

Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103 arm64

### Healthcheck

```Text
mason: require("mason.health").check()

mason.nvim
- OK mason.nvim version v1.6.1
- OK PATH: prepend
- OK Providers:
  mason.providers.registry-api
  mason.providers.client
- OK neovim version >= 0.7.0

mason.nvim [Registries]
- OK Registry github.com/mason-org/mason-registry version: 2023-07-27-woeful-peony is installed.

mason.nvim [Core utils]
- OK unzip: UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send
- OK wget: GNU Wget 1.21.4 built on darwin22.4.0.
- OK curl: curl 7.88.1 (x86_64-apple-darwin22.0) libcurl/7.88.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.51.0
- OK gzip: Apple gzip 403.100.6
- OK tar: `bsdtar 3.5.3 - libarchive 3.5.3 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8
- OK bash: GNU bash, version 3.2.57(1)-release (arm64-apple-darwin22)
- OK sh: Ok

mason.nvim [Languages]
- WARNING cargo: not available
  - ADVICE:
    - spawn: cargo failed with exit code - and signal -. cargo is not executable
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer failed with exit code - and signal -. composer is not executable
- WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. php is not executable
- WARNING luarocks: not available
  - ADVICE:
    - spawn: luarocks failed with exit code - and signal -. luarocks is not executable
- OK Ruby: ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin22]
- OK Go: go version go1.19.11 darwin/arm64
- OK RubyGem: 3.0.3.1
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- OK python: Python 3.11.4
- OK node: v20.5.0
- OK JAVA_HOME: openjdk version "17.0.7" 2023-04-18 LTS
- OK java: openjdk version "17.0.7" 2023-04-18 LTS
- OK javac: javac 17.0.7
- OK npm: 9.8.0
- OK pip: pip 23.0.1 from /opt/homebrew/lib/python3.11/site-packages/pip (python 3.11)
- OK python venv: Ok

mason.nvim [GitHub]
- OK GitHub API rate limit. Used: 0. Remaining: 5000. Limit: 5000. Reset: Fri Jul 28 21:46:24 2023.
```

**Comment by williamboman** [comment]
Hello! `cfn-lint` is a standalone tool that is unrelated to yaml-language-server. cfn-lint does not provide a language server implementation, so in order to get diagnostics inside Neovim you'll have to leverage a tool that does this (null-ls, ALE, for example).
