### ISSUE TITLE
Remapping toggle help

### ISSUE THREAD

**Issue by simonmandlik** [williamboman/mason.nvim#1435]
### I've searched open issues for similar requests

- [X] Yes

### Is your feature request related to a problem? Please describe.

Would it be possible to add "Toggle help" to a set of keys that can be remapped in `setup`?

### Describe the solution you'd like

Extend the setup part as follows:

```lua
keymaps = {
            -- Keymap to toggle 
            toggle_help = "<key>",
}
```

**Comment by williamboman** [comment]
Makes sense, added in #1468!

**Comment by simonmandlik** [comment]
Thanks!

Just a note, maybe add it to `README.md` as well.

**Comment by williamboman** [comment]
Ah yes, I realized I forgot it but then I forgot about forgetting it 😂, will update the README now.
