### ISSUE TITLE
[New package]: erb_lint

### ISSUE THREAD

**Issue by dbernheisel** [williamboman/mason.nvim#144]
### Package name

erb_lint

### Package homepage

https://github.com/Shopify/erb-lint

### Languages

ruby

### How is this package distributed?

gem

**Comment by williambotman** [comment]
Hello! Cool! Pull requests are always very welcomed to add new packages. If the distribution of the
package is simple, the installation will most likely be so as well (existing package installers may be
used for reference!). Otherwise, @williamboman will get around to looking into this ASAP!
