### ISSUE TITLE
Solargraph doesn't work

### ISSUE THREAD

**Issue by equal-l2** [williamboman/mason.nvim#146]
### Problem description

When opening ruby files, solargraph doesn't launch, saying `Client 1 quit with exit code 1 and signal 0`.

### Why do you think this is an issue with mason.nvim?

Solargraph is installed via mason.

### Neovim version (>= 0.7)

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.7.2_1/share/nvim"

Run :checkhealth for more info

### Operating system/version

Darwin equall2.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

### I've manually reviewed the Nvim LPS client log (`:MasonLog`) to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Affected packages

solargraph

### Steps to reproduce

1. Install solargraph with mason
2. Open ruby files

### Actual behavior

Solargraph doesn't launch when I open ruby files, saying `Client 1 quit with exit code 1 and signal 0`.

### Expected behavior

Solargraph launches and works correctly.

### LspInfo

```Text
Language client log: /Users/equall2/.cache/nvim/lsp.log
 Detected filetype:   ruby
 
 0 client(s) attached to this buffer: 
 
 Other clients that match the filetype: ruby
 
 Config: solargraph
 	filetypes:         ruby
 	root directory:    /usr/local/Homebrew/Library/Homebrew
 	cmd:               solargraph stdio
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
 
 Configured servers list: solargraph, sumneko_lua, taplo, pyright, rust_analyzer, clangd
```

### LspLog

```Text
[ERROR][2022-07-26 02:43:17] .../vim/lsp/rpc.lua:420	"rpc"	"solargraph"	"stderr"	"/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem solargraph (>= 0.a) with executable solargraph (Gem::GemNotFoundException)\n\tfrom /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'\n\tfrom /Users/equall2/.local/share/nvim/mason/bin/solargraph:23:in `<main>'\n"
```

### Healthcheck

```Text
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - OK: **Go**: `go version go1.18.4 darwin/amd64`
  - OK: **cargo**: `cargo 1.62.1 (a748cf5a3 2022-06-08)`
  - WARNING: **luarocks**: not available
  - OK: **Ruby**: `ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]`
  - OK: **RubyGem**: `3.0.3.1`
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.13.2`
  - OK: **node**: `v16.16.0`
  - OK: **python3**: `Python 3.9.13`
  - OK: **pip3**: `pip 22.1.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)`
  - OK: **javac**: `javac 17.0.1`
  - OK: **java**: `java version "17.0.1" 2021-10-19 LTS`
  - OK: **julia**: `julia version 1.7.3`
  - ERROR: **wget**: not available
  - OK: **curl**: `curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.45.1`
  - OK: **gzip**: `Apple gzip 353.100.22`
  - OK: **tar**: `bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
  - OK: **bash**: `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 0. Remaining: 5000. Limit: 5000. Reset: Tue Jul 26 03:44:04 2022.
```

**Comment by williamboman** [comment]
Hello! Ah this was something I had forgot to address before release. I've opened #152 as this applies to all gem-based packages. Thanks for reporting!
