### ISSUE TITLE
Window does not open by <C-f> for filtering language. Opening only full screen numbered language list.

### ISSUE THREAD

**Issue by nPaul** [williamboman/mason.nvim#1461]
### Discussed in https://github.com/williamboman/mason.nvim/discussions/1460

<div type='discussions-op-text'>

<sup>Originally posted by **nPaul** August 19, 2023</sup>
NVIM v0.9.1 compiled from source.
</div>

**Comment by williamboman** [comment]
That's the default UI for `:h vim.ui.select`, which is what mason.nvim uses to prompt for a selection. You can modify the behaviour of `vim.ui` components by installing 3rd party plugins, I use https://github.com/stevearc/dressing.nvim which is what's shown in the screenshot in the README.
