### ISSUE TITLE
MasonInstall fails to install java-debug-adapter

### ISSUE THREAD

**Issue by milind-shakya-sp** [williamboman/mason.nvim#1465]
### I've searched open issues for similar requests

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

MasonInstall fails to install java-debug-adapter

### Expected behavior

MasonInstall does not fail to install java-debug-adapter

### Affected packages

java-debug-adapter

### Mason output

```Text
Failed (1)
  ◍ java-debug-adapter
    Downloading file "https://github.com/microsoft/vscode-java-debug/releases/download/0.53.0/vscjava.vscode-java-debug-0.53.0.vsix"...
    ...acker/start/mason.nvim/lua/mason-core/installer/init.lua:121: ...er/start/mason.nvim/lua/mason-core/managers/std/init.lua:52: Failed to download file "https://github.com/microsoft/vscode-java-debug/releases/d
    spawn: wget failed with exit code 2 and signal 0. Usage: wget [OPTION]... [URL]...

    Try `wget --help' for more options.
```

### Installation log

```Text
Failed (1)
  ◍ java-debug-adapter
    Downloading file "https://github.com/microsoft/vscode-java-debug/releases/download/0.53.0/vscjava.vscode-java-debug-0.53.0.vsix"...
    ...acker/start/mason.nvim/lua/mason-core/installer/init.lua:121: ...er/start/mason.nvim/lua/mason-core/managers/std/init.lua:52: Failed to download file "https://github.com/microsoft/vscode-java-debug/releases/d
    spawn: wget failed with exit code 2 and signal 0. Usage: wget [OPTION]... [URL]...

    Try `wget --help' for more options.
```

### Neovim version (>= 0.7)

NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

x86_64 x86_64 x86_64 GNU/Linux

### Healthcheck

```Text
mason: require("mason.health").check()

mason.nvim report
- OK neovim version >= 0.7.0
- WARNING **Go**: not available
- OK **cargo**: cargo 1.69.0 (6e9a83356 2023-04-12)
- WARNING **luarocks**: not available
- OK **Ruby**: ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
- OK **RubyGem**: 2.0.14.1
- WARNING **Composer**: not available
- WARNING **PHP**: not available
- OK **npm**: 7.24.0
- OK **node**: v16.10.0
- OK **python3**: Python 3.9.13
- OK **pip3**: pip 22.2.1 from ~/.virtualenvs/python39/lib/python3.9/site-packages/pip (python 3.9)
- OK **javac**: javac 17.0.6
- OK **java**: openjdk version "17.0.6" 2023-01-17 LTS
- WARNING **julia**: not available
- OK **wget**: GNU Wget 1.14 built on linux-gnu.
- OK **curl**: curl 8.1.0 (x86_64-pc-linux-gnu) libcurl/8.1.0 OpenSSL/1.1.1t zlib/1.2.13 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.4 libssh2/1.10.0 nghttp2/1.53.0 librtmp/2.3
- OK **gzip**: gzip 1.5
- OK **tar**: tar (GNU tar) 1.26
- OK **bash**: GNU bash, version 4.2.46(2)-release (x86_64-koji-linux-gnu)
- OK **sh**: Ok
- OK **JAVA_HOME**: openjdk version "17.0.6" 2023-01-17 LTS
- OK GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: Wed 23 Aug 2023 03:40:46 PM UTC.
```

**Comment by williamboman** [comment]
The healthcheck output is at least ~5-6 months old, please try updating the plugin version. If the issue persists after that, please see `:help mason-debugging` and `:MasonLog` for installation logs.

**Comment by milind-shakya-sp** [comment]
Is there a way to specify the version of the package that Mason should install?

in this case Mason tries to install https://github.com/microsoft/vscode-java-debug/releases/download/0.53.0/vscjava.vscode-java-debug-0.53.0.vsix but it returns a 404.

Looks like a version earlier, https://github.com/microsoft/vscode-java-debug/releases/download/0.52.0/vscjava.vscode-java-debug-0.52.0.vsix exists, so wondering if theres a way to downgrade.

**Comment by milind-shakya-sp** [comment]
Looks like according to https://github.com/microsoft/vscode-java-debug/issues/1373 the current approach to retrieve vscode-java-debug release might not work.

**Comment by williamboman** [comment]
If you update mason.nvim it will use the latest compatible version, but yes you can otherwise install a specific version with `:MasonInstall java-debug-adapter@0.52.0`
