### ISSUE TITLE
[New package]: yamllint

### ISSUE THREAD

**Issue by dbernheisel** [williamboman/mason.nvim#147]
### Package name

yamllint

### Package homepage

https://github.com/adrienverge/yamllint

### Languages

yaml

### How is this package distributed?

pip yamllint

**Comment by williambotman** [comment]
Hello! Cool! Pull requests are always very welcomed to add new packages. If the distribution of the
package is simple, the installation will most likely be so as well (existing package installers may be
used for reference!). Otherwise, @williamboman will get around to looking into this ASAP!
