### ISSUE TITLE
mason.nvim breaking rtp

### ISSUE THREAD

**Issue by lexisother** [williamboman/mason.nvim#1475]
### I've searched open issues for similar requests

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

I have some functionality in my `init.vim` to add my dotfiles folder to the runtimepath so loading of modules in the `lua` folder from my `init.lua` works correctly:
```vim
let g:nvim_dotfiles_dir = expand('<sfile>:p:h')

function! s:configure_runtimepath() abort
        let rtp = split(&runtimepath, ',')
        let dotf = g:nvim_dotfiles_dir
        if index(rtp, dotf         ) < 0 | call insert(rtp, dotf         ) | endif
        if index(rtp, dotf.'/after') < 0 | call    add(rtp, dotf.'/after') | endif
        let &runtimepath = join(rtp, ',')
endfunction
call s:configure_runtimepath()

luafile <sfile>:h/init.lua
```

The reason I do this is because my configs are stored in `~/.dotfiles/nvim`, and my configuration is obviously initially loaded from `~/.config/nvim/init.vim`. This contains a simple `source` call to the `init.vim` from the dotfiles folder. Without the above code, `require` would not pick anything up in my `lua` folder.

*However,* the moment mason.nvim loads (which is loaded by lazy.nvim from the very first module I tell nvim to require), any subsequent modules fail to load.

My `init.lua` looks like this:
```lua
local init_modules = {
        "aly.plugins",
        "aly.options"
}

for _, module in ipairs(init_modules) do
        local ok, err = pcall(require, module)
        if not ok then
                error("Error loading " .. module .. "\n\n" .. err)
        end
end
```

The `aly.plugins` module loads lazy.nvim, which loads mason.nvim. After this happens, `require` can no longer find `aly.options` and throws an error.

<details><summary>The contents of `~/.dotfiles/nvim/lua/aly/plugins.lua`</summary>

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable",
		lazypath,
	})
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
	{
		"neovim/nvim-lspconfig",
		dependencies = {
			{ "williamboman/mason.nvim", config = true },
--			"williamboman/mason-lspconfig.nvim",
--			{ "j-hui/fidget.nvim", tag = "legacy", opts = {} },
--
--			"folke/neodev.nvim",
		},
	},
}, {})
```
</details>

<details><summary>The contents of `~/.dotfiles/nvim/lua/aly/options.lua`</summary>

```lua
print("yes")

local options = {
	termguicolors = true, -- how do I even use the editor without this?
}

for o, _ in pairs(options) do
	vim.opt[o] = _
end

vim.cmd("filetype plugin indent on")
vim.cmd("syntax enable")
```
</details>

### Expected behavior

I expect mason.nvim not to mess with the rtp in a way that breaks my loading.

### Steps to reproduce

1. Set up a folder somewhere that will contain the real editor configs, e.g. `~/.dotfiles/nvim`
2. Create `~/.config/nvim/init.vim` with the contents `source ~/.dotfiles/nvim/init.vim`
3. `~/.dotfiles/nvim/init.vim` should contain the rtp fix from my first codeblock in the problem description.
4. `~/.dotfiles/nvim/init.lua` should contain the module require loop from my second codeblock in the problem description.
5. Place the other two files at the bottom of the problem description in the appropriate locations.
6. lazy.nvim should install mason.nvim, after which `aly.options` will fail to load.

### Neovim version (>= 0.7)

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.1692616192

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Operating system/version

Linux alyxiapc 6.4.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 24 Aug 2023 00:38:14 +0000 x86_64 GNU/Linux

### Healthcheck output

```shell
mason: require("mason.health").check()

mason.nvim
- OK mason.nvim version v1.7.0
- OK PATH: prepend
- OK Providers: 
  mason.providers.registry-api
  mason.providers.client
- OK neovim version >= 0.7.0

mason.nvim [Registries]
- OK Registry github.com/mason-org/mason-registry version: 2023-08-28-vanilla-denim is installed.

mason.nvim [Core utils]
- OK unzip: UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send
- OK wget: GNU Wget 1.21.4 built on linux-gnu.
- OK curl: curl 8.2.1 (x86_64-pc-linux-gnu) libcurl/8.2.1 OpenSSL/3.1.2 zlib/1.3 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.11.0 nghttp2/1.55.1
- OK gzip: gzip 1.12
- OK tar: tar (GNU tar) 1.35
- OK bash: GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
- OK sh: Ok

mason.nvim [Languages]
- OK Go: go version go1.21.0 linux/amd64
- OK Ruby: ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux]
- OK PHP: PHP 8.2.9 (cli) (built: Aug 13 2023 06:12:43) (NTS)
- OK cargo: cargo 1.71.0 (cfd3bbd8f 2023-06-08)
- OK luarocks: /usr/bin/luarocks 3.9.2
- OK node: v20.2.0
- OK Composer: Composer version 2.5.8 2023-06-09 17:13:21
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- OK python: Python 3.11.3
- OK RubyGem: 3.3.25
- OK java: openjdk version "17.0.8.1" 2023-08-24
- OK javac: javac 17.0.8.1
- OK npm: 9.6.6
- OK pip: pip 23.2.1 from /usr/lib/python3.11/site-packages/pip (python 3.11)
- OK python venv: Ok

mason.nvim [GitHub]
- OK GitHub API rate limit. Used: 112. Remaining: 4888. Limit: 5000. Reset: Mon 28 Aug 2023 09:41:58 PM CEST.
```

### Screenshots

![image](https://github.com/williamboman/mason.nvim/assets/54973868/14fe7f9f-31c4-42e2-9602-a291db5d355b)

**Comment by williamboman** [comment]
Hello! I'm 99.99% certain this is not due to mason.nvim, but probably due to lazy.nvim or some other plugin that actually modifies rtp.

**Comment by williamboman** [comment]
I'm pretty sure lazy.nvim does stuff to rtp when it loads (I believe via `package.loader`). Mason's setup is [very simple](https://github.com/williamboman/mason.nvim/blob/main/lua/mason/init.lua#L19-L35), and Mason never touches anything related to rtp or Lua module loading.

**Comment by lexisother** [comment]
I will try adjusting my config a bit and report back later.

**Comment by lexisother** [comment]
More plugins started causing the issue, I guess I just got lucky with the set I used for testing. I've adjusted my issue to accommodate for rtp weirdness for now. Thanks!
