### ISSUE TITLE
GraphQL LSP Missing dependency

### ISSUE THREAD

**Issue by acoffman** [williamboman/mason.nvim#1476]
### I've searched open issues for similar requests

- [X] Yes

### I've manually reviewed logs to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

`graphql-lsp` invocation fails with error `Error: Cannot find module 'graphql'`

This appears to be due to missing the `graphql` dependency. I believe this is due to the installed `graphql-language-service-cli` package specifying `graphql` as a dev dependency rather than a direct one:

https://www.npmjs.com/package/graphql-language-service-cli?activeTab=dependencies 

It seems like, based on this: https://github.com/mason-org/mason-registry/blob/main/CONTRIBUTING.md#npm

Adding 
```
 extra_packages:
    - graphql
 ```

Should solve the issue. If you agree, I'm happy to open a PR.

Thanks!
Adam

### Expected behavior

`graphql-lsp` starts successfully.

### Steps to reproduce

Install `graphql-language-service-cli` via mason, open a graphql file in vim.

### Affected packages

graphql-language-service-cli

### Neovim version (>= 0.7)

NVIM v0.10.0-dev-772+g0211f889b-Homebrew
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

Darwin 3071-AL-00007 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64 x86_64

### Healthcheck

```Text
mason: require("mason.health").check()

mason.nvim ~
- OK mason.nvim version v1.7.0
- OK PATH: prepend
- OK Providers: 
    mason.providers.registry-api
    mason.providers.client
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- OK Registry `github.com/mason-org/mason-registry version: 2023-08-28-vanilla-denim` is installed.

mason.nvim [Core utils] ~
- OK unzip: `UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send`
- OK wget: `GNU Wget 1.21.4 built on darwin22.4.0.`
- OK curl: `curl 8.1.2 (x86_64-apple-darwin22.0) libcurl/8.1.2 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.51.0`
- OK gzip: `Apple gzip 403.100.6`
- OK tar: `bsdtar 3.5.3 - libarchive 3.5.3 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
- OK bash: `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin22)`
- OK sh: `Ok`

mason.nvim [Languages] ~
- WARNING Go: not available
  - ADVICE:
    - spawn: go failed with exit code - and signal -. go is not executable
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer failed with exit code - and signal -. composer is not executable
- WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. php is not executable
- WARNING luarocks: not available
  - ADVICE:
    - spawn: luarocks failed with exit code - and signal -. luarocks is not executable
- OK node: `v18.13.0`
- OK Ruby: `ruby 3.2.0 (2022-12-25 revision a528908271) +YJIT [x86_64-darwin22]`
- OK RubyGem: `3.4.12`
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- OK cargo: `cargo 1.68.0-nightly (2381cbdb4 2022-12-23)`
- OK npm: `8.19.3`
- OK python: `Python 3.8.5`
- OK java: `java version "1.8.0_201"`
- OK javac: `Ok`
- OK pip: `pip 22.0.4 from /Users/acoffman/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pip (python 3.8)`
- OK python venv: `Ok`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 4. Remaining: 56. Limit: 60. Reset: Mon Aug 28 14:59:09 2023.
  Install and authenticate via gh-cli to increase rate limit.
```
```


### Screenshots or recordings

_No response_

**Comment by acoffman** [comment]
Hi! Thanks for following up.

So, opening a GQL file results in the following popping up:
![Screenshot 2023-08-29 at 8 01 03 AM](https://github.com/williamboman/mason.nvim/assets/13370/cf71ccc4-fc3d-4a1d-a2d5-aa8ab64336df)

Checking the logfile or `:LspLog` gives the following:

```
[ERROR][2023-08-29 08:02:25] .../vim/lsp/rpc.lua:675	"rpc"	"/Users/acoffman/.local/share/nvim/mason/bin/graphql-lsp"	"stderr"	"node:internal/modules/cjs/loader:1042\n  throw err;\n  ^\n\nError: Cannot find module 'graphql'\nRequire stack:\n- /Users/acoffman/.local/share/nvim/mason/packages/graphql-language-service-cli/node_modules/graphql-language-service-cli/dist/client.js\n- /Users/acoffman/.local/share/nvim/mason/packages/graphql-language-service-cli/node_modules/graphql-language-service-cli/dist/cli.js\n- /Users/acoffman/.local/share/nvim/mason/packages/graphql-language-service-cli/node_modules/graphql-language-service-cli/bin/graphql.js\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)\n    at Module._load (node:internal/modules/cjs/loader:885:27)\n    at Module.require (node:internal/modules/cjs/loader:1105:19)\n    at require (node:internal/modules/cjs/helpers:103:18)\n    at Object.<anonymous> (/Users/acoffman/.local/share/nvim/mason/packages/graphql-language-service-cli/node_modules/graphql-language-service-cli/dist/client.js:6:19)\n    at Module._compile (node:internal/modules/cjs/loader:1218:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)\n    at Module.load (node:internal/modules/cjs/loader:1081:32)\n    at Module._load (node:internal/modules/cjs/loader:922:12)\n    at Module.require (node:internal/modules/cjs/loader:1105:19) {\n  code: 'MODULE_NOT_FOUND',\n  requireStack: [\n    '/Users/acoffman/.local/share/nvim/mason/packages/graphql-language-service-cli/node_modules/graphql-language-service-cli/dist/client.js',\n    '/Users/acoffman/.local/share/nvim/mason/packages/graphql-language-service-cli/node_modules/graphql-language-service-cli/dist/cli.js',\n    '/Users/acoffman/.local/share/nvim/mason/packages/graphql-language-service-cli/node_modules/graphql-language-service-cli/bin/graphql.js'\n  ]\n}\n\nNode.js v18.13.0\n"
```

If I invoke the mason installed lsp manually I get a more nicely formatted stack trace of the same error:

```
 ~/.local/share/nvim/mason/bin/graphql-lsp
node:internal/modules/cjs/loader:1042
  throw err;
  ^

Error: Cannot find module 'graphql'
Require stack:
- /Users/acoffman/.local/share/nvim/mason/packages/graphql-language-service-cli/node_modules/graphql-language-service-cli/dist/client.js
- /Users/acoffman/.local/share/nvim/mason/packages/graphql-language-service-cli/node_modules/graphql-language-service-cli/dist/cli.js
- /Users/acoffman/.local/share/nvim/mason/packages/graphql-language-service-cli/node_modules/graphql-language-service-cli/bin/graphql.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/acoffman/.local/share/nvim/mason/packages/graphql-language-service-cli/node_modules/graphql-language-service-cli/dist/client.js:6:19)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/acoffman/.local/share/nvim/mason/packages/graphql-language-service-cli/node_modules/graphql-language-service-cli/dist/client.js',
    '/Users/acoffman/.local/share/nvim/mason/packages/graphql-language-service-cli/node_modules/graphql-language-service-cli/dist/cli.js',
    '/Users/acoffman/.local/share/nvim/mason/packages/graphql-language-service-cli/node_modules/graphql-language-service-cli/bin/graphql.js'
  ]
}

Node.js v18.13.0
```

**Comment by williamboman** [comment]
Thanks! Do you have something related to peer dependencies inside `~/.npmrc`?

**Comment by acoffman** [comment]
No, I don't even have an `~/.npmrc` as far as I can tell. Just a `.npm` directory:
```
ls ~/ | grep -i npm
.npm
```
Which has the following inside:
```
_cacache 
_locks
_logs
_npx
_update-notifier-last-checked
anonymous-cli-metrics.json
eresolve-report.txt
index-v5
node-sass
```

I think you might be on to something in general though with the peer dependencies. As I mentioned in the original issue, the `graphql` package is listed as a Dev Dependency of `graphql-language-service-cli`. I believe that the default behavior is to install dev deps, but that does not seem to be occurring here.

**Comment by williamboman** [comment]
It's also listed as a peer dependency, and gets installed on all machines I have access to. npm reintroduced the behaviour of automatically installing `peerDependencies` starting at v7, so not really sure what might be happening seeing as you're on 8 (according to the health check).

Just to rule out the case where there's no `.npmrc` lingering about, what does npm tell you if you go to the `graphql-language-server-cli` installation directory and run:

```
~/.local/share/nvim/mason/packages/graphql-language-service-cli
$ npm config get legacy-peer-deps
```

**Comment by acoffman** [comment]
Well, that explains the issue!

```
~/.local/share/nvim/mason/packages/graphql-language-service-cli as acoffman at 3071-AL-00007
λ npm config get legacy-peer-deps
undefined
```

But based on this:
>starting at v7, so not really sure what might be happening seeing as you're on 8 (according to the health check).

I ran `npm --version` out of curiosity and in that directory I get `6.14.11` even though the version I get elsewhere is `8.19.3`.

So it seems like the mismatched `npm` versions are to blame and the outdated version isn't installing the peer dependency. Apologies for the wild goose chase, as that's almost certainly an issue with my system rather than mason.

Would it be worth adding a note to the health check or elsewhere that `npm >= 7` is required to successfully install some packages?

Thanks for an excellent project!

**Comment by williamboman** [comment]
There is a version check in the healthcheck, although it checked for `>= 6`, updated to `>= 7` [here](https://github.com/williamboman/mason.nvim/pull/1480).

Maybe you had activated a project-local Node & npm version (for example via nvm), which will cause Neovim to inherit it when opened in a shell. This will cause Mason to end up using those executables during installation. Using different "environments" in Neovim is problematic as there's more and more editor functionality that shells out to external tooling, and that tooling likely relies on a separate environment than your project-local one (if that makes sense). Not sure what the best way to solve it would be, and right now it's up to users to make sure Neovim has the correct environment.

**Comment by acoffman** [comment]
Yeah, that appears to be exactly what's happening. All my individual projects have a project-local node/npm version which is what was being reported in the health check (the npm version for the project dir I happened to be in) but globally, it was using a way out of date version Updating my global npm fixed the issue.

As you said, there's not much mason (or any other plugin) really can do if you hand it an incorrect environment to work with.
