### ISSUE TITLE
Add ability to stop/disable/restart running stuff (servers)

### ISSUE THREAD

**Issue by Andrew15-5** [williamboman/mason.nvim#1492]
### I've searched open issues for similar requests

- [X] Yes

### Is your feature request related to a problem? Please describe.

I wanted to try and stop `typst-lsp` to check something, but I quickly found out that there is no way to do it.

### Describe the solution you'd like

`:MasonDisable` and `:MasonRestart` would be nice if user want to disable everything that is currently running through `mason`. Maybe add optional arguments to disable specific things (1 name per argument).

As an _addition_ in TUI (`:Mason`) there could be status "running" and a shortcut to disable/restart the things that are "running".

But in any case, there should be a quick way to do it, so that users can make custom shortcuts/commands/functions that can use `mason`'s disable/restart API (command/function).

**Comment by williamboman** [comment]
Hello! Mason is not involved in running anything, it only installs packages and makes them available for usage by other 3rd party plugins or builtin features. Most likely you're using nvim-lspconfig to set up LSP servers, in which case there's `:LspStop`. If you use `:h vim.lsp.start()` directly there's `:h vim.lsp.stop_client()` to stop clients.
