### ISSUE TITLE
Pest language server is not working propperly

### ISSUE THREAD

**Issue by jmwielandt** [williamboman/mason.nvim#1503]
### I've searched open issues for similar requests

- [X] Yes

### I've manually reviewed logs to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

Things that are failing:
- Syntax hilight
- Filetype detection

### Expected behavior

- Syntax is hilighted
- Filetype is detected propperly

### Steps to reproduce

In a fresh environment, install nvim 9.0.2, setup packer with mason.nvim and it's dependencies. With `:Mason` install pest-language-server, on `after/lsp.lua` add the setup with mason and mason-lspconfig.

### Affected packages

pest-language-server

### Neovim version (>= 0.7)

NVIM v0.9.2
Build type: RelWithDebInfo
LuaJIT 2.1.1694082368

### Operating system/version

windows 10 home single language 22H2

### Healthcheck

```Text
mason: require("mason.health").check()

mason.nvim ~
- OK mason.nvim version v1.8.0
- OK PATH: prepend
- OK Providers: 
  mason.providers.registry-api
  mason.providers.client
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- OK Registry `github.com/mason-org/mason-registry version: 2023-09-21-spooky-reward` is installed.

mason.nvim [Core utils] ~
- WARNING unzip: not available
  - ADVICE:
    - spawn: unzip failed with exit code - and signal -. unzip is not executable
- WARNING wget: not available
  - ADVICE:
    - spawn: wget failed with exit code - and signal -. wget is not executable
- OK curl: `curl 8.0.1 (Windows) libcurl/8.0.1 Schannel WinIDN
`
- WARNING gzip: not available
  - ADVICE:
    - spawn: gzip failed with exit code - and signal -. gzip is not executable
- OK tar: `bsdtar 3.5.2 - libarchive 3.5.2 zlib/1.2.5.f-ipp 
`
- OK pwsh: `7.3.7 Microsoft Windows 10.0.19045 Win32NT
`
- WARNING 7z: not available
  - ADVICE:
    - spawn: 7z failed with exit code - and signal -. 7z is not executable

mason.nvim [Languages] ~
- WARNING luarocks: not available
  - ADVICE:
    - spawn: luarocks failed with exit code - and signal -. luarocks is not executable
- WARNING Ruby: not available
  - ADVICE:
    - spawn: ruby failed with exit code - and signal -. ruby is not executable
- WARNING RubyGem: not available
  - ADVICE:
    - spawn: gem.cmd failed with exit code - and signal -. gem.cmd is not executable
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer.bat failed with exit code - and signal -. composer.bat is not executable
- WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. php is not executable
- WARNING npm: not available
  - ADVICE:
    - spawn: npm.cmd failed with exit code - and signal -. npm.cmd is not executable
- WARNING node: not available
  - ADVICE:
    - spawn: node failed with exit code - and signal -. node is not executable
- WARNING javac: not available
  - ADVICE:
    - spawn: javac failed with exit code - and signal -. javac is not executable
- WARNING java: not available
  - ADVICE:
    - spawn: java failed with exit code - and signal -. java is not executable
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- WARNING python: not available
  - ADVICE:
    - spawn: python failed with exit code - and signal -. python is not executable
- WARNING pip: not available
  - ADVICE:
    - spawn: python failed with exit code - and signal -. python is not executable
- WARNING python venv: not available
  - ADVICE:
    - On Debian/Ubuntu systems, you need to install the python3-venv package using the following command:
      
      apt-get install python3-venv
- OK cargo: `cargo 1.72.0 (103a7ff2e 2023-08-15)`
- OK Go: `go version go1.21.1 windows/amd64`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 1. Remaining: 59. Limit: 60. Reset: 21-09-2023 19:34:37.
  Install and authenticate via gh-cli to increase rate limit.
```

### Screenshots or recordings

![image](https://github.com/williamboman/mason.nvim/assets/37153467/52ba4ff6-5f3e-4692-963a-6e2d624707ec)

**Comment by jmwielandt** [comment]
https://github.com/mason-org/mason-registry/pull/1641

maybe what should be installing is https://github.com/pest-parser/pest.vim ?

checkout the vim section at https://github.com/pest-parser/pest-ide-tools ' readme

**Comment by Jamalam360** [comment]
LS mainter here (although _not_ involved with pest.vim itself)

I believe the vim plugin is waiting on a tree sitter grammar for syntax highlighting

**Comment by Samyak2** [comment]
Mason only installs the LS. Syntax highlighting and filetype detection are provided by [pest.vim](https://github.com/pest-parser/pest.vim) (which also means that the LS won't activate since it doesn't detect the .pest file type).

**Comment by jmwielandt** [comment]
oh, something i forgot to mention. if i set the pest filetype with :set
filetype=pest, the lsp starts working but syntax highlight doesn't.

**Comment by Jamalam360** [comment]
Alright @Samyak2, thanks for the info.

Does anyone know if there's something in Mason to suggest installing an extension alongside the LSP or something? That's just my guess from a vscode brain who's never used vim.

The instructions on the LSP repo can also be improved.

**Comment by williamboman** [comment]
What @Samyak2 said above!

**Comment by williamboman** [comment]
> Does anyone know if there's something in Mason to suggest installing an extension alongside the LSP or something? That's just my guess from a vscode brain who's never used vim.

Neovim extensions (plugins) aren't handled by Mason (yet), you'll want something like lazy.nvim for that.
