### ISSUE TITLE
Gems need to to also exist in GEM_PATH

### ISSUE THREAD

**Issue by williamboman** [williamboman/mason.nvim#152]
Gems installed with mason.nvim will be installed into a different `GEM_HOME`, and into a location that most definitely doesn't exist on `GEM_PATH` by default. This results in the Ruby runtime being unable to locate these gems.

**Comment by dbernheisel** [comment]
Linking #144 and #148 since this solution will likely fix errors I encountered while testing adding these linters.

**Comment by williamboman** [comment]
Fixed in #202
