### ISSUE TITLE
jdtls installed with mason spwan error on windows system

### ISSUE THREAD

**Issue by dragove** [williamboman/mason.nvim#1528]
### I've searched open issues for similar requests

- [X] Yes

### I've manually reviewed logs to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

I'm on windows.

After install jdtls, I'm not able to config jdtls.nvim with cmd = { "jdtls" } and got following error message:

```
Spawning language server with cmd: `jdtls` failed. The language server is either not installed, missing from PATH, or not executable.
```

However, I'm able to run `jdtls` command in neovim's builtin ":term" and I can find the `PATH` variable is containg the mason bin path. I'm not sure what's wrong here.

I also tested my config with  WSL2, and it works fine under wsl2.

### Expected behavior

jdtls runs with no issue

### Steps to reproduce

1. install `jdtls` with mason
2. config `jdtls.nvim` with `cmd={ 'jdtls' }`

### Affected packages

jdtls

### Neovim version (>= 0.7)

NVIM v0.10.0-dev-bb38c06
Build type: RelWithDebInfo
LuaJIT 2.1.1693350652

### Operating system/version

Windows_NT M-0322031370 10.0 22621 x86_64 MS/Windows (Windows 11)

### Healthcheck

```Text
==============================================================================
mason: require("mason.health").check()

mason.nvim ~
- OK mason.nvim version v1.8.1
- OK PATH: prepend
- OK Providers: 
    mason.providers.registry-api
    mason.providers.client
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- OK Registry `github.com/mason-org/mason-registry version: 2023-10-17-junior-jelly` is installed.

mason.nvim [Core utils] ~
- WARNING unzip: not available
  - ADVICE:
    - spawn: unzip failed with exit code - and signal -. unzip is not executable
- WARNING wget: not available
  - ADVICE:
    - spawn: wget failed with exit code - and signal -. wget is not executable
- OK curl: `curl 8.0.1 (Windows) libcurl/8.0.1 Schannel WinIDN
`
- WARNING gzip: not available
  - ADVICE:
    - spawn: gzip failed with exit code - and signal -. gzip is not executable
- OK tar: `bsdtar 3.6.2 - libarchive 3.6.2 zlib/1.2.5.f-ipp liblzma/5.2.5 bz2lib/1.0.8 libzstd/1.5.4 
`
- OK pwsh: `7.3.8 Microsoft Windows 10.0.22621 Win32NT
`
- OK 7z: `7-Zip 23.01 (x64) : Copyright (c) 1999-2023 Igor Pavlov : 2023-06-20
`

mason.nvim [Languages] ~
- WARNING luarocks: not available
  - ADVICE:
    - spawn: luarocks failed with exit code - and signal -. luarocks is not executable
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer.bat failed with exit code - and signal -. composer.bat is not executable
- WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. php is not executable
- WARNING Ruby: not available
  - ADVICE:
    - spawn: ruby failed with exit code - and signal -. ruby is not executable
- WARNING RubyGem: not available
  - ADVICE:
    - spawn: gem.cmd failed with exit code - and signal -. gem.cmd is not executable
- OK Go: `go version go1.21.3 windows/amd64`
- OK node: `v18.18.2
`
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- OK cargo: `cargo 1.69.0 (6e9a83356 2023-04-12)`
- OK python: `Python 3.12.0
`
- OK java: `openjdk version "17.0.8.1" 2023-08-24 LTS
`
- OK JAVA_HOME: `openjdk version "17.0.8.1" 2023-08-24 LTS
`
- OK javac: `javac 17.0.8.1
`
- OK pip: `pip 23.2.1 from C:\Users\jingchun\scoop\apps\python\current\Lib\site-packages\pip (python 3.12)

`
- OK python venv: `Ok`
- OK npm: `9.8.1`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 3. Remaining: 57. Limit: 60. Reset: 2023/10/17 13:33:52.
  Install and authenticate via gh-cli to increase rate limit.
```

**Comment by dragove** [comment]
I think it is on my configuration side, since it works if I remove nvim-jdtls

**Comment by williamboman** [comment]
Try `cmd = vim.fn.exepath("jdtls")`. Libuv (which Neovim uses) is unable to find `.cmd` scripts in PATH when spawning processes on Windows. Using `vim.fn.exepath` will produce an absolute path to the `jdtls.cmd` executable provided by Mason

**Comment by dragove** [comment]
> Try `cmd = vim.fn.exepath("jdtls")`. Libuv (which Neovim uses) is unable to find `.cmd` scripts in PATH when spawning processes on Windows. Using `vim.fn.exepath` will produce an absolute path to the `jdtls.cmd` executable provided by Mason

Wow, Thanks, this works for me
