### ISSUE TITLE
feat(ui): Delete Whitespaces in Blankline

### ISSUE THREAD

**Issue by pysan3** [williamboman/mason.nvim#1529]
### I've searched open issues for similar requests

- [X] Yes

### Is your feature request related to a problem? Please describe.

First of all, thanks for the plugin. I am having amazing experience so far but got a very minor hiccup.

I would like to quickly move the cursor to the `Available` section.
I believe the fastest way would be to use the `}` keybind to move down a paragraph, but since there are whitespaces between the `Installed` section, I cannot move between the sections easily.

As you can see, there are whitespaces (highlighted in red) above the `Available` section which does not make it a separate paragraph.
![image](https://github.com/williamboman/mason.nvim/assets/41065736/63b04148-65a8-47ad-b199-b2f97191b556)

### Describe the solution you'd like

It would be nice if there were no whitespaces in the blankline between the sections.

Or, another solution would be to add a specific keybind (e.g. `[[`, `]]`) to jump to the next section.

### Describe potential alternatives you've considered

I believe changing some code near this part (or inside `get_styles`) so that `indentation` is not added if `line:len() == 0` or something similar to that would be a possible fix.
But I was hesitant to submit a PR becuz this method might rather be a _hack_ and there might be a better and more elegant way to solve the issue.

https://github.com/williamboman/mason.nvim/blob/cd7835b15f5a4204fc37e0aa739347472121a54c/lua/mason-core/ui/display.lua#L122-L133

**Comment by WillLillis** [comment]
I'd also find this change very useful! 😃 I'm happy to open a PR, but won't do so yet as the "scope and acceptance criteria are agreed upon with project maintainers before implementation" condition from `CONTRIBUTING.md` hasn't been established yet. As mentioned in the issue, could this be implemented with the following simple change from: https://github.com/williamboman/mason.nvim/blob/cd7835b15f5a4204fc37e0aa739347472121a54c/lua/mason-core/ui/display.lua#L124-L133

to:

```lua
  -- apply indentation to non-empty lines
  if string.len(full_line) > 0 then
      full_line = (" "):rep(active_styles.indentation) .. full_line
      for j = 1, #line_highlights do
          local highlight = line_highlights[j]
          highlight.col_start = highlight.col_start + active_styles.indentation
          highlight.col_end = highlight.col_end + active_styles.indentation
          output.highlights[#output.highlights + 1] = highlight
      end
  end
  
  output.lines[#output.lines + 1] = full_line
```

**Comment by pysan3** [comment]
> I'm happy to open a PR, but won't do so yet as the "scope and acceptance criteria are agreed upon with project maintainers before implementation" condition from CONTRIBUTING.md hasn't been established yet.

I think this is fulfilled when the PR is accepted, so I think you are free to submit a PR. If they don't agree with adding this feature, they will just deny the PR.

I'd love to see this feature being implemented so I'd be happy if you could submit a PR with the code above, tho I'm not able to test as I don't have much free time now.

**Comment by WillLillis** [comment]
It's working as far as I can tell, so I'll open a PR :)

**Comment by williamboman** [comment]
Thanks @pysan3 for reporting and providing a fix, I forgot to attribute the change to you as well. (and sorry for not responding earlier, huge backlog)

**Comment by pysan3** [comment]
Thanks for merging the PR @williamboman ! Keep up with your hard work.
