### ISSUE TITLE
[New package]: Dart LS and formatter

### ISSUE THREAD

**Issue by StevenJPx2** [williamboman/mason.nvim#156]
### Package name

dartls, dart_format

### Package homepage

https://github.com/dart-lang/sdk/tree/master/pkg/analysis_server/tool/lsp_spec, 

### Languages

dart

**Comment by williambotman** [comment]
Hello! Cool! Pull requests are always very welcomed to add new packages. If the distribution of the
package is simple, the installation will most likely be so as well (existing package installers may be
used for reference!). Otherwise, @williamboman will get around to looking into this ASAP!

**Comment by williamboman** [comment]
Hello! This was requested the other day: https://github.com/williamboman/mason.nvim/issues/136#issuecomment-1193913116

These things come bundled with the Dart executable. Don’t you have it installed? Or is there some other reason you’d like it to be available via Mason?

**Comment by StevenJPx2** [comment]
Formatting and linting works. However I'm not able to do do any code actions, get diagnostics, type info and such using `vim.lsp` because I don't have dart-ls.

**Comment by br1anchen** [comment]
@StevenJPx2 I am currently using both `williamboman/mason.nvim` and `williamboman/mason-lspconfig.nvim` in my config to bridge the lsp name differences between `mason` and `lspconfig`.
Are you sure that you called `lspconfig.dartls.setup()` in your config? I have all `vim.lsp` available in `dart` filetype buffer with `dart` installed in my environment. I do not think there is anything `mason` can provide in this case since language server, formatter, linter are all from `dart` itself.

**Comment by williamboman** [comment]
> because I don't have dart-ls.

I'm not sure I follow what dart-ls is? Here's for example the command lspconfig provides for the dart language server: https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/dartls.lua#L5

**Comment by StevenJPx2** [comment]
> @StevenJPx2 I am currently using both `williamboman/mason.nvim` and `williamboman/mason-lspconfig.nvim` in my config to bridge the lsp name differences between `mason` and `lspconfig`. Are you sure that you called `lspconfig.dartls.setup()` in your config? I have all `vim.lsp` available in `dart` filetype buffer with `dart` installed in my environment. I do not think there is anything `mason` can provide in this case since language server, formatter, linter are all from `dart` itself.

AAAh. Never needed to do this for nvim-lsp-installer, so I didn't set it up. But it works now. But to your other point, [nvim-lsp-installer](https://github.com/williamboman/nvim-lsp-installer) did have the server for dart lsp.

**Comment by br1anchen** [comment]
Yeah, `dartls` is only registry for `dart` lsp in `nvim-lsp-installer` [here](https://github.com/williamboman/nvim-lsp-installer/blob/main/lua/nvim-lsp-installer/servers/dartls/init.lua#L10). Technically it only checks if `dart` is installed in the environment or not.

**Comment by StevenJPx2** [comment]
Okay but for me, I'm getting two dart lsp clients in one buffer, both with @br1anchen's solution and using nvim-lsp-installer. How do I fix that?

**Comment by williamboman** [comment]
> But to your other point, nvim-lsp-installer did have the server for dart lsp.

Ah I forgot about this. I remember deciding to remove it because of reasons I mentioned in the other comment I linked to. I am however a bit incosistent with this as `deno` exists as a package (they have the exact same approach).

**Comment by realitymolder** [comment]
> 

I'm not sure if I understand. Tried to use the LSPconfig + Mason (for other LSP support) still don't get any support in my files.
