### ISSUE TITLE
Language filter is opening the list in more and I am unable to select one

### ISSUE THREAD

**Issue by RoryNesbitt** [williamboman/mason.nvim#158]
### Problem description

When looking at the installation page and hitting `<C-f>` I get a list of all the languages displayed in more
Since more doesn't provide much other than paging when I try to enter a number it thinks I've forgot where my arrows are

### Neovim version (>= 0.7)

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

### Operating system/version

Linux Triss 5.18.11-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 12 Jul 2022 15:40:51 +0000 x86_64 GNU/Linux

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Affected packages

all

### Actual behavior

Language list opens in more

### Expected behavior

Language list opens in something that would let me select one.
Sorry I can't provide more, I'm not exactly sure what the language filter code should be calling

### Healthcheck output

```shell
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - WARNING: **Go**: not available
  - OK: **cargo**: `cargo 1.62.0`
  - OK: **luarocks**: `/usr/bin/luarocks 3.9.0`
  - OK: **Ruby**: `ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux]`
  - OK: **RubyGem**: `3.3.15`
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.14.0`
  - OK: **node**: `v16.16.0`
  - OK: **python3**: `Python 3.10.5`
  - OK: **pip3**: `pip 22.1.2 from /usr/lib/python3.10/site-packages/pip (python 3.10)`
  - OK: **javac**: `javac 18.0.1.1`
  - OK: **java**: `Picked up _JAVA_OPTIONS: -Djava.util.prefs.userRoot=/home/rory/.config/java`
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: **curl**: `curl 7.84.0 (x86_64-pc-linux-gnu) libcurl/7.84.0 OpenSSL/1.1.1q zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.48.0`
  - OK: **gzip**: `gzip 1.12`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: Tue 26 Jul 2022 15:32:33 BST.
```

**Comment by RoryNesbitt** [comment]
So I see now that once scrolling to the bottom the selection can then be entered, I am just hasty and dumb

That being said I don't like the setup and hopefully a future version can provide a nicer input, but for just now it would be better to use less than more so we can search with `/`

**Comment by williamboman** [comment]
The language filter uses `:h vim.ui.select()` to prompt for a selection. What you describe sounds like the default behaviour, which can be a bit awkward with many options. I personally use dressing.nvim for nicer vim.ui interfaces

**Comment by RoryNesbitt** [comment]
Hey that's a great tip, thanks
