### ISSUE TITLE
Failed to update registries: GitHubRegistrySource(repo=mason-org/mason-registry) failed to install: Failed to download registry archive

### ISSUE THREAD

**Issue by thecode-master-sy** [williamboman/mason.nvim#1603]
### I've searched open issues for similar requests

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

mason.nvim is failing to install registries, even when i run `:MasonUpdate` or C as the prompt say i still get the above error.

see what shows when i run `:CheckHealth mason`

`mason: require("mason.health").check()

mason.nvim ~
- OK mason.nvim version v1.9.0
- OK PATH: prepend
- OK Providers: 
  mason.providers.registry-api
  mason.providers.client
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- ERROR Registry `github.com/mason-org/mason-registry [uninstalled]` is not installed.
  - ADVICE:
    - Run :MasonUpdate to install.

mason.nvim [Core utils] ~
- WARNING unzip: not available
  - ADVICE:
    - spawn: unzip failed with exit code - and signal -. unzip is not executable
- OK wget: `GNU Wget 1.21.4 built on mingw32.
`
- OK curl: `curl 8.4.0 (Windows) libcurl/8.4.0 Schannel WinIDN
`
- WARNING gzip: not available
  - ADVICE:
    - spawn: gzip failed with exit code - and signal -. gzip is not executable
- OK tar: `bsdtar 3.5.2 - libarchive 3.5.2 zlib/1.2.5.f-ipp 
`
- OK pwsh: `7.4.1 Microsoft Windows 10.0.19045 Win32NT
`
- WARNING 7z: not available
  - ADVICE:
    - spawn: 7z failed with exit code - and signal -. 7z is not executable

mason.nvim [Languages] ~
- WARNING Go: not available
  - ADVICE:
    - spawn: go failed with exit code - and signal -. go is not executable
- WARNING cargo: not available
  - ADVICE:
    - spawn: cargo failed with exit code - and signal -. cargo is not executable
- WARNING luarocks: not available
  - ADVICE:
    - spawn: luarocks failed with exit code - and signal -. luarocks is not executable
- WARNING Ruby: not available
  - ADVICE:
    - spawn: ruby failed with exit code - and signal -. ruby is not executable
- WARNING RubyGem: not available
  - ADVICE:
    - spawn: gem.cmd failed with exit code - and signal -. gem.cmd is not executable
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer.bat failed with exit code - and signal -. composer.bat is not executable
- WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. php is not executable
- WARNING javac: not available
  - ADVICE:
    - spawn: javac failed with exit code - and signal -. javac is not executable
- WARNING java: not available
  - ADVICE:
    - spawn: java failed with exit code - and signal -. java is not executable
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- WARNING python: not available
  - ADVICE:
    - spawn: python failed with exit code - and signal -. python is not executable
- WARNING pip: not available
  - ADVICE:
    - spawn: python failed with exit code - and signal -. python is not executable
- WARNING python venv: not available
  - ADVICE:
    - On Debian/Ubuntu systems, you need to install the python3-venv package using the following command:
      
      apt-get install python3-venv
- OK node: `v20.11.0
`
- OK npm: `10.2.4`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: 1/19/2024 2:35:08 PM.
  Install and authenticate via gh-cli to increase rate limit.
`
i am unable to tell what actually is the cause of this issue, i have curl and wget installed.

### Expected behavior

mason.nvim to successfully install registries without any errors

### Affected packages

all

### Mason output

```Text
Registry installation failed with the following error:
    GitHubRegistrySource(repo=mason-org/mason-registry) failed to install: Failed to download registry archive.
```

### Installation log

```Text
[ERROR 1/17/2024 12:04:12 PM] ...ta/lazy/mason.nvim/lua/mason-registry/sources/github.lua:146: Failed to install registry GitHubRegistrySource(repo=mason-org/mason-registry). "Failed to download registry archive."
```

### Neovim version (>= 0.7)

NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1703942320

### Operating system/version

Windows 10 pro/10.0.19045 build 19045

### Healthcheck

```Text
mason.nvim ~
- OK mason.nvim version v1.9.0
- OK PATH: prepend
- OK Providers: 
  mason.providers.registry-api
  mason.providers.client
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- ERROR Registry `github.com/mason-org/mason-registry [uninstalled]` is not installed.
  - ADVICE:
    - Run :MasonUpdate to install.

mason.nvim [Core utils] ~
- WARNING unzip: not available
  - ADVICE:
    - spawn: unzip failed with exit code - and signal -. unzip is not executable
- OK wget: `GNU Wget 1.21.4 built on mingw32.
`
- OK curl: `curl 8.4.0 (Windows) libcurl/8.4.0 Schannel WinIDN
`
- WARNING gzip: not available
  - ADVICE:
    - spawn: gzip failed with exit code - and signal -. gzip is not executable
- OK tar: `bsdtar 3.5.2 - libarchive 3.5.2 zlib/1.2.5.f-ipp 
`
- OK pwsh: `7.4.1 Microsoft Windows 10.0.19045 Win32NT
`
- WARNING 7z: not available
  - ADVICE:
    - spawn: 7z failed with exit code - and signal -. 7z is not executable

mason.nvim [Languages] ~
- WARNING Go: not available
  - ADVICE:
    - spawn: go failed with exit code - and signal -. go is not executable
- WARNING cargo: not available
  - ADVICE:
    - spawn: cargo failed with exit code - and signal -. cargo is not executable
- WARNING luarocks: not available
  - ADVICE:
    - spawn: luarocks failed with exit code - and signal -. luarocks is not executable
- WARNING Ruby: not available
  - ADVICE:
    - spawn: ruby failed with exit code - and signal -. ruby is not executable
- WARNING RubyGem: not available
  - ADVICE:
    - spawn: gem.cmd failed with exit code - and signal -. gem.cmd is not executable
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer.bat failed with exit code - and signal -. composer.bat is not executable
- WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. php is not executable
- WARNING javac: not available
  - ADVICE:
    - spawn: javac failed with exit code - and signal -. javac is not executable
- WARNING java: not available
  - ADVICE:
    - spawn: java failed with exit code - and signal -. java is not executable
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- WARNING python: not available
  - ADVICE:
    - spawn: python failed with exit code - and signal -. python is not executable
- WARNING pip: not available
  - ADVICE:
    - spawn: python failed with exit code - and signal -. python is not executable
- WARNING python venv: not available
  - ADVICE:
    - On Debian/Ubuntu systems, you need to install the python3-venv package using the following command:
      
      apt-get install python3-venv
- OK node: `v20.11.0
`
- OK npm: `10.2.4`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: 1/19/2024 2:35:08 PM.
  Install and authenticate via gh-cli to increase rate limit.
```

**Comment by vladdoster** [comment]
@thecode-master-sy,

The provided stack-trace clearly describes the issue.

> - WARNING unzip: not available 
> - WARNING 7z: not available
> - WARNING gzip: not available

See [requirements in README.md](https://github.com/williamboman/mason.nvim?tab=readme-ov-file#requirements)

**Comment by tydra-wang** [comment]
Got a same error but `:checkhealth mason` shows `Core Utils` OK.

```

==============================================================================
mason: require("mason.health").check()

mason.nvim ~
- OK mason.nvim version v1.10.0
- OK PATH: prepend
- OK Providers: 
  mason.providers.registry-api
  mason.providers.client
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- OK Registry `github.com/mason-org/mason-registry version: 2024-01-25-strong-salad` is installed.

mason.nvim [Core utils] ~
- OK unzip: `UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send`
- OK wget: `GNU Wget 1.24.5 built on darwin23.2.0.`
- OK curl: `curl 8.4.0 (x86_64-apple-darwin23.0) libcurl/8.4.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.58.0`
- OK gzip: `Apple gzip 428`
- OK gtar: `tar (GNU tar) 1.35`
- OK bash: `GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23)`
- OK sh: `Ok`

mason.nvim [Languages] ~
- OK Ruby: `ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin23]`
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer failed with exit code - and signal -. composer is not executable
- WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. php is not executable
- OK Go: `go version go1.22.0 darwin/arm64`
- OK cargo: `cargo 1.74.0`
- OK node: `v21.7.1`
- OK luarocks: `/opt/homebrew/bin/luarocks 3.9.2`
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- OK RubyGem: `3.0.3.1`
- OK python: `Python 3.9.6`
- OK java: `openjdk version "21.0.2" 2024-01-16`
- OK javac: `javac 21.0.2`
- OK npm: `10.5.0`
- OK pip: `pip 21.2.4 from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/pip (python 3.9)`
- OK python venv: `Ok`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: Mon Mar 25 18:47:19 2024.
  Install and authenticate via gh-cli to increase rate limit.


```

**Comment by Samy-33** [comment]
Facing the same issue.

**Comment by tydra-wang** [comment]
I found out my issue was due to a permission problem. The existing file ~/.local/share/nvim/mason/registries/github/mason-org/mason-registry/registry.json.zip is owned by root, for reasons unknown. Deleting registry.json.zip fixed it.

**Comment by Samy-33** [comment]
I confirm that `~/.local/share/nvim/mason/registries/github/mason-org/mason-registry/registry.json.zip` is owned by root and updating the owner to the current user fixed the issue as well.

**Comment by nfgferreira** [comment]
Same error here, but the said file is not root's.

**Comment by notno** [comment]
Ditto for me. Core apps ok, zip file permissions ok, also behind a corporate network.

**Comment by jrschenk** [comment]
I'm using the NVIM nightly build and after updating this morning the error occurred. checkhealth shows that the core utilities are not available. I was able to track the error to the nvim commit c5af5c0b which has something to do with faster vim.deprecate().  Maybe this helps.

**Comment by Tainted-Fool** [comment]
@jrschenk i was experiencing this problem and your solution solved my issue. I had to switch nvim commit to `git checkout a4fc3bb0e` and then rebuild it

**Comment by cleong14** [comment]
Tested and confirmed nightly build has been fixed thanks to commit `1294е22`.

**Comment by thecode-master-sy** [comment]
seems like this issue has been resolved

**Comment by krishgoblin** [comment]
> @thecode-master-sy,
> 
> The provided stack-trace clearly describes the issue.
> 
> > * WARNING unzip: not available
> > * WARNING 7z: not available
> > * WARNING gzip: not available
> 
> See [requirements in README.md](https://github.com/williamboman/mason.nvim?tab=readme-ov-file#requirements)

This solution worked for me. I installed the required dependencies and viola.

**Comment by codestantine** [comment]
Faced the same issue just now. And I changed the owner of that registry file to current owner and it got fixed.
