### ISSUE TITLE
Add Jinja-lsp support

### ISSUE THREAD

**Issue by palandovalex** [williamboman/mason.nvim#1636]
### I've searched open issues for similar requests

- [x] Yes

### Is your feature request related to a problem? Please describe.

Theare new lsp for jinja templates:

https://github.com/uros-5/jinja-lsp

### Describe the solution you'd like

may bee it will be like this:
```json
  {
    "name": "jinja-lsp",
    "description": "Experimental jinja lsp server, with autocomplete, syntax highlighting, hover, goto definition, code actions and linting.", 
    "homepage": "https://github.com/uros-5/jinja-lsp",
    "licenses": [
      "MIT"
    ],
    "languages": [
      "Django",
      "Jinja",
      "Nunjucks",
    ],
    "categories": [
      "LSP", 
      "Linter",
      "Compiler"
    ],
    "source": {
      "id": "pkg:cargo/jinja-lsp@0.1.4"
    },
    "bin": {
      "jinja-lsp": "cargo:jinja-lsp"
    }
  },
```

**Comment by benedikt-bartscher** [comment]
@palandovalex   
https://github.com/mason-org/mason-registry/pull/4895  
https://github.com/williamboman/mason-lspconfig.nvim/pull/375
https://github.com/neovim/nvim-lspconfig/pull/3069

**Comment by holmanb** [comment]
I think this can be closed as completed.
