### ISSUE TITLE
Cursor position is being inherited

### ISSUE THREAD

**Issue by luetage** [williamboman/mason.nvim#175]
### Problem description

Reproduce

* Open mason interface
* In `All` search `/gotests` and confirm
* Switch tabs from 1 to 5 and back

### Neovim version (>= 0.7)

NVIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system/version

Fedora 36

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Affected packages

all

### Actual behavior

Visiting the next tab (LSP) seems to inherit the row/cursor position, but at the third tab there is nowhere to go to and we are on the top screen with cursor positioned in the middle. Going to tab 5 and back to 1 we will be at the first screen of “All” once more.

### Expected behavior

Either we should start out on top whenever we switch tabs, or when first visiting a tab we should be on top and on a subsequent visit at the previous position. Right now it’s a little confusing.

### Healthcheck output

```shell
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - WARNING: **Go**: not available
  - OK: **cargo**: `cargo 1.62.1 (a748cf5a3 2022-06-08)`
  - WARNING: **luarocks**: not available
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.12.1`
  - OK: **node**: `v16.14.0`
  - OK: **python3**: `Python 3.10.5`
  - OK: **pip3**: `pip 21.3.1 from /usr/lib/python3.10/site-packages/pip (python 3.10)`
  - WARNING: **javac**: not available
  - OK: **java**: `openjdk version "17.0.3" 2022-04-19`
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: **curl**: `curl 7.82.0 (x86_64-redhat-linux-gnu) libcurl/7.82.0 OpenSSL/3.0.5 zlib/1.2.11 brotli/1.0.9 libidn2/2.3.3 libpsl/0.21.1 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.46.0 OpenLDAP/2.6.2`
  - OK: **gzip**: `gzip 1.11`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-redhat-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: **python3_host_prog**: `Python 3.10.5`
  - OK: GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: Do 28 Jul 2022 00:57:59.
```

**Comment by williamboman** [comment]
Hello! Yeah I think it'd make sense to reset the cursor when switching tabs, #178
