### ISSUE TITLE
Pwsh not available

### ISSUE THREAD

**Issue by steven-na** [williamboman/mason.nvim#1769]
### I've searched open issues for similar requests

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

When I run `:checkhealth mason` i get the error:
```
1 - ERROR pwsh: not available
2   - ADVICE:
3     - spawn: pwsh failed with exit code 2147516546 and signal 0. Failed to load the dll from [C:\ProgramFiles\WindowsApps\Microsoft.PowerShell_7.4.4.0_x64__8wekyb3d8bbwe\hostfxr.dll], HRESULT: 0x80070005^M
4       The library hostfxr.dll was found, but loading it from C:\Files\WindowsApps\Microsoft.PowerShell_7.4.4.0_x64__8wekyb3d8bbwe\hostfxr.dll failed^M
5         - Installing .NET prerequisites might help resolve this problem.^M
6            https://go.microsoft.com/fwlink/?linkid=798306^M
  ```

I am running Nvim in powershell, so i know that the program works. I have installed all relevant .net dependencies as the error message said to.

### Expected behavior

It should recognize powershell

### Steps to reproduce

1. Open Nvim
2. Run `:checkhealth mason`

### Neovim version (>= 0.7)

NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713484068

### Operating system/version

Windows 11 Pro 23H2 22631.3880

### Healthcheck output

```shell
1 - ERROR pwsh: not available
2   - ADVICE:
3     - spawn: pwsh failed with exit code 2147516546 and signal 0. Failed to load the dll from [C:\Program Files\WindowsApps\Microsoft.PowerShell_7.4.4.0_x64__8wekyb3d8bbwe\hostfxr.dll], HRESULT: 0x80070005^M
4       The library hostfxr.dll was found, but loading it from C:\Program Files\WindowsApps\Microsoft.PowerShell_7.4.4.0_x64__8wekyb3d8bbwe\hostfxr.dllfailed^M
5         - Installing .NET prerequisites might help resolve this problem.^M
6            https://go.microsoft.com/fwlink/?linkid=798306^M
```
```


### Screenshots

Same error when installing stylua
![image](https://github.com/user-attachments/assets/8d91b805-e642-4715-93e7-0d0917fa94ed)

**Comment by steven-na** [comment]
The only previous mention I can find of the exit code `2147516546` is [this github issue from 2018](https://github.com/microsoft/live-share/issues/1195). The fix for this issue is installing some security fix that was discontinued with Windows 7.

**Comment by steven-na** [comment]
I solved this problem by uninstalled the Microsoft store version of PowerShell 7 and re-installing it through winget.

**Comment by Travia21** [comment]
In case anyone in the future is googling Mason hostfxr.dll, this is the solution.

Be careful when reinstalling using winget to specifically use "Microsoft.PowerShell", ie `winget install Microsoft.PowerShell`
