### ISSUE TITLE
No available packages 

### ISSUE THREAD

**Issue by nippi05** [williamboman/mason.nvim#1779]
### I've searched open issues for similar requests

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

No available packages, when :checkhealth mason is run it does stalls the terminal and when I press Ctrl-c it results in a promise not resolve on time error.

### Expected behavior

Packages showing up and healthcheck working

### Steps to reproduce

1. Build nightly version OR latest stable release of neovim on debian
2. Use _either_  lazyvim or nvchad setup
3. Attempt to use mason

### Neovim version (>= 0.7)

NVIM v0.11.0-dev-680+g4353996d0
Build type: RelWithDebInfo
LuaJIT 2.1.1724512491
Run "nvim -V1 -v" for more info

### Operating system/version

Linux tkpad 6.1.0-23-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64 GNU/Linux

### Healthcheck output

```shell
Stalls indefinitely, pressing Ctrl-c gives this result

mason: require("mason.health").check()

mason.nvim ~
- ERROR Failed to run healthcheck for "mason" plugin. Exception:
  ...j/.local/share/nvim/lazy/mason.nvim/lua/mason/health.lua:315: async function failed to resolve in time.
```

### Screenshots

![image](https://github.com/user-attachments/assets/82c0c518-5050-4443-9b21-66db5ff006ab)
![image](https://github.com/user-attachments/assets/b8746b6b-beb8-4fb1-9965-c6f0e1bda015)

**Comment by AlphaTechnolog** [comment]
having same issue here

**Comment by AlphaTechnolog** [comment]
even `MasonUpdate` keeps hanging

**Comment by mwojtyna** [comment]
Same here

version:
```
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1723675123
Run "nvim -V1 -v" for more info
```

Tried with my custom config and AstroNvim and in both cases the behaviour is the same as reported here.

**Comment by mwojtyna** [comment]
I think I found the issue. Mason's web api, which is used to check for updates to packages, is hosted on vercel. It seems like my ISP has erroneously banned it or something, because `vercel.com` never loads for me, same with any website hosted on vercel like `uploadthing.com`. Can anyone here confirm if vercel is working for them?

**Comment by nippi05** [comment]
> I think I found the issue. Mason's web api, which is used to check for updates to packages, is hosted on vercel. Output of `dig api.mason-registry.dev`:
> 
> ```
> ;; ANSWER SECTION:
> api.mason-registry.dev. 3342    IN      CNAME   cname.vercel-dns.com.
> cname.vercel-dns.com.   972     IN      A       76.76.21.241
> cname.vercel-dns.com.   972     IN      A       76.76.21.142
> ```
> 
> It seems like my ISP has erroneously banned vercel or something, because `vercel.com` never loads for me, same with any website hosted on vercel like `uploadthing.com`. Can anyone here confirm if vercel is working for them?

Yep, this is it! My universities student website wasn't working either I guess they vercel or some derivative of it.
