### ISSUE TITLE
Command `MasonInstallAll` not found after loading `mason.nvim`

### ISSUE THREAD

**Issue by firashacker** [williamboman/mason.nvim#1805]
### I've searched open issues for similar requests

- [X] Yes

### I've manually reviewed logs to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

Command `MasonInstallAll` not found after loading `mason.nvim`

### Expected behavior

installing my ensureinstalled packages

### Steps to reproduce

use nvchad starter config
setup mason
add some deppendencies
run MasonInsyallAll

# NOTE
previews versions worked fine it broke after update

### Affected packages

mason

### Neovim version (>= 0.7)

`NVIM v0.10.1 
Build type: RelWithDebInfo 
LuaJIT 2.1.1725453128 
Run "nvim -V1 -v" for more info `

### Operating system/version

ArchLinux

### Healthcheck

```Text
mason: 

- ERROR No healthcheck found for "mason" plugin.
```

**Comment by siduck** [comment]
this plugin has no such command. thats nvchad command. please close the issue

**Comment by firashacker** [comment]
ok mate thanks for you help and sorry for this issue

**Comment by siduck** [comment]
read this thread for more info https://github.com/williamboman/mason.nvim/discussions/1795
