### ISSUE TITLE
Adding Vscode-java-decompiler

### ISSUE THREAD

**Issue by jayp0521** [williamboman/mason.nvim#193]
### Package name

Vscode-java-decompiler

### Package homepage

https://github.com/dgileadi/vscode-java-decompiler

### Languages

Java

### How is this package distributed?

Github

Hello, 

I don't know if this package would be allowed to install. It doesn't seem to fit any of the categories on the homepage. I do think most would want it, or some flavor of a decompiler for Java. Please let me know your thoughts

**Comment by williambotman** [comment]
Hello! Pull requests are always very welcomed to add new packages. If the distribution of the package is simple, the installation will most likely be so as well. See [CONTRIBUTING.md](https://github.com/williamboman/mason.nvim/blob/main/CONTRIBUTING.md) and the [API reference](https://github.com/williamboman/mason.nvim/blob/main/doc/reference.md) for more details! You may also use existing packages as reference.

**Comment by jayp0521** [comment]
Yep, I will look into creating a pull request based on the rules. Thank you

**Comment by williamboman** [comment]
Hey @jayp0521 ! At first glance this looks like a tool that is pretty deeply integrated with VSCode, and depends on another VSCode extension. I'd be open to repackaging it in Mason if it's possible, but I feel like it'll eventually require a dedicated Neovim wrapper (external to Mason) to be usable
