### ISSUE TITLE
some language servers installation failed

### ISSUE THREAD

**Issue by zhang-stephen** [williamboman/mason.nvim#194]
### Problem description

1. json-lsp installation failed
2. taplo(toml-language-server) compilation failed. Why not download the pre-compiled binary from the repo?

### Neovim version (>= 0.7)

```
NVIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -fcommon -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/abuild/rpmbuild/BUILD/neovim-0.7.2/build/config -I/home/abuild/rpmbuild/BUILD/neovim-0.7.2/src -I/usr/include -I/home/abuild/rpmbuild/BUILD/neovim-0.7.2/build/src/nvim/auto -I/home/abuild/rpmbuild/BUILD/neovim-0.7.2/build/include
Compiled by abuild@OBS

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Operating system/version

Linux localhost 5.18.11-1-default #1 SMP PREEMPT_DYNAMIC Fri Jul 15 05:36:11 UTC 2022 (4fcb983) x86_64 x86_64 x86_64 GNU/Linux

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Affected packages

json-lsp, toml-language-server

### Actual behavior

installation failed.

### Expected behavior

all servers installation completed.

### Mason output

```Text
see the screenshot.
```

### Installation log

```Text
see the log url.
```

### Healthcheck

```Text
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - WARNING: Go: not available
  - OK: cargo: `cargo 1.61.0`
  - OK: luarocks: `/usr/bin/luarocks 3.8.0`
  - OK: Ruby: `ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-gnu]`
  - OK: RubyGem: `3.3.7`
  - WARNING: Composer: not available
  - WARNING: PHP: not available
  - OK: npm: `8.5.2`
  - OK: node: `v17.7.1`
  - OK: python3: `Python 3.10.5`
  - OK: pip3: `pip 22.0.4 from /usr/lib/python3.10/site-packages/pip (python 3.10)`
  - WARNING: javac: not available
  - WARNING: java: not available
  - WARNING: julia: not available
  - OK: wget: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: curl: `curl 7.83.1 (x86_64-suse-linux-gnu) libcurl/7.83.1 OpenSSL/1.1.1q-fips zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.3 libpsl/0.21.1 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.48.0 OpenLDAP/2.6.2`
  - OK: gzip: `gzip 1.12`
  - OK: tar: `tar (GNU tar) 1.34`
  - OK: bash: `GNU bash, version 5.1.16(1)-release (x86_64-suse-linux)`
  - OK: sh: `Ok`
  - OK: GitHub API rate limit. Used: 9. Remaining: 51. Limit: 60. Reset: Sat 30 Jul 2022 02:46:14 AM CST.
```

### Screenshots

`:Mason` output:
![image](https://user-images.githubusercontent.com/17326718/181819695-909da6e3-7069-4a42-a8c9-3b31652b5c0b.png)

`:MasonLog`:
[mason.log.zip](https://github.com/williamboman/mason.nvim/files/9222438/mason.zip)

**Comment by williamboman** [comment]
Hello so the errors are available in the error output itself.

For taplo, see [this](https://github.com/tamasfe/taplo/blob/86fb2a2eedda3a0bfaef4940d4897b375c22d9e4/site/site/cli/installation/cargo.md). You'll need `openssl` to be installed on your system.

For npm, a quick Google search suggests it may be related to HTTP proxies. You most likely have an incorrect proxy configuration for `npm`. Also, the error message for `json-lsp` includes the path to a log file which contains more information that I'm sure will be helpful for debugging!

**Comment by zhang-stephen** [comment]
OK, it's my bad for ignoring the issue of proxy... I will have a retry.

I just think `openssl-devel` is not necessary for end-users, and I have installed taplo successfully yesterday.  Thank you for you reply.
