### ISSUE TITLE
[New package]: Sourcekit LSP for Swift

### ISSUE THREAD

**Issue by xyl1t** [williamboman/mason.nvim#208]
### Package name

sourcekit

### Package homepage

https://github.com/apple/sourcekit-lsp

### Languages

Swift

**Comment by williambotman** [comment]
Hello! Pull requests are always very welcomed to add new packages. If the distribution of the package is simple, the installation will most likely be so as well. See [CONTRIBUTING.md](https://github.com/williamboman/mason.nvim/blob/main/CONTRIBUTING.md) and the [API reference](https://github.com/williamboman/mason.nvim/blob/main/doc/reference.md) for more details! You may also use existing packages as reference.

**Comment by williamboman** [comment]
Hello! Sourcekit comes bundled with the Swift toolchain itself. Packaging it as a standalone package in Mason is not in scope. I also believe it would be pretty complicated to achieve. Let me know if you think this is incorrect!

**Comment by Shock9616** [comment]
[nvim-lsp-installer](https://github.com/williamboman/nvim-lsp-installer) had Sourcekit support, and at least as far as I understand this is basically a continuation of that project, so It's gotta be possible
