### ISSUE TITLE
[New package]: proselint

### ISSUE THREAD

**Issue by thecontinium** [williamboman/mason.nvim#212]
### Package name

proselint

### Package homepage

https://github.com/amperser/proselint

### Languages

markdown,text

### How is this package distributed?

https://github.com/amperser/proselint#installation

**Comment by williambotman** [comment]
Hello! Pull requests are always very welcomed to add new packages. If the distribution of the package is simple, the installation will most likely be so as well. See [CONTRIBUTING.md](https://github.com/williamboman/mason.nvim/blob/main/CONTRIBUTING.md) and the [API reference](https://github.com/williamboman/mason.nvim/blob/main/doc/reference.md) for more details! You may also use existing packages as reference.

**Comment by thecontinium** [comment]
Do you want the generated (`make generated`)  `mason-registry/index.lua` checked in as part of the PR ?

**Comment by williamboman** [comment]
> Do you want the generated (`make generated`) `mason-registry/index.lua` checked in as part of the PR ?

Either works, @williambotman will take care of it if it's not. Thanks for the PR!
