### ISSUE TITLE
[rust-analyzer] not work with single rust file

### ISSUE THREAD

**Issue by hiberabyss** [williamboman/mason.nvim#216]
### Problem description

Will have following error when open single rust file.

![image](https://user-images.githubusercontent.com/2898670/182153571-b5b8b03c-97bb-4661-9b26-e3f294197f52.png)

rust-analyzer should support this:

https://github.com/rust-lang/rust-analyzer/pull/8955

### Why do you think this is an issue with mason.nvim?

There may be some config issue with rust analyzer

### Neovim version (>= 0.7)

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.7.2_1/share/nvim"

Run :checkhealth for more info

### Operating system/version

Darwin hbliu-mac13 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:05:47 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8101 arm64

### I've manually reviewed the Nvim LPS client log (`:MasonLog`) to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Affected packages

all

### Steps to reproduce

Create file /tmp/main.rs, open the file, there will be error.

### Actual behavior

Errors occured.

### Expected behavior

No error.

### Healthcheck

```Text
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - OK: **Go**: `go version go1.18.3 darwin/arm64`
  - OK: **cargo**: `cargo 1.62.0 (a748cf5a3 2022-06-08)`
  - OK: **luarocks**: `/opt/homebrew/bin/luarocks 3.9.0`
  - OK: **Ruby**: `ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]`
  - OK: **RubyGem**: `3.0.3.1`
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.15.1`
  - OK: **node**: `v18.6.0`
  - OK: **python3**: `Python 3.9.13`
  - OK: **pip3**: `pip 22.2.1 from /opt/homebrew/lib/python3.9/site-packages/pip (python 3.9)`
  - OK: **javac**: `javac 10.0.1`
  - OK: **java**: `java version "10.0.1" 2018-04-17`
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.2 built on darwin21.1.0.`
  - OK: **curl**: `curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.45.1`
  - OK: **gzip**: `Apple gzip 353.100.22`
  - OK: **tar**: `bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (aarch64-apple-darwin21.1.0)`
  - OK: **sh**: `Ok`
  - WARNING: **JAVA_HOME**: not available
  - OK: GitHub API rate limit. Used: 1. Remaining: 59. Limit: 60. Reset: Mon Aug  1 21:48:57 2022.

```
```


### Screenshots or recordings

_No response_

**Comment by williamboman** [comment]
Hello! This is not controlled by this plugin, but instead lspconfig (as the error message suggests). They do [this](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/rust_analyzer.lua#L17-L54) to discover the workspace directory, which is where the error stems from. If you think there's an error in there please file an issue with lspconfig!
