### ISSUE TITLE
[goimports]: Add package 

### ISSUE THREAD

**Issue by serhez** [williamboman/mason.nvim#223]
### Package name

goimports

### Package homepage

https://pkg.go.dev/golang.org/x/tools/cmd/goimports

### Languages

Go

### How is this package distributed?

`go install`

**Comment by williambotman** [comment]
Hello! Pull requests are always very welcomed to add new packages. If the distribution of the package is simple, the installation will most likely be so as well. See [CONTRIBUTING.md](https://github.com/williamboman/mason.nvim/blob/main/CONTRIBUTING.md) and the [API reference](https://github.com/williamboman/mason.nvim/blob/main/doc/reference.md) for more details! You may also use existing packages as reference.

**Comment by williamboman** [comment]
Thanks for the PR!
