### ISSUE TITLE
Add "ensure_installed" to the config

### ISSUE THREAD

**Issue by serhez** [williamboman/mason.nvim#226]
### Is your feature request related to a problem? Please describe.

Currently, if you work across different machines often, you need to keep a manual list of all servers and tools you use in your environment to replicate such environment in your new machine.

### Describe the solution you'd like

Having a configurable list (e.g., `ensure_installed`, as in [`mason-lspconfig.nvim`](https://github.com/williamboman/mason-lspconfig.nvim)) which ensures on nvim startup that the servers/tools referenced on the list are installed, and installs them otherwise.

In this way, an nvim config using this plugin would be completely portable to a new machine with no gaps in functionality.

### Describe potential alternatives you've considered

I personally have made myself an installer script for my own dev environment and configs (including but not limited to nvim), via which I also install all LSP, DAP, linter and formatting servers along with other tools. Now that I've started to use this plugin, it would only make sense to remove these from my custom installer, since I am installing them via the plugin, but I would lose the functionality of this being done automatically.

**Comment by williamboman** [comment]
Hello! This is also discussed in #103, closing as duplicate.

> I personally have made myself an installer script for my own dev environment and configs (including but not limited to nvim), via which I also install all LSP, DAP, linter and formatting servers along with other tools. Now that I've started to use this plugin, it would only make sense to remove these from my custom installer, since I am installing them via the plugin, but I would lose the functionality of this being done automatically.

You can script things very easily with Mason. Either in your Neovim config directly, using mason's Lua APIs, or through the shell interface (see headless example in `:h :MasonInstall`)
