### ISSUE TITLE
Add support for Sonarlint

### ISSUE THREAD

**Issue by ChristianChiarulli** [williamboman/mason.nvim#247]
### I've searched open issues for similar requests

- [X] Yes

### Is your feature request related to a problem? Please describe.

I would like sonar lint

### Describe the solution you'd like

I would like sonar lint

### Additional context

https://github.com/SonarSource/sonarlint-language-server

^^ link to the language server

**Comment by teddy2104** [comment]
Hi Christian! How do you use Sonarlint in neovim?

**Comment by williamboman** [comment]
Hey! So it [seems like the server is hard-coded to only communicate over TCP](https://github.com/SonarSource/sonarlint-language-server/blob/0f75227b78b4423c3e9d759dcd035dc07b533a18/src/main/java/org/sonarsource/sonarlint/ls/ServerMain.java#L66-L73) (as opposed to stdio, which is the only transport mechanism supported by Neovim's LSP client). There seems to have been a PR to lspconfig, that were closed for some reason. They seem to [leverage netcat to work around this](https://github.com/neovim/nvim-lspconfig/pull/1627/files#diff-f8cd8d035852a39e39e824053782eeef139ff690c52fcdb65bae929eed9aa647R94).

I think it'd make sense to try to get the server added to lspconfig first, before considering adding it here, so if someone wants to pick that up again would be great!

**Comment by williamboman** [comment]
TCP support has been added in core. For now it's only available via the `vim.lsp.start` API (not lspconfig).

**Comment by schrieveslaach** [comment]
FYI, I implement the basic Stdio channel in Sonarlint (see https://github.com/SonarSource/sonarlint-language-server/pull/187) and I'm trying to come up with some Lua code to get Sonarlint running within Neovim. However, looks like that it requires a lot of information to be sent from the client.

**Comment by dav1d-wright** [comment]
Today s a good day to be looking at this Issue, thrilled to see your work on the sonarlint-language-server repo! Looking forward to using this in my work setup :+1:

**Comment by schrieveslaach** [comment]
@dav1d-wright, thanks for these kind words.

With a version of the sonarlint-language-server branch you can use my new [`sonarlint.nvim`](https://gitlab.com/schrieveslaach/sonarlint.nvim). Python analyzer works, Java not yet. I think I have a solution in mind to get the Java anlyzer working.

**Comment by dav1d-wright** [comment]
@schrieveslaach Thank you so much for your work on this! I am afraid that I am using sonarlint for C++ at work, which does not seem to be supported yet. I hope I'll find some time to look into this :slightly_smiling_face:

**Comment by huesersohn** [comment]
@williamboman I'm thinking about adding SonarLint to lspconfig and here, now that @schrieveslaach has added stdio support. How would you handle the analyzers? Should they all be downloaded together with SonarLint itself (the VSCode Extension does ship with some bundled)? Or should the user configure them by hand? Or should they be separate packages although they depend on this?

**Comment by schrieveslaach** [comment]
@huesersohn, please note that not all analyzers just work because there has to be some dance with the LSP client. For example, the Java analyzer needs extra responses with classpath information etc. I started a new Neovim plugin for that (see [sonarlint.nvim](https://gitlab.com/schrieveslaach/sonarlint.nvim)). I'm waiting for the official release of Sonarlint-LS and then I'll continue with adding Java support to the plugin.

**Comment by huesersohn** [comment]
@schrieveslaach Yes, I've used your plugin successfully with your branch with stdio support. Is your plan to implement the download/installation of SonarLint and the analyzers in your plugin? My idea was to just download the same prebuilt jars (and maybe the other languages not supported yet) that the VS Code extension uses.

**Comment by schrieveslaach** [comment]
I didn't plan to implement downloading in sonarlint.nvim. For my dotfiles I wanted to integrate the download into my [chezmoi](https://www.chezmoi.io/) setup.

**Comment by schrieveslaach** [comment]
FYI, got working Java support:

![ezgif-2-0ff4794c7b](https://user-images.githubusercontent.com/16558417/228354201-d9aedc12-0778-4e21-8b6c-c12257c72eba.gif)

**Comment by krishnakumarg1984** [comment]
> I'm waiting for the official release of Sonarlint-LS 

@schrieveslaach I am slightly confused by the above statement. I thought there have been [periodic official releases](https://github.com/SonarSource/sonarlint-language-server/releases) of the Sonarlint-LS

**Comment by schrieveslaach** [comment]
@krishnakumarg1984, sorry, I didn't want to confuse anybody. Maybe, the updated README.md of sonarlint.nvim helps: https://gitlab.com/schrieveslaach/sonarlint.nvim

Basically, I wanted to wait for an official release because development versions of sonarlint-ls may rely on unpublished Maven dependencies (see comments in [sonarlint-language-server PR](https://github.com/SonarSource/sonarlint-language-server/pull/187#issuecomment-1476899827)).

**Comment by williamboman** [comment]
Added in https://github.com/mason-org/mason-registry/pull/1294

**Comment by reisnobre** [comment]
@williamboman question. I'm trying to make use of this, but going to `/home/user/.local/share/lvim/mason/bin` and running the `sonarlint-language-server` it says this: `The operation couldn’t be completed. Unable to locate a Java Runtime.` but on their documentation it says that the vscode version comes with it own JRE thing, do I need to install the JRE way or there's something wrong that I'm doing?

**Comment by williamboman** [comment]
@reisnobre Yeah it's currently packaged in such a way that it requires JRE on the system. I remember seeing that they provide self-hosted JRE but decided to not use that because it would incur a ~50% larger disk footprint.

**Comment by reisnobre** [comment]
@williamboman the sonarlint-analyzers are also not on mason package right? this project https://gitlab.com/schrieveslaach/sonarlint.nvim points that  it would be at "$MASON/share/sonarlint-analyzers/" but I also can't find the folder for it
