### ISSUE TITLE
[New package]: tectonic

### ISSUE THREAD

**Issue by RaafatTurki** [williamboman/mason.nvim#248]
### Package name

tectonic

### Package homepage

https://tectonic-typesetting.github.io/en-US/

### Languages

latex

### How is this package distributed?

Prebuilt binaries can be obtained from the [github releases files](https://github.com/tectonic-typesetting/tectonic/releases)

**Comment by williambotman** [comment]
Hello! Pull requests are always very welcomed to add new packages. If the distribution of the package is simple, the installation will most likely be so as well. See [CONTRIBUTING.md](https://github.com/williamboman/mason.nvim/blob/main/CONTRIBUTING.md) and the [API reference](https://github.com/williamboman/mason.nvim/blob/main/doc/reference.md) for more details! You may also use existing packages as reference.

**Comment by williamboman** [comment]
Hey @RaafatTurki! I’m struggling a bit to see how tectonic relates to Neovim. For now I only intend to support packages that have some clear connection with Neovim (LSP server, DAP server, formatter, linter).

**Comment by RaafatTurki** [comment]
@williamboman my bad, I should've explained this part earlier.

Tectonic doesn't relate directly to neovim, however texlab supports compiling latex using it.

One feature of tectonic is the auto downloading of ctan packages as needed which is very appealing since that means if packaged correctly any user can turn their nvim into a latex editor on any environment.

With that said I can understand if packaging it isn't in scope yet.

**Comment by thanhvule0310** [comment]
This package is simple to add. However, it appears that this project's objectives do not include it. So that you may use it in cli when necessary, I believe you should install it globally.

**Comment by RaafatTurki** [comment]
Thanks to how mason works, every package installed is usable through the nvim terminal. furthermore if globalizing mason packages is desired one could always add `~/.local/share/nvim/mason/bin/` to `$PATH`.

On a side note I believe mason will eventually add packages that don't strictly relate to nvim simply because nvim is so modular. for instance an another package of interest is `xxd`, it's a hexdump utility that ships with `vim` and has the ability to convert its hex dump back to binary.

You can see how it could be used to essentially make `vim` a [hex editor](https://vi.stackexchange.com/questions/2232/how-can-i-use-vim-as-a-hex-editor), and the only proper way to get this software is to either install `vim` or download its [subtree](https://github.com/vim/vim/tree/master/src/xxd) and compile it yourself

You see how that blurs the line between what's nvim related and what's not, perhaps a `Misc` category is in order.

**Comment by williamboman** [comment]
> however texlab supports compiling latex using it.

That's good enough for me!

> You see how that blurs the line between what's nvim related and what's not, perhaps a `Misc` category is in order.

I'm not sure I agree with the overall sentiment. What I'm primarily looking for when considering a package that doesn't fit one of the existing categories are usage examples where Neovim somehow directly interfaces with the tool. Taking the `xxd` use-case as an example; it enables translation of buffer <-> file contents via stdio, where Neovim will directly invoke the program.

This principle is loosely applied though, there will be cases where a package ticks all the boxes but it wouldn't make sense to include it (take `git` for example). Mason is a complement to more competent and established package managers, not a replacement!

**Comment by williamboman** [comment]
Added in #249!
