### ISSUE TITLE
Symbolic link of json-lsp in ~/.local/share/nvim/mason/bin is different with mason-registry

### ISSUE THREAD

**Issue by zhang-stephen** [williamboman/mason.nvim#250]
### I've made an initial investigation into the error myself

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

Hi, The symbolic link created for `json-lsp` is `vscode-json-language-server`, instead of the registry name `json-lsp`. I think it's not a good behavior, is it?

### Neovim version (>= 0.7)

```
NVIM v0.8.0-dev-731-g468b1a689
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by p8zhang@l1sw-env

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/host/workdir/local/share/nvim"

Run :checkhealth for more info
```

### Operating system/version

Linux localhost 5.18.11-1-default #1 SMP PREEMPT_DYNAMIC Fri Jul 15 05:36:11 UTC 2022 (4fcb983) x86_64 x86_64 x86_64 GNU/Linux

### Affected packages

json-lsp

### Actual behavior

A symbolic link named 'vscode-json-language-server' has been created after installation.

### Expected behavior

the symbolic name should be `json-lsp`.

### Mason output

```Text
I think it's not necessary for this issue, `json-lsp` has been installed successfully.
```

### Installation log

```Text
not necessary for this issue.
```

### Healthcheck

```Text
not necessary for this issue
```

### Screenshots

![image](https://user-images.githubusercontent.com/17326718/183014668-d6ed0596-6b65-44e2-916a-93db658d3747.png)

**Comment by williamboman** [comment]
Hey! Yeah the servers vendored in https://github.com/hrsh7th/vscode-langservers-extracted (the JSON LSP being one of them) is a bit awkward as they're all bundled together under a single npm package, and their executables come with the `vscode-*` prefix. In Mason these are separated into their own distinct packages, with a name that is unique to Mason.

I'd personally prefer if they were distributed as standalone packages (without a vscode prefix), in which case Mason could use the same package name. I'm not too sure about diverting from upstream executable names by introducing a new executable name (`json-lsp`) as I think it'll only cause more issues. There's also no rule that linked executables must have the same name as the Mason package name (although it is very much preferred).

Did this cause any problems when you were trying to use the package somehow?

**Comment by zhang-stephen** [comment]
Hey, I was too busy to reply this... my bad.

I had built a [plugin](https://github.com/zhang-stephen/nvim-lsp-loader), which is powered by `nvim-lspconfig` and `manson.nvim`, and use `.json` files to load languages servers. I met this issue when I tried to use registry name as executable in path `~/.local/share/nvim/mason/bin`...

Now I find the executable name is a member in registry, I will try to get executable this way, thank you for your reply.

**Comment by zhang-stephen** [comment]
I had read the code of UI, and I found there seems to be a installation state table maintained by installer context. So I cannot get executable names from registry, could you help on it? Or add new APIs in `mason-core.Package` to get executable?

**Comment by williamboman** [comment]
So I took a quick look in the plugin source to get a better understanding of the problem and have some recommendations:

- I'd really avoid dynamically producing a `cmd` based on a package name. There is no 1:1 relation between these, although in most cases the executable does have the same name as the package.
- You shouldn't need to produce a full path to the executable. The executable will exist on PATH (assuming mason.nvim has been set up)
- Some server configurations in lspconfig don't come with a `cmd`, for different reasons. For these servers, the `mason-lspconfig` plugin will provide a custom `cmd` that points to an executable installed by Mason. So for full coverage I'd recommend including the `mason-lspconfig` plugin in the dependencies

As for exposing which executables a package will install - this is sort of already possible via the receipt file that Mason writes upon successful installation (accessible via `Package:get_receipt()`). Note that this requires the package to be installed, there's no way to gather which executables an uninstalled package will install (this is quite far down the prio lane)

**Comment by zhang-stephen** [comment]
Thank you, I will have a try about `Package:get_receipt()`.

The full path executable is designed for servers which are not managed by mason and not in the `$PATH`, I will try a new method to refactor this.

I will raise a new discussion if there were new questions.
