### ISSUE TITLE
[New package]: latexindent

### ISSUE THREAD

**Issue by RaafatTurki** [williamboman/mason.nvim#261]
### Package name

latexindent

### Package homepage

https://github.com/cmhughes/latexindent.pl

### Languages

latex

### How is this package distributed?

It's distributed in a zip file in the github releases page, the zip comes with `latexindent.pl` and all it's dependencies.

when mason symlinks `latexindent.pl` it should remove the file extension (`latexindent`) as that's how it's normally distributed and how other latex utilities reference it.

Note: this belongs in the `Formatter` category and can be used via `texlab` and `null-ls`

**Comment by williambotman** [comment]
Hello! Pull requests are always very welcomed to add new packages. If the distribution of the package is simple, the installation will most likely be so as well. See [CONTRIBUTING.md](https://github.com/williamboman/mason.nvim/blob/main/CONTRIBUTING.md) and the [API reference](https://github.com/williamboman/mason.nvim/blob/main/doc/reference.md) for more details! You may also use existing packages as reference.
