### ISSUE TITLE
volar not find tsserve rlibrary.js

### ISSUE THREAD

**Issue by kola-web** [williamboman/mason.nvim#269]
### I believe this to be an issue that should be addressed by maintainers of mason.nvim.

- [X] Yes

### Why do you think this is an issue with mason.nvim?

I don't have this problem when using volar with lsp-installer

### Neovim version (>= 0.7)

![image](https://user-images.githubusercontent.com/46446884/183384088-aa614110-d209-4183-964a-7e2741d478ee.png)

### Operating system/version

Darwin localhost 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64

### I've manually reviewed logs to find potential errors

- [ ] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Affected packages

volar

### Problem description

![image](https://user-images.githubusercontent.com/46446884/183383864-198fada9-3afe-4438-9d7b-f794332041a1.png)

### Steps to reproduce

1. use volar 
2. open vue file

### Actual behavior

none

### Expected behavior

none

### Healthcheck

```Text
mason: 
========================================================================
  - ERROR: No healthcheck found for "mason" plugin.
```

**Comment by williamboman** [comment]
Hello! From the call stack in the error message it doesn't seem like you're running vue-language-server via Mason, but instead via `fnm`. The checkhealth output also suggests you're not even using Mason at all? I'm also not sure how to interpret the following:

> Actual behavior
> none
>
> Expected behavior
> none

I don't have any issues running vue-language-server

**Comment by kola-web** [comment]
If typescript is not installed in the project, an error will be reported 
When using lspinstall to install volar before, no error will be reported

**Comment by williamboman** [comment]
The error log suggests you're running an non-Mason installation of the language server. Also, do you use mason-lspconfig? Without mason-lspconfig you'll have to configure the fallback typescript resolution yourself.
