### ISSUE TITLE
[New package]: ruby-lsp

### ISSUE THREAD

**Issue by cj** [williamboman/mason.nvim#276]
### Package name

ruby-lsp

### Package homepage

https://github.com/Shopify/ruby-lsp

### Languages

ruby

**Comment by williambotman** [comment]
Hello! Pull requests are always very welcomed to add new packages. If the distribution of the package is simple, the installation will most likely be so as well. See [CONTRIBUTING.md](https://github.com/williamboman/mason.nvim/blob/main/CONTRIBUTING.md) and the [API reference](https://github.com/williamboman/mason.nvim/blob/main/doc/reference.md) for more details! You may also use existing packages as reference.

**Comment by jayp0521** [comment]
https://github.com/williamboman/mason.nvim/pull/446
