### ISSUE TITLE
[New package]: flutter-tools.nvim

### ISSUE THREAD

**Issue by ArbazIrshad** [williamboman/mason.nvim#279]
### Package name

flutter-tools.nvim

### Package homepage

https://github.com/akinsho/flutter-tools.nvim

### Languages

Dart, Flutter

**Comment by williambotman** [comment]
Hello! Pull requests are always very welcomed to add new packages. If the distribution of the package is simple, the installation will most likely be so as well. See [CONTRIBUTING.md](https://github.com/williamboman/mason.nvim/blob/main/CONTRIBUTING.md) and the [API reference](https://github.com/williamboman/mason.nvim/blob/main/doc/reference.md) for more details! You may also use existing packages as reference.

**Comment by williamboman** [comment]
Hello! Hmm, flutter-tools.nvim is a Neovim plugin, not a package that would be a candidate for addition in Mason. I'll go ahead and close this for that reason, let's re-open in case I misunderstood you.
