### ISSUE TITLE
Neovim can't detect language servers

### ISSUE THREAD

**Issue by IZenithy** [williamboman/mason.nvim#292]
### Problem description

Hello, how are you? I hope that you are doing well!

My problem is that after installing servers, it seems like Neovim don't know about them, for example I have installed lua-language-server, but when I open a Lua file, diagnostic doesn't work

### Neovim version (>= 0.7)

NVIM v0.8.0-dev-837-g3cf629022b
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions     -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security     -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/ahmed/.cache/paru/clone/neovim-git/src/build/cmake.config -I/home/ahmed/.cache/paru/clone/neovim-git/src/neovim-git/src -I/usr/include -I/home/ahmed/.cache/paru/clone/neovim-git/src/build/src/nvim/auto -I/home/ahmed/.cache/paru/clone/neovim-git/src/build/include
Compiled by ahmed

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Operating system/version

Linux Zenithy 5.15.60-1-lts #1 SMP Thu, 11 Aug 2022 14:09:59 +0000 x86_64 GNU/Linux

### I've recently downloaded the latest plugin version of mason.nvim

- [x] Yes

### Actual behavior

Neovim can't detect language servers

### Expected behavior

Neovim should detect language servers

### Healthcheck output

```shell
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - WARNING: **Go**: not available
  - OK: **cargo**: `cargo 1.63.0`
  - WARNING: **luarocks**: not available
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.17.0`
  - OK: **node**: `v18.7.0`
  - OK: **python3**: `Python 3.10.5`
  - OK: **pip3**: `pip 22.2.2 from /usr/lib/python3.10/site-packages/pip (python 3.10)`
  - WARNING: **javac**: not available
  - OK: **java**: `openjdk version "18.0.2" 2022-07-19`
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: **curl**: `curl 7.84.0 (x86_64-pc-linux-gnu) libcurl/7.84.0 OpenSSL/1.1.1q zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.3 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.48.0`
  - OK: **gzip**: `gzip 1.12`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: Sat 13 Aug 2022 07:13:16 PM +03.
```

### Screenshots

![2022-08-13_18:14:06](https://user-images.githubusercontent.com/82327047/184500209-8c5a2e31-365c-40bf-a6ac-a6905c1a85a8.jpg)

![2022-08-13_18:14:29](https://user-images.githubusercontent.com/82327047/184500237-372cc190-658f-437f-9873-be6861013079.jpg)

**Comment by Raagh** [comment]
I am encountering the same. I open a js file and typescript language server does nothing. It was working fine with lsp-installer

**Comment by williamboman** [comment]
Hey! So you'll need to setup the servers yourself. There are quite a few different ways of doing this (`:h lsp`), the easiest being via [`lspconfig`](https://github.com/neovim/nvim-lspconfig/). [mason-lspconfig.nvim](https://github.com/williamboman/mason-lspconfig.nvim) helps bridge these plugins. See `:h mason-how-to`, `:h mason-lspconfig-quickstart`

**Comment by IZenithy** [comment]
Thank you, That solved my problem.

**Comment by Raagh** [comment]
Hi william so I am a little bit confused, Mason doesn't take care of configuring the servers if you have mason and mason-lspconfig installed and running? I mean what is the UI for if you can't install servers from there and you have to manually pass them to the setup function. It seems I am missing some knowledge

**Comment by williamboman** [comment]
> Hi william so I am a little bit confused, Mason doesn't take care of configuring the servers if you have mason and mason-lspconfig installed and running?

Not by default, no. mason-lspconfig does however provide amenities for automatically setting up installed servers (`:h mason-lspconfig-quickstart`).

> What am I missing?

`:h mason-lspconfig-quickstart` 😉!

> It seems strange to have a UI to install the servers but you still need to go into code and manually pass lspconfig server names to the setup function..

lspconfig is just one of the methods available to set up LSP servers. Mason doesn't care which method you end up using, it just provides the means to make external tooling available to Neovim.
