### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by ghassan0** [williamboman/mason.nvim#306]
### I've searched open issues for similar requests

- [X] Yes

### Is your feature request related to a problem? Please describe.

I tried using this on Termux on my Android phone and noticed that some installed LSPs exit with an error every time they get invoked such as lua-language-server and ltex-ls.

### Describe the solution you'd like

Add an additional platform check and install instructions for termux/android support

### Describe potential alternatives you've considered

Some LSPs can be installed from the Termux repo such as lua-language-server but others are not available such as ltex-ls. But ideally they would all be installed through mason.

**Comment by williamboman** [comment]
Hello! Support for Android rely heavily on what precompiled assets are available. It is extremely uncommon to provide assets for Android systems, so packages that makes use of precompiled assets are generally not available on Android. This does fall short of the premise of Mason, but it is what it is. You'll have to manage unsupported packages outside of Mason for now (e.g. manually building these if possible).

Packages that rely on a runtime such as Node or Python should be available though. This includes a majority of packages in Mason.

**Comment by ghassan0** [comment]
That's understandable. Honestly, almost all of the packages I tried were able to be installed properly (given that I have `python`, `nodejs`, `golang`, `rust`, etc. already installed). Which is really awesome so great job!

Considering there is a somewhat similar issue when it comes to OpenBSD/FreeBSD, how do you feel about adding a "Supported Systems" field under the "Languages" and "Categories" fields of each package in `PACKAGES.md`?

**Comment by williamboman** [comment]
(closing as there's nothing actionable here)

> Considering there is a somewhat similar issue when it comes to OpenBSD/FreeBSD, how do you feel about adding a "Supported Systems" field under the "Languages" and "Categories" fields of each package in `PACKAGES.md`?

I think that'd make sense! This should be fairly easy to accomplish once https://github.com/mason-org/mason-registry is live
