### ISSUE TITLE
`mason-null-ls.nvim`

### ISSUE THREAD

**Issue by ok-nick** [williamboman/mason.nvim#324]
Similar to `mason-lspconfig`, `mason-null-ls` would be extremely convenient. I know it's probably not the highest priority, but I thought I'd leave it here.

It's also worth checking out all the built-in tooling by `null-ls`. Should definitely port them over to mason if not already.

**Comment by williamboman** [comment]
Hello! Yes this has been on my mind as well. I think a `mason-dap` plugin (to bridge with `nvim-dap`) has an even greater need due to how configuration-heavy it is. Are there any particular features you think are missing, what would you like to see in a `mason-null-ls.nvim` plugin?

**Comment by ok-nick** [comment]
I'd like to see it auto-install `null-ls` built-in sources, just like `mason-lspconfig.nvim`.

**Comment by mehalter** [comment]
@williamboman I think the main thing I would want to see in a `mason-null-ls` plugin is similar to the `lspconfig` plugin where it has mappings from packages to their equivalent null-ls built in as well as a hook that gets called when those packages are ready to assist with automatically registering them. 


Great work by the way on Mason! As one of the lead developers of AstroNvim it has made our life so much easier!

**Comment by jayp0521** [comment]
This needs more time and testing, but I have a working implementation of `mason-null-ls.nvim`. I will update README.md and give credit where it is due later, **https://github.com/jayp0521/mason-null-ls.nvim**. Please don't hesitate to provide feedback. This is my first neovim plugin!

Thinking about working on the `dap` equivalent later.

**Comment by jayp0521** [comment]
@ok-nick any initial thoughts on the above? I believe you were the first to request. maybe we can close the issue

**Comment by ok-nick** [comment]
@jayp0521 I'm going to hopefully try it out later today and I'll let you know how it goes. Nice work.

**Comment by jayp0521** [comment]
Any update on the above? @ok-nick

Can probably resolve this issue

**Comment by jayp0521** [comment]
FYI, just released https://github.com/jayp0521/mason-nvim-dap.nvim. Still needs some polishing and some functionality is missing

**Comment by MagicDuck** [comment]
@jay-babu thanks for `mason-null-ls.nvim`. Just added it to my config and it's working perfectly 😄 
Should probably be advertised on the README for this project.

**Comment by jay-babu** [comment]
Only @williamboman can approve that :)
