### ISSUE TITLE
Add nvim-cmp setup guide

### ISSUE THREAD

**Issue by DrK01** [williamboman/mason.nvim#325]
### I've searched open issues for similar requests

- [X] Yes

### Is your feature request related to a problem? Please describe.

Could you please add a migration guide from lsp-install to Mason?

### Describe the solution you'd like

A full guide about migration & integration with different autocomplete plugins

**Comment by williamboman** [comment]
Hello! There are plenty of guides and docs for nvim-cmp, I'm not sure I have anything to add personally. Mason also doesn't unlock anything when it comes to nvim-cmp or other completion plugins, so there's a pretty weak relation between Mason and autocompletion plugins.

> Could you please add a migration guide from lsp-install to Mason?

There's one here: https://github.com/williamboman/nvim-lsp-installer/discussions/876!
