### ISSUE TITLE
Leaves `wget-log` files in working directory

### ISSUE THREAD

**Issue by mrjones2014** [williamboman/mason.nvim#332]
### Problem description

Running mason installers sometimes leaves files `wget-log`, `wget-log.1` etc. in my working directory. Is there a way to not write these files or write them in the plugin directory instead of my working directory?

### Neovim version (>= 0.7)

```
NVIM v0.8.0-dev-875-gf5588ee89
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by mat@Mats-MBP.lan

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-f5588ee_1/share/nvim"

Run :checkhealth for more info
```

### Operating system/version

Darwin Mats-MBP.lan 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000 arm64

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Actual behavior

Writes wget logs in my working directory.

### Expected behavior

should not write wget logs or should write them to plugin directory and not my working directory.

### Healthcheck output

```shell
mason: require("mason.health").check()
      ========================================================================
      ## mason.nvim report
        - OK: neovim version >= 0.7.0
        - OK: Go: `go version go1.19 darwin/arm64`
        - OK: cargo: `cargo 1.61.0 (a028ae42f 2022-04-29)`
        - OK: luarocks: `/opt/homebrew/bin/luarocks 3.9.1`
        - OK: Ruby: `ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]`
        - OK: RubyGem: `3.0.3.1`
        - WARNING: Composer: not available
        - WARNING: PHP: not available
        - OK: npm: `8.3.1`
        - OK: node: `v16.14.0`
        - OK: python3: `Python 3.10.6`
        - OK: pip3: `pip 22.2.2 from /opt/homebrew/lib/python3.10/site-packages/pip (python 3.10)`
        - WARNING: javac: not available
        - WARNING: java: not available
        - WARNING: julia: not available
        - OK: wget: `GNU Wget 1.21.3 built on darwin21.3.0.`
        - OK: curl: `curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.45.1`
        - OK: gzip: `Apple gzip 353.100.22`
        - OK: tar: `bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
        - OK: bash: `GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)`
        - OK: sh: `Ok`
        - ERROR: GitHub API rate limit exceeded. Used: 60. Remaining: 0. Limit: 60. Reset: Mon Aug 22 15:00:05 2022.
```
```


### Screenshots

_No response_

**Comment by williamboman** [comment]
That's.. odd. After some quick research it seems like there's no definitive way to disable them. I run the exact same version (on Darwin as well) but have never experienced this. First of all, I think I'll reorder the priority and use curl first, and wget as fall back. Doesn't fix the issue itself but should make it much less prevalent.

**Comment by williamboman** [comment]
Could you try the branch `fix/wget-log-file` and see if that fixes the log file issue for you? Will have to revise it for Windows support

**Comment by mrjones2014** [comment]
Sure, I'll try it out today and report back.

**Comment by mrjones2014** [comment]
This seems to fix it.
