### ISSUE TITLE
How to install jdtls?

### ISSUE THREAD

**Issue by JRS-Developer** [williamboman/mason.nvim#338]
### Discussed in https://github.com/williamboman/mason.nvim/discussions/337

<div type='discussions-op-text'>

<sup>Originally posted by **JRS-Developer** August 24, 2022</sup>
Hello, I have tried to install jdtls using MasonInstall and it says that it's installed successfully but when I open a java file it shows up this message: "Client 1 quit with exit code 1 and signal 0"

I have already installed OpenJDK 17 using APT with Ubuntu 16.04.

I tried executing jdtls from ~/.local/share/nvim/mason/bin  and it shows up this message:

Traceback (most recent call last):
  File "./jdtls", line 17, in <module>
    jdtls.main(sys.argv[1:])
  File "/home/jose/.local/share/nvim/mason/packages/jdtls/bin/jdtls.py", line 68, in main
    parser.add_argument("--validate-java-version", default=True, action=argparse.BooleanOptionalAction)
AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'</div>

**Comment by williamboman** [comment]
#337
