### ISSUE TITLE
Add ccls Server

### ISSUE THREAD

**Issue by asteroidalaz** [williamboman/mason.nvim#349]
### I've searched open issues for similar requests

- [ ] Yes

### Is your feature request related to a problem? Please describe.

I use clangd for c/c++ stuff, but I think ccls lsp is far more developed and fast (as written in c++, rather than python in which clangd is written). And also the header suggestions in clangd have > appended to it, which is kind of annoying.

### Describe the solution you'd like

 So If you guys add ccls server to the mason download list it would be easier to install.

**Comment by williamboman** [comment]
Hello! ccls used to be supported but it was very problematic due to lack of precompiled binaries as well cross-platform inconsistencies when building. It's currently a non-goal to support ccls.

**Comment by sarmong** [comment]
@williamboman can such info be shown in `:Mason` somehow? 

I think it would greatly improve user experience because you wouldn't need to search for issues to find that is not supported
