### ISSUE TITLE
[New package]: bufls

### ISSUE THREAD

**Issue by iwata** [williamboman/mason.nvim#362]
### Package name

buf-language-server

### Package homepage

https://github.com/bufbuild/buf-language-server

### Languages

protobuf

### How is this package distributed?

buf-language-server can be installed via go install:
```
go install github.com/bufbuild/buf-language-server/cmd/bufls@latest
```
https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#bufls

**Comment by williambotman** [comment]
Hello! Pull requests are always very welcomed to add new packages. If the distribution of the package is simple, the installation will most likely be so as well. See [CONTRIBUTING.md](https://github.com/williamboman/mason.nvim/blob/main/CONTRIBUTING.md) and the [API reference](https://github.com/williamboman/mason.nvim/blob/main/doc/reference.md) for more details! You may also use existing packages as reference.
