### ISSUE TITLE
codelldb via nvim-dap

### ISSUE THREAD

**Issue by HearseDev** [williamboman/mason.nvim#371]
### I believe this to be an issue that should be addressed by maintainers of mason.nvim.

- [X] Yes

### Why do you think this is an issue with mason.nvim?

codelldb works fine without mason, so it is clear that the issue is within mason itself.

### Neovim version (>= 0.7)

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.7.2_1/share/nvim"

Run :checkhealth for more info

### Operating system/version

Darwin admin-MacBook-Air.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:35 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T8101 arm64

### I've manually reviewed logs to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Affected packages

codelldb as far as I am aware, maybe more

### Problem description
***Error***:
 ```cpp
use { 'mfussenegger/nvim-dap', config = function()
      local dap = require('dap')
      dap.adapters.codelldb = {
        type = 'server',
        port = "1234",
        executable = {
          -- CHANGE THIS to your path!
          command = 'codelldb',
          args = { "--port", "1234" },

          -- On windows you may have to uncomment this:
          -- detached = false,
        }

      }
```
This causes the codelldb binary to crash since it looks within the mason folder to codelldb.dylib. Instead using this below is the right choice since within the extension, there is a folder lldb/lib which contains codelldb.dylib which this extension needs to dlopen.
***Working***:
 ```cpp
use { 'mfussenegger/nvim-dap', config = function()
      local dap = require('dap')
      dap.adapters.codelldb = {
        type = 'server',
        port = "1234",
        executable = {
          -- CHANGE THIS to your path!
          command = '/Users/xxx/.local/share/nvim/mason/packages/codelldb/extension/adapter/codelldb',
          args = { "--port", "1234" },

          -- On windows you may have to uncomment this:
          -- detached = false,
        }

      }
```

Error:
```
[debug-adapter stderr] Error: "\"dlopen(/Users/xxx/.local/share/nvim/mason/lldb/lib/liblldb.dylib, 0x0009): tried: \\'/Users/xxx/.local/share/nvim/mason/lldb/lib/liblldb.dylib\\' (no such file)\""
```
See how it is looking in mason's folder for lldb/lib. it is in fact supposed to be inside of the extension folder. One thing that is possible to is add the packages/codelldb/extension folder in the codelldb binary rpath so it can find it successfully. which can be done using install_name_tool.

### Steps to reproduce

should be easy to reproduce by the problem description. install codelldb and set it up using the path set to "codelldb"

### Actual behavior

error.

### Expected behavior

the expected behavior is for the debug adapter to work correctly

### Healthcheck

```Text
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - WARNING: **Go**: not available
  - WARNING: **cargo**: not available
  - WARNING: **luarocks**: not available
  - OK: **Ruby**: `ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]`
  - OK: **RubyGem**: `3.0.3.1`
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.18.0`
  - OK: **node**: `v18.8.0`
  - OK: **python3**: `Python 3.10.6`
  - OK: **pip3**: `pip 22.2.2 from /opt/homebrew/lib/python3.10/site-packages/pip (python 3.10)`
  - OK: **javac**: `javac 18.0.2.1`
  - OK: **java**: `openjdk version "18.0.2.1" 2022-08-18`
  - WARNING: **julia**: not available
  - ERROR: **wget**: not available
  - OK: **curl**: `curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.45.1`
  - OK: **gzip**: `Apple gzip 353.100.22`
  - OK: **tar**: `bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
  - OK: **bash**: `GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 6. Remaining: 54. Limit: 60. Reset: Fri Sep  2 11:52:01 2022.
```
```


### Screenshots or recordings

_No response_

**Comment by williamboman** [comment]
Ah, this should be fixed in #374.
