### ISSUE TITLE
vscode-chrome-debug calls `npm install` twice

### ISSUE THREAD

**Issue by jayp0521** [williamboman/mason.nvim#377]
Unsure if this is a expected, but seeing that both `npm install` and `npm install --production` are being run. I would expect this is unoptimal in terms of speed. Just wanted to confirm. Maybe I can add a comment if it is.

https://github.com/williamboman/mason.nvim/blob/c6bd87abd0526a01522e27e5b4575e8e18ba0678/lua/mason-registry/chrome-debug-adapter/init.lua#L20

https://github.com/williamboman/mason.nvim/blob/main/lua/mason-registry/chrome-debug-adapter/init.lua#L24

**Comment by williamboman** [comment]
Hello! When running `npm install` it'll install both `dependencies` as well as `devDependencies`. This is usually needed to build the program. Once the build is completed you should only really need the runtime dependencies listed in `dependencies`, assuming they've been split correctly. This is the case with `chrome-debug-adapter`. By running `npm install --production` it'll make sure to only include the packages listed under `depdendencies`.

**Comment by williamboman** [comment]
I just saw the surrounding comment. I'm not sure why it's producing erroneous exit codes, but it shouldn't be a problem. Are you experiencing issues with the package?
