### ISSUE TITLE
Option to change default downloader

### ISSUE THREAD

**Issue by shaeinst** [williamboman/mason.nvim#389]
### I've searched open issues for similar requests

- [X] Yes

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

it would be nice if we had an option to change the default downloader. So that we can config Mason to use wget, curl, aria2c... anything we like to use.
something like this 
```lua
downloader = "aria2c"
```

**Comment by williamboman** [comment]
Hello! I'm not particularly keen on supporting a wide variety of network utilities. Would this help solve a specific problem? Does `wget` or `curl` not work for you?

**Comment by shaeinst** [comment]
no, they both works fine. But `aria2c` is little faster than them. 
>Does wget or curl not work for you?

since Mason is package downloader, i thought it would be nice to have option to change downloader.

**Comment by williamboman** [comment]
> since Mason is package downloader, i thought it would be nice to have option to change downloader.

I'm personally opposed to adding customization for every single thing unless there's very strong case for it. Have you benchmarked performance to have a strong case to support this? It would be interesting to see. I'm personally not exposed to bottlenecks with downloading assets because I am lucky to have a very fast internet connection.

I'm not very educated in how aria2 et al. actually speeds up transfers, and correct me if I'm wrong, but if the bottleneck is on the client side I have a hard time seeing how using multiple connections would improve things? I'd be surprised if GitHub's CDN is the bottleneck here.

**Comment by shaeinst** [comment]
humm..interesting. speed on both are almost same but aria2c is still faster than wget. when i have to download larger file, aira2c downloads faster than wget. since there is no case for downloading larger file  on Mason, speed on both wget and aria2c are identical.

```log
wget -q https://github.com/psf/black/releases/download/22.8.0/black_linux  0.13s user 0.17s system 6% cpu 4.593 total
wget -q https://github.com/psf/black/releases/download/22.8.0/black_linux  0.16s user 0.15s system 6% cpu 4.582 total
wget -q https://github.com/psf/black/releases/download/22.8.0/black_linux  0.20s user 0.32s system 5% cpu 9.283 total
wget -q https://github.com/psf/black/releases/download/22.8.0/black_linux  0.16s user 0.19s system 7% cpu 4.580 total
wget -q https://github.com/psf/black/releases/download/22.8.0/black_linux  0.24s user 0.26s system 3% cpu 14.085 total
wget -q https://github.com/psf/black/releases/download/22.8.0/black_linux  0.19s user 0.13s system 7% cpu 4.390 total
wget -q https://github.com/psf/black/releases/download/22.8.0/black_linux  0.16s user 0.21s system 5% cpu 6.459 total
wget -q https://github.com/psf/black/releases/download/22.8.0/black_linux  0.18s user 0.17s system 7% cpu 4.405 total
wget -q https://github.com/psf/black/releases/download/22.8.0/black_linux  0.17s user 0.21s system 7% cpu 4.895 total
wget -q https://github.com/psf/black/releases/download/22.8.0/black_linux  0.15s user 0.15s system 7% cpu 4.206 total
------------------------------------
aria2c https://github.com/psf/black/releases/download/22.8.0/black_linux  0.16s user 0.16s system 6% cpu 4.756 total
aria2c https://github.com/psf/black/releases/download/22.8.0/black_linux  0.16s user 0.18s system 7% cpu 4.409 total
aria2c https://github.com/psf/black/releases/download/22.8.0/black_linux  0.23s user 0.22s system 5% cpu 7.696 total
aria2c https://github.com/psf/black/releases/download/22.8.0/black_linux  0.24s user 0.26s system 6% cpu 7.376 total
aria2c https://github.com/psf/black/releases/download/22.8.0/black_linux  0.10s user 0.11s system 3% cpu 6.675 total
aria2c https://github.com/psf/black/releases/download/22.8.0/black_linux  0.20s user 0.19s system 5% cpu 6.644 total
aria2c https://github.com/psf/black/releases/download/22.8.0/black_linux  0.18s user 0.14s system 6% cpu 5.106 total
aria2c https://github.com/psf/black/releases/download/22.8.0/black_linux  0.14s user 0.21s system 7% cpu 4.909 total
aria2c https://github.com/psf/black/releases/download/22.8.0/black_linux  0.18s user 0.15s system 5% cpu 6.132 total
aria2c https://github.com/psf/black/releases/download/22.8.0/black_linux  0.16s user 0.15s system 6% cpu 4.510 total


Average for WGET
---------
user   = 0.174
system = 0.196s
cpu    = 6%
total = 6.147799999999999


Average for ARIA2C
---------
user   = 0.175
system = 0.17699999999999996
cpu    = 5.6%
total  = 5.821299999999999
```

**Comment by williamboman** [comment]
Interesting! Thanks for sharing. Seems very identical indeed. Since there does not seem to be many actual benefits to be made, let's close this
