### ISSUE TITLE
jdtls cannot find the projects root directory. Language server does not start

### ISSUE THREAD

**Issue by DasOhmoff** [williamboman/mason.nvim#401]
### I believe this to be an issue that should be addressed by maintainers of mason.nvim.

- [X] Yes

### Why do you think this is an issue with mason.nvim?

After installing the language server via Mason, I think the LSP is supposed to automatically start when entering java files, which it does not do.

### Neovim version (>= 0.7)

NVIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system/version

Windows 10, 64 bit

### I've manually reviewed logs to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Affected packages

jdtls

### Problem description

After installing jdtls via mason, jdtls cannot find the projects root directory. Language server does not start. Here is the error:
```
 Config: jdtls
 	Refer to :h lspconfig-root-detection for help.
 	filetypes:         java
 	root directory:    Not found. Searched for: { -- Single-module projects { 'build.xml', -- Ant 'pom.xml', -- Maven 'settings.gradle', -- Gradle 'settings.gradle.kts', -- Gradle }, -- Multi-module projects { 'build.gradle', 'build.gradle.kts' }, } or vim.fn.getcwd().
 	cmd:               C:\Users\Adam\AppData\Local\nvim-data\mason\bin\jdtls.CMD -configuration C:\Users\Adam/.cache/jdtls/config -data C:\Users\Adam/.cache/jdtls/workspace
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   workspace/applyEdit, textDocument/rename, language/status, textDocument/codeAction
```

### Steps to reproduce

1. Set the vim config:
```vim
call plug#begin("~/.vim/plugged")

Plug 'williamboman/mason.nvim'
Plug 'williamboman/mason-lspconfig.nvim'
Plug 'neovim/nvim-lspconfig'

call plug#end()
```
2. Set the lua config:
```lua
require("mason").setup()
require("mason-lspconfig").setup()
require("lspconfig").jdtls.setup {}
```
3. Install jdtls via `MasonInstall jdtls`
4. Open a java file in a java project that contains a `settings.gradle` or so
![image](https://user-images.githubusercontent.com/16063186/189496494-51085789-4321-4232-8582-46c5bec49a19.png)
6. Use the `LspInfo` command to see that the root directory of the project was not found
![image](https://user-images.githubusercontent.com/16063186/189496464-d878afe3-8147-4106-af03-d89a74d8d847.png)

### Actual behavior

After installing jdtls via mason, jdtls cannot find the projects root directory. Language server does not start.

### Expected behavior

After installing jdtls via mason, jdtls should be able to find the projects root directory. Language server should start.

### Healthcheck

```Text
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - WARNING: **Go**: unsupported version `go version go1.16.7 windows/amd64`. Go version must be >= 1.17.
  - OK: **cargo**: `cargo 1.61.0 (a028ae42f 2022-04-29)`
  - OK: **luarocks**: `luarocks 3.9.1
`
  - OK: **Ruby**: `ruby 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]
`
  - OK: **RubyGem**: `3.0.3
`
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.18.0`
  - OK: **node**: `v16.17.0
`
  - OK: **python3**: `Python 3.10.6
`
  - OK: **pip3**: `pip 22.2.1 from C:\Users\Adam\AppData\Local\Programs\Python310\lib\site-packages\pip (python 3.10)

`
  - OK: **javac**: `javac 17.0.4.1
`
  - OK: **java**: `java version "17.0.4.1" 2022-08-18 LTS
`
  - WARNING: **julia**: not available
  - ERROR: **wget**: not available
  - OK: **curl**: `curl 7.83.1 (Windows) libcurl/7.83.1 Schannel
`
  - OK: **gzip**: `gzip 1.11`
  - OK: **tar**: `bsdtar 3.5.2 - libarchive 3.5.2 zlib/1.2.5.f-ipp 
`
  - OK: **python**: `Ok`
  - OK: **pip**: `pip 22.2.1 from C:\Users\Adam\AppData\Local\Programs\Python310\lib\site-packages\pip (python 3.10)

`
  - WARNING: **python3_host_prog**: not available
  - OK: **JAVA_HOME**: `openjdk version "18.0.2.1" 2022-08-18
`
  - OK: GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: 9/10/2022 7:36:44 PM.
```
```


### Screenshots or recordings

_No response_

**Comment by williamboman** [comment]
Hello! Mason is not involved in starting servers, since you use lspconfig it's lspconfig that is responsible. I believe this is not an issue with Mason so I'll go ahead and close this. I'd recommend checking `:LspLog` if you haven't already - if you find something more that indicates this is indeed something with Mason let's reopen!

**Comment by boningggg** [comment]
It's not an issue of Mason.
I think you need to configure the jdtls correctly with your lspconfig. The default configuration of jdtls in lspconfig is not suitable for us, we need to modify it.

See [this for help](https://github.com/mfussenegger/nvim-jdtls)

 Mine is:
```
local home = vim.fn.getenv("HOME")

return {
	cmd = {
		"java",
		"-Declipse.application=org.eclipse.jdt.ls.core.id1",
		"-Dosgi.bundles.defaultStartLevel=4",
		"-Declipse.product=org.eclipse.jdt.ls.core.product",
		"-Dlog.protocol=true",
		"-Dlog.level=ALL",
		"-Xms1g",
		"--add-modules=ALL-SYSTEM",
		"--add-opens",
		"java.base/java.util=ALL-UNNAMED",
		"--add-opens",
		"java.base/java.lang=ALL-UNNAMED",
		"-jar",
		home .. "/.local/share/nvim/mason/packages/jdtls/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar",
		"-configuration",
		home .. "/.local/share/nvim/mason/packages/jdtls/config_linux",
		"-data",
		home .. "/.local/share/nvim/mason/packages/jdtls/workspace",
	},
	root_dir = function(fname)
		return require("lspconfig").util.root_pattern("pom.xml", "gradle.build", ".git")(fname) or vim.fn.getcwd()
	end,
}
```

**Comment by DasOhmoff** [comment]
@boningggg Thanks! That was exactly the issue.

I did not know that it needs to be configured, there was nothing in the mason doc or installation or so that told me that I need to configure something, I think it would be nice if its mentioned somewhere.
