### ISSUE TITLE
Missing documentation; How to update an installed server

### ISSUE THREAD

**Issue by supermacro** [williamboman/mason.nvim#405]
### Problem description

I have `typescript-language-server` installed, and when I run `:Mason` - I see a prompt telling me that there's a `new version available` ... however I don't know how to upgrade it via Mason. 

1. How do I upgrade servers via Mason?
2. Is there any documentation on this? Sorry if there is and I was unable to find it.

### Neovim version (>= 0.7)

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by linuxbrew@07b28abf8b55

### Operating system/version

Linux pop-os 5.19.0-76051900-generic #202207312230~1660780566~22.04~9d60db1 SMP PREEMPT_DYNAMIC Thu A x86_64 x86_64 x86_64 GNU/Linux

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Actual behavior

.

### Expected behavior

.

### Healthcheck output

```shell
.
```

**Comment by williamboman** [comment]
Hello! So to update all outdated packages you can press `U` when the window is open. You can also update a single outdated server by moving the cursor to it and pressing `u`. This info plus other keymaps are available in the help view:

<img width="201" alt="Screenshot 2022-09-11 at 19 04 20" src="https://user-images.githubusercontent.com/6705160/189540028-62165a59-6e8a-4c75-8e7c-5bc47e4f7932.png">
<img width="865" alt="Screenshot 2022-09-11 at 19 04 27" src="https://user-images.githubusercontent.com/6705160/189540031-1db7e607-8d95-45c1-b9d5-36ca53a0535c.png">
