### ISSUE TITLE
[New package]: up

### ISSUE THREAD

**Issue by Piotr1215** [williamboman/mason.nvim#414]
### Package name

vscode-up

### Package homepage

https://github.com/upbound/vscode-up

### Languages

typescript, yaml

### How is this package distributed?

As a vscode extension, the `up xpls serve` starts LSP that can be configured with `coc`, but I haven't found a way to port it to nvim LSP.

**Comment by williambotman** [comment]
Hello! Pull requests are always very welcomed to add new packages. If the distribution of the package is simple, the installation will most likely be so as well. See [CONTRIBUTING.md](https://github.com/williamboman/mason.nvim/blob/main/CONTRIBUTING.md) and the [API reference](https://github.com/williamboman/mason.nvim/blob/main/doc/reference.md) for more details! You may also use existing packages as reference.
