### ISSUE TITLE
fantomas not installing 

### ISSUE THREAD

**Issue by WillEhrendreich** [williamboman/mason.nvim#418]
### I've made an initial investigation into the error myself

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

I can install fantomas in my commandline by doing 
dotnet tool install fantomas-tool -g 
or 
dotnet tool install fantomas-tool -g --prerelease

but when mason tries to do it i get this error, which i don't fully understand, but i thought i'd create the issue so someone could look into it. 

C:\Temp\mq1zgyri.0nr\restore.csproj : error NU1212: Invalid project-package combination for Fantomas 4.7.9. DotnetToolReference project style can only contain references of the DotnetTool type 

### Neovim version (>= 0.7)

NVIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az276-503

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info

### Operating system/version

Windows 10 

### Affected packages

fantomas

### Actual behavior

it give the error message C:\Temp\mq1zgyri.0nr\restore.csproj : error NU1212: Invalid project-package combination for Fantomas 4.7.9. DotnetToolReference project style can only contain references of the DotnetTool type

### Expected behavior

installing fantomas

### Mason output

```Text
Failed
    ⟳ fantomas
      Fantomas is an opinionated code formatter for f#
      
      homepage   https://fsprojects.github.io/fantomas 
      languages  F#                                    
      categories Formatter                             
      
      C:\Temp\inc0cms4.c1n\restore.csproj : error NU1212: Invalid project-package combination for Fantomas 4.7.9. DotnetToolReference project style can only contain references of the DotnetTool type 
      Tool 'fantomas' failed to update due to the following:
      The tool package could not be restored.
      Tool 'fantomas' failed to install. This failure may have been caused by:
      
      * You are attempting to install a preview release and did not use the --version option to specify the version.
      * A package by this name was found, but it was not a .NET tool.
      * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
      * You mistyped the name of the tool.
      
      For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
      spawn: dotnet failed with exit code 1 and signal 0.
```

### Installation log

```Text
[DEBUG 9/14/2022 10:36:34 AM] ...\pack\packer\start\mason.nvim/lua\mason-core\process.lua:162: Spawned with pid 18292
[DEBUG 9/14/2022 10:36:34 AM] ...\pack\packer\start\mason.nvim/lua\mason-core\process.lua:148: Job pid=18292 exited with exit_code=22, signal=0
[INFO  9/14/2022 10:36:34 AM] ...acker\start\mason.nvim/lua\mason-core\installer\init.lua:110: Executing installer for Package(name=fantomas)
[DEBUG 9/14/2022 10:36:34 AM] ...\site\pack\packer\start\mason.nvim/lua\mason-core\fs.lua:71: fs: mkdirp C:\.local\share\nvim-data\mason\.packages\fantomas
[DEBUG 9/14/2022 10:36:34 AM] ...\pack\packer\start\mason.nvim/lua\mason-core\process.lua:116: Spawning cmd="dotnet", spawn_opts={
  args = { "tool", "update", "--tool-path", ".", "fantomas" },
  cwd = "C:\\.local\\share\\nvim-data\\mason\\.packages\\fantomas"
}
```

### Healthcheck

```Text
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - OK: **Go**: `go version go1.18.3 windows/amd64`
  - WARNING: **cargo**: unsupported version `cargo 1.53.0 (4369396ce 2021-04-27)`. Some cargo installations require Rust >= 1.60.0.
  - WARNING: **luarocks**: unsupported version `luarocks 2.0.2
`. Luarocks version must be >= 3.0.0.
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.5.5`
  - OK: **node**: `v17.9.0
`
  - WARNING: **python3**: not available
  - WARNING: **pip3**: not available
  - OK: **javac**: `javac 11.0.12
`
  - OK: **java**: `openjdk version "11.0.12" 2021-07-20
`
  - WARNING: **julia**: not available
  - ERROR: **wget**: not available
  - OK: **curl**: `curl 7.79.1 (Windows) libcurl/7.79.1 Schannel
`
  - ERROR: **gzip**: not available
  - OK: **tar**: `bsdtar 3.5.2 - libarchive 3.5.2 zlib/1.2.5.f-ipp 
`
  - OK: **python**: `Ok`
  - OK: **pip**: `pip 21.2.4 from C:\Python310\lib\site-packages\pip (python 3.10)

`
  - OK: **JAVA_HOME**: `openjdk version "18" 2022-03-22
`
  - OK: GitHub API rate limit. Used: 45. Remaining: 15. Limit: 60. Reset: 9/14/2022 10:36:36 AM.
```

**Comment by WillEhrendreich** [comment]
perhaps @adelarsq has some insight?

**Comment by adelarsq** [comment]
@WillEhrendreich Yes, there is something wrong with the current version. Using like this works?

```
:MasonInstall fantomas@5.0.0-beta-010
```

**Comment by williamboman** [comment]
I wonder if we should default to the latest beta version if no version is supplied? I'm not particularly knowledgable about dotnet in general so at face value that error tells me absolutely nothing. Happy to receive suggestions to potential improvements in [how dotnet tools are installed](https://github.com/williamboman/mason.nvim/blob/d39e46db31c9b2eee458ca59a814ebc4fe8a5bd5/lua/mason-core/managers/dotnet/init.lua#L31-L42)

**Comment by WillEhrendreich** [comment]
That works, @adelarsq , thanks.

**Comment by adelarsq** [comment]
@williamboman Appears that the problem occurs because the project was renamed (https://github.com/fsprojects/fantomas/issues/2174).

> I wonder if we should default to the latest beta version if no version is supplied?

For now I think that this is the best option.

**Comment by adelarsq** [comment]
@williamboman No action will be necessary. Today Fantomas 5 was released and installation it's working as expected.
