### ISSUE TITLE
[New package]: pyright-python

### ISSUE THREAD

**Issue by baco** [williamboman/mason.nvim#424]
### Package name

pyright-python

### Package homepage

https://github.com/RobertCraigie/pyright-python

### Languages

python

### How is this package distributed?

pip

It is a wrapper **in Python** around the installation of `pyright`.

Since the `pyright` LSP server is a tool for those who develop in Python and makes more sense, as a Python developer, to have all the tooling needed already installed (i.e. Python + pip), instead of the tooling for a language we are not developing in (i.e. Node + npm); it becomes obvious why this package is the first choice to provide `pyright`s LSP completion when developing in python for those who never need TypeScript.

**Comment by williambotman** [comment]
Hello! Pull requests are always very welcomed to add new packages. If the distribution of the package is simple, the installation will most likely be so as well. See [CONTRIBUTING.md](https://github.com/williamboman/mason.nvim/blob/main/CONTRIBUTING.md) and the [API reference](https://github.com/williamboman/mason.nvim/blob/main/doc/reference.md) for more details! You may also use existing packages as reference.

**Comment by williamboman** [comment]
Hello! Thanks for the PR! I'm not too sure about this one. It seems to just be a CLI wrapper around the `pyright` npm package. It locally downloads node & npm if they don't exist on PATH. I think having two packages for pyright will lead to a lot of confusion, with questionable benefits if you ask me. If people want to use the pyright-python package they'll have to do so outside of Mason.

**Comment by baco** [comment]
Hmm.. well... that's the whole point, to have something install all the tooling (foreign to the language you are pretending to develop in) for you, to ease the use of such language.

Using myself as an example:
![pyright fails to install without npm](https://user-images.githubusercontent.com/102958/190632483-0d330fbe-cc4a-4983-9c16-091ed9025d37.png)
![Mason, no npm](https://user-images.githubusercontent.com/102958/190638679-29fa0651-75ae-4115-a573-81e07f0d5da1.png)


So... for my daily work, I don't need to install or use all the Node+npm stuff. There is no TypeScript/Javascript code in the project I am in, and I have no need to install that and all it's dependencies.

I came to `mason.nvim` in order to not have to handle all the dependencies and the installation myself, to get, somehow, the same easy experience you get using VSCode.

I understand the dilemma of having two packages with fairly the same name. I think there are two other possibilities to this problem:
1. Only having pyright-python as the only provider of `pyright`. Moreover considering that is the same `pyright` within, and the developer of pyright-python keeps good track of `pyright` releases to have it wrapped immediately.
2. Make `mason.nvim` do the same work pyright-python does, not forcing the user to have Node+npm installed to achieve Python completion.

**Comment by williamboman** [comment]
Yeah I understand. For now, Node (and npm) is part of the base requirements that you'll have to manage externally. Likely Node will be added as a Mason package pretty soon, due to how common of a runtime it is among the available packages.

**Comment by baco** [comment]
Sorry to read about that... already ditched CoC.nvim, in favor of Mason, for such requirement.

**Comment by acid-bong** [comment]
The conflict resolution is actually simpler: Pyright wrapper exposes 2 new executables, `pyright-python` and `pyright-python-langserver`. However, that'll require synchronous commits to `neovim/nvim-lspconfig` with a copy of the Pyright preset, that explicitly uses the new name, and to the registry repo instead of here. Which imma try to do
