### ISSUE TITLE
Specify a version for a language server

### ISSUE THREAD

**Issue by itmecho** [williamboman/mason.nvim#425]
### I've searched open issues for similar requests

- [X] Yes

### Is your feature request related to a problem? Please describe.

The project I work on is locked to node 12. I know this is old and no longer supported but it's a big piece of work to upgrade.

The `typescript-language-server` after `v1.0.0` requires node >=14 so it no longer works. I manually edited the `package.json` in the mason folder for the server and reinstalled with `npm` and not it works.

### Describe the solution you'd like

It would be nice to be able to manually specify a version for a language server somewhere. I'm not sure what the best process for doing this would be though.

### Describe potential alternatives you've considered

Manually editing the `package.json` to use the required version.

**Comment by williamboman** [comment]
Hello! You can specify which version to install like so `:MasonInstall typescript-language-server@0.11.2`

**Comment by itmecho** [comment]
Thanks for the reply! This does work, however it shows up in the upgrade list as out of date. It would be nice to be able to pin the version somehow.

Also when I start a fresh install of nvim with my dotfiles, mason automatically installs the language servers I have configured in the setup function which pulls the latest version so it's a manual step after the initial install.
