### ISSUE TITLE
MasonInstall fails if nvim folder is not present in .cache

### ISSUE THREAD

**Issue by mokafolio** [williamboman/mason.nvim#430]
### Problem description

I just freshly installed nvim and mason on clean Ubuntu 22.04. When I tried to run `:MasonInstall` with any package, I got a ton of lua errors telling me, that `~/.cache/nvim/mason.log` could not be opened. After checking the contents of `~/.cache` I noticed that no nvim folder was present. I assume that the script needs to create the folder if it does not exist yet before it tries to create `mason.log`. Adding the folder by hand fixed the issue.

### Neovim version (>= 0.7)

NVIM v0.8.0-dev-1088-gbd4eca114
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system/version

Ubuntu 22.04

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Actual behavior

`:MasonInstall` fails on a fresh nvim install.

### Expected behavior

It should not fail :)

### Healthcheck output

```shell
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - WARNING: **Go**: not available
  - WARNING: **cargo**: not available
  - WARNING: **luarocks**: not available
  - OK: **Ruby**: `ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]`
  - OK: **RubyGem**: `3.3.5`
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - ERROR: **npm**: not available
  - ERROR: **node**: not available
  - OK: **python3**: `Python 3.10.4`
  - OK: **pip3**: `pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)`
  - OK: **javac**: `javac 11.0.16`
  - OK: **java**: `openjdk version "11.0.16" 2022-07-19`
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.2 built on linux-gnu.`
  - OK: **curl**: `curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.13`
  - OK: **gzip**: `gzip 1.10`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 1. Remaining: 59. Limit: 60. Reset: Thu 15 Sep 2022 08:13:59 PM PDT.
```

**Comment by williamboman** [comment]
Repro in CI: https://github.com/williamboman/mason.nvim/actions/runs/3193346268/jobs/5211813135.

**Comment by williamboman** [comment]
So this was due to the location of `$NVIM_LOG_FILE` changing to reside within `$XDG_STATE_HOME` instead of `$XDG_CACHE_HOME` in `0.8.0`. Neovim makes sure the directory to `$NVIM_LOG_FILE` exists when starting. Up until #516, Mason would use `$XDG_CACHE_HOME` for its log file, and fail to create its log file because Neovim had written its log file to another directory.
