### ISSUE TITLE
Good looking window popup

### ISSUE THREAD

**Issue by karma-riuk** [williamboman/mason.nvim#453]
### Problem description

Hello, I am sorry to create an issue for such a stupid matter, but I was wondering how you got such a great looking popup window (the one that appears when you run `:Mason`). Mine looks pretty dull and I was look for a way to make it look better.

I tried googling it but struggled a lot to find relevant results, so here I am.

Is it just a colorscheme / theme thing or is there a plugin to make it look better?

### Neovim version (>= 0.7)

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui

### Operating system/version

Linux 5.18.11-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 12 Jul 2022 15:40:51 +0000 x86_64 GNU/Linux

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Actual behavior

My window looks bad, as shown in the first screenshot below.

### Expected behavior

As explained above, to make it look good like in the README.md screenshots

### Healthcheck output

```shell
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - OK: **Go**: `go version go1.18.3 linux/amd64`
  - OK: **cargo**: `cargo 1.62.0`
  - OK: **luarocks**: `/usr/bin/luarocks 3.9.1`
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.4.0`
  - OK: **node**: `v18.5.0`
  - OK: **python3**: `Python 3.10.5`
  - OK: **pip3**: `pip 22.1.2 from /usr/lib/python3.10/site-packages/pip (python 3.10)`
  - OK: **javac**: `javac 18.0.1.1`
  - OK: **java**: `openjdk version "18.0.1.1" 2022-04-22`
  - OK: **julia**: `julia version 1.7.2`
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: **curl**: `curl 7.84.0 (x86_64-pc-linux-gnu) libcurl/7.84.0 OpenSSL/1.1.1q zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.48.0`
  - OK: **gzip**: `gzip 1.12`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 6. Remaining: 54. Limit: 60. Reset: Wed 21 Sep 2022 21:04:16 CEST.
```

### My version of the window

![actual behaviour](https://user-images.githubusercontent.com/30158492/191580884-87ca625b-7a27-47c9-a35c-80d93751e6b3.png)

### The result I would like to achieve (picture took from the README.md)

![wanted result](https://user-images.githubusercontent.com/6705160/177617680-d62caf26-f253-4ace-ab57-4b590595adca.png)

**Comment by williamboman** [comment]
Hello! Hm, do you have `:h 'termguicolors'` enabled (`:set termguicolors`)?

**Comment by karma-riuk** [comment]
I knew that whatever the answer was going to be, I was going to feel embarrassed... 

Enabling `termguicolors` indeed fixed my "issue".

Thanks a lot for your quick response!

**Comment by williamboman** [comment]
Great 👍 !

**Comment by brymon68** [comment]
You rock dude. Thanks @williamboman
