### ISSUE TITLE
Download `shfmt` from GitHub releases

### ISSUE THREAD

**Issue by latipun7** [williamboman/mason.nvim#475]
### Discussed in https://github.com/williamboman/mason.nvim/discussions/468

<div type='discussions-op-text'>

<sup>Originally posted by **latipun7** September 27, 2022</sup>
Currently [`shfmt`](https://github.com/mvdan/sh) is installed using `go`. I'm not `go` developer so installing `go` which is so huge imo only for installing `shfmt` is kinda overkill.

[`shfmt` GitHub release](https://github.com/mvdan/sh/releases) already has the latest version of pre-build of that tools, but it's not zip or tarball. They are the executable itself. So, after downloading that, it just needs to be renamed into `shfmt` or `shfmt.exe` and set the executable.

Does this approach could be supported? Thank you very much for this great tool.</div>

**Comment by williamboman** [comment]
Done already in #472!
