### ISSUE TITLE
Installs old versions using go install (goimports-reviser)

### ISSUE THREAD

**Issue by akarl** [williamboman/mason.nvim#484]
### I believe this to be an issue that should be addressed by maintainers of mason.nvim.

- [X] Yes

### Why do you think this is an issue with mason.nvim?

Mason installs an old version of `goimports-reviser` which is not working properly with the default config of `null-ls`

### Neovim version (>= 0.7)

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

Darwin LM410 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

### I've manually reviewed logs to find potential errors

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Affected packages

goimports-reviser

### Problem description

When mason installs `goimports-reviser` it installs the latest `v1.x.x` version which is not correct.

When using `go install` the major version is in the path. So to install the latest version we need to do `go install github.com/incu6us/goimports-reviser/v3`.

This can be fixed by updating https://github.com/williamboman/mason.nvim/blob/main/lua/mason-registry/goimports-reviser/init.lua#L16. However any package in the registry that uses `mason-core.managers.go` would have the same issue. And when doing it that way we need to update the registry on every new major version.

And there is no way that I know of to say that you want the "latest" major version when using `go install`.

### Steps to reproduce

1. `MasonInstall goimports-reviser`
2. Add `null_ls.builtins.formatting.goimports_reviser` to null-ls config.
3. `:lua vim.lsp.buf.formatting_seq_sync({}, 5000)`.
4. File not formatted. Check `:NullLsLog`.

### Actual behavior

File not formatted.

### Expected behavior

File formatted.

### Healthcheck

```Text
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - OK: **Go**: `go version go1.19.1 darwin/amd64`
  - OK: **cargo**: `cargo 1.62.0 (a748cf5a3 2022-06-08)`
  - OK: **luarocks**: `/usr/local/bin/luarocks 3.9.1`
  - OK: **Ruby**: `ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]`
  - OK: **RubyGem**: `3.0.3.1`
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.19.1`
  - OK: **node**: `v18.9.1`
  - OK: **python3**: `Python 3.10.6`
  - OK: **pip3**: `pip 22.2.2 from /usr/local/lib/python3.10/site-packages/pip (python 3.10)`
  - WARNING: **javac**: not available
  - WARNING: **java**: not available
  - WARNING: **julia**: not available
  - ERROR: **wget**: not available
  - OK: **curl**: `curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.45.1`
  - OK: **gzip**: `Apple gzip 353.100.22`
  - OK: **tar**: `bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
  - OK: **bash**: `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 4. Remaining: 56. Limit: 60. Reset: Fri Sep 30 11:33:29 2022.
```

### Screenshots or recordings

`:NullLsLog` output:
```
[TRACE Fri Sep 30 10:33:59 2022] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:209: error output: flag provided but not defined: -output
Usage of /Users/andreas/.local/share/nvim/mason/bin/goimports-reviser:
  -file-path string
    	File path to fix imports(ex.: ./reviser/reviser.go). Required parameter.
  -project-name string
    	Your project name(ex.: github.com/incu6us/goimports-reviser). Required parameter.
  -rm-unused
    	Remove unused imports. Optional parameter.
  -set-alias
    	Set alias for versioned package names, like 'github.com/go-pg/pg/v9'. In this case import will be set as 'pg "github.com/go-pg/pg/v9"'. Optional parameter.
```

**Comment by akarl** [comment]
Cool! The general problems with installing go tools the way we do here still exist though. But perhaps that should be another issue?

I'll be happy to help if we can come up with a good solution. Perhaps I should give it some thought.

**Comment by williamboman** [comment]
I actually took a look at that as well. It does seem to be a potential source of issues with go-based packages, but none of the remaining ones suffer from this as none of them include their major version in the mod name. Not sure how it best could be mitigated, and tbh it strikes me as a pretty odd thing to do? Maybe there's a solid reason I'm not seeing. Anyways, any suggestions are welcomed!

**Comment by akarl** [comment]
Yes, it is a bit odd but that is how it's done in Go. I don't really have a good solution except updating `mason.nvim` when new major versions are released.
