### ISSUE TITLE
checkhealth hint dismatch with work way

### ISSUE THREAD

**Issue by aarthurddragon** [williamboman/mason.nvim#498]
### I've made an initial investigation into the error myself

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

I am a windows platform user. 
I tried to download rust-analyzer by mason, but always failed because of the problem of unpacking the package.
And then I use checkhealth command to check if there are any errors.
Mason told me there are no gzip avialable.
then I downloaded the gzip and added the path to enviroument variables.
but that was still not work.
Finally, I found that the mason source code use 7z utility insteaed of gzip to unzip the package.
However, checkhealth still indicates that it depends on gzip.

### Neovim version (>= 0.7)

NVIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az276-503

### Operating system/version

windows

### Affected packages

All

### Actual behavior

the declared unzipping utility does not work properly.

### Expected behavior

Maybe the dependency of 7z should present at cheackhealth output.

### Installation log

```Text
the log has been cleared...
```

### Healthcheck

```Text
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - WARNING: **Go**: not available
  - OK: **cargo**: `cargo 1.64.0 (387270bc7 2022-09-16)`
  - WARNING: **luarocks**: not available
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.8.0`
  - OK: **node**: `v18.0.0
`
  - WARNING: **python3**: not available
  - WARNING: **pip3**: not available
  - OK: **javac**: `javac 17.0.1
`
  - OK: **java**: `java version "17.0.1" 2021-10-19 LTS
`
  - WARNING: **julia**: not available
  - ERROR: **wget**: not available
  - OK: **curl**: `curl 7.83.1 (Windows) libcurl/7.83.1 Schannel
`
  - OK: **gzip**: `gzip 1.10
`
  - OK: **tar**: `bsdtar 3.5.2 - libarchive 3.5.2 zlib/1.2.5.f-ipp bz2lib/1.0.6 
`
  - WARNING: **python**: not available
  - WARNING: **pip**: not available
  - OK: **JAVA_HOME**: `java version "17.0.1" 2021-10-19 LTS
`
```

**Comment by williamboman** [comment]
Hello! `gzip` support for Windows was added in #501, also the health check was hopefully made clearer as well
