### ISSUE TITLE
Mason should add it's path to the end of vim.env.PATH instead of start

### ISSUE THREAD

**Issue by lucario387** [williamboman/mason.nvim#509]
### Problem description

Sometimes, I have some packages installed through Mason, and it takes precedence over packages in `$PATH`. 
An example of this is `ocaml-lsp`. It takes precedence over the installed one inside the opam switch, making the lsp unable to run at all.
I believe it would be better to append the path of mason to `$PATH`, instead of prepending it like currently

Reproduction steps:
- Install Mason
- Check `vim.env.PATH`

### Neovim version (>= 0.7)

NVIM v0.9.0-dev-16-g56998feeb
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by root

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info

### Operating system/version

Linux spacegliders 5.19.13-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 04 Oct 2022 14:36:58 +0000 x86_64 GNU/Linux

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Actual behavior

`vim.env.PATH` is `~/.local/share/nvim/mason/bin:$PATH`

### Expected behavior

It should be `$PATH:~/.local/share/nvim/mason/bin`

### Healthcheck output

```shell
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - OK: **Go**: `go version go1.19.1 linux/amd64`
  - OK: **cargo**: `cargo 1.61.0 (a028ae4 2022-04-29)`
  - WARNING: **luarocks**: not available
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.16.0`
  - OK: **node**: `v16.15.0`
  - OK: **python3**: `Python 3.10.7`
  - OK: **pip3**: `pip 22.2.2 from /usr/lib/python3.10/site-packages/pip (python 3.10)`
  - OK: **javac**: `javac 17.0.4.1`
  - OK: **java**: `openjdk version "17.0.4.1" 2022-08-12`
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: **curl**: `curl 7.85.0 (x86_64-pc-linux-gnu) libcurl/7.85.0 OpenSSL/1.1.1q zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.3 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.50.0`
  - OK: **gzip**: `gzip 1.12`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: **python3_host_prog**: `Python 3.10.7`
  - OK: **JAVA_HOME**: `openjdk version "17.0.4.1" 2022-08-12`
  - OK: GitHub API rate limit. Used: 4. Remaining: 4996. Limit: 5000. Reset: 2022年10月05日 14時23分05秒.
```

**Comment by williamboman** [comment]
Hello! This could probably be made into a setting. Any reason why you keep ocaml-lsp installed via Mason though, can't you just uninstall it?

**Comment by lucario387** [comment]
@williamboman hello, sorry for the late reply.
I wrote ocaml-lsp as an example of an issue that I had before. I did remove it after noticing it's Mason's ocaml-lsp that was causing problems. 
Only now do I think there are probably more language-specific executables that will be affected by the prepending of mason path, so that's why I raised the issue yesterday.
Tyvm for the path update :+1:
