### ISSUE TITLE
mason filetype breaks eruby filetype detection

### ISSUE THREAD

**Issue by mehalter** [williamboman/mason.nvim#535]
### Problem description

Hi, I am the maintainer of AstroNvim and I have a user that has an interesting bug report and I figured I would ask you if you had any ideas. It seems that when this user is working with `.html.erb` files with a specific type of string in it the fieltype detectionnn starts detecting the file as `mason` instead of `eruby`. Is there any chance you are checking for something along the lines of `<%= %>` for setting the filetype of a buffer to `mason`?

Relevant issue: https://github.com/AstroNvim/AstroNvim/issues/1051

## Steps to reproduce:

1. Create a file `test.html.erb`
2. See that it's filetype is `eruby` with `:set ft`
3. Write to it `<%= %>`
4. Reopen the file and see that the filetype is `mason` with `:set ft`

### Neovim version (>= 0.7)

NVIM v0.8.0                                                                                                                    
Build type: Release                                                                                                            
LuaJIT 2.1.0-beta3                                                                                                             
Compiled by builduser

### Operating system/version

Linux balena-arch-thinkpad-cx1 5.19.13-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 04 Oct 2022 14:36:58 +0000 x86_64 GNU/Linux

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Actual behavior

`:set ft` outputs `mason`

### Expected behavior

`:set ft` should output `eruby`

### Healthcheck output

```shell
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - OK: **Go**: `go version go1.19.2 linux/amd64`
  - WARNING: **cargo**: not available
  - WARNING: **luarocks**: not available
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - OK: **Composer**: `Composer version 2.4.2 2022-09-14 16:11:15`
  - OK: **PHP**: `PHP 8.1.11 (cli) (built: Sep 29 2022 16:31:09) (NTS)`
  - OK: **npm**: `8.11.0`
  - OK: **node**: `v16.16.0`
  - OK: **python3**: `Python 3.10.7`
  - OK: **pip3**: `pip 22.2.2 from /usr/lib/python3.10/site-packages/pip (python 3.10)`
  - OK: **javac**: `Ok`
  - OK: **java**: `openjdk version "1.8.0_345"`
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: **curl**: `curl 7.85.0 (x86_64-pc-linux-gnu) libcurl/7.85.0 OpenSSL/1.1.1q zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.3 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.50.0`
  - OK: **gzip**: `gzip 1.12`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 161. Remaining: 4839. Limit: 5000. Reset: Mon 10 Oct 2022 10:04:06 AM EDT.
```

### Screenshots

![2022-10-10_09:18:37_screenshot](https://user-images.githubusercontent.com/1591837/194875634-ffa2b6e3-c40d-4346-8018-20adfcd423ff.png)

**Comment by williamboman** [comment]
Hello! There's no filetype detection done by mason.nvim. `mason` is indeed the filetype of the UI window, this filetype also happens to be a ["native" filetype](https://github.com/neovim/neovim/blob/09dffb9db7d16496e55e86f78ab60241533d86f6/runtime/lua/vim/filetype/detect.lua#L1477) for the Perl-based HTML templating language [Mason](https://metacpan.org/pod/Mason). Neovim will, as a last resort, look inside the contents of a file to try to figure out the filetype, and that pattern is what triggers `mason`.

I also can't really repro for `.html.erb` files because the extension match for `.erb` has precedence (which sets `&ft` to `eruby`). Have they customized their filetype detection somehow (like disabling parts of it or having `g:do_legacy_filetype = 1`)?

**Comment by mehalter** [comment]
hm this was the concern. Thanks for helping me discern this with the perl based templating language. I'll keep investigating. AstroNvim isn't modifying any of the filetype stuff to my knowledge. I need to start going through plugins to see if someone is doing something to modify the matching. Thanks again, sorry for the noise!

**Comment by williamboman** [comment]
Really weird! FWIW, I can repro if the file doesn't contain a known pattern (e.g. filename such as `.prettierrc`, absolute path like `/etc/hosts`, or extension like `index.html.erb`).

```vim
:e foobar
:i
<%= %>
.
:w
:e
:echo &ft
```

**Comment by mehalter** [comment]
Oh wow @williamboman I actually found quite an interesting result with debugging this. Not sure if you are interested, but figured I would share. I found several plugins in AstroNvim's core code that if I disable all of them it works completely fine with filetype detection. If I enable any single one of them then the filetype detection completely goes to crap. The one thing that all of these plugins share is that I'm lazy loading them on buffer reading with Packer. :O I have no idea why lazy loading a plugin one `BufRead` or `BufReadPost` is causing this but that's definitely the source of the weirdness!

**Comment by mehalter** [comment]
I have also confirmed that this behavior is completely new to Neovim v0.8 and is not present in earlier versions. I know there has been a lot of rewriting done to `filetype.lua` in core Neovim and that must have caused some weirdness :/ I will keep investigating because loading a plugin on the first time a file is read is pretty nice
