### ISSUE TITLE
Verbile installation fails missing configuration in verible/init.lua

### ISSUE THREAD

**Issue by Xyhlon** [williamboman/mason.nvim#536]
### I've made an initial investigation into the error myself

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

:MasonInstall verible
installation of verible formatter for systemverilog is not working. it seems like configurations in verible/init.lua are missing. see below for information

### Neovim version (>= 0.7)

NVIM v0.8.0-1210-gd367ed9b2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az505-656

Features: +acl +iconv +tui
See ":help feature-compile"

### Operating system/version

Linux archbob 5.19.13-arch1-1-surface #1 SMP PREEMPT_DYNAMIC Tue, 04 Oct 2022 20:05:48 +0000 x86_64 GNU/Linux

### Affected packages

verible

### Actual behavior

I got following error 
[INFO  Mon 10 Oct 2022 05:33:42 PM CEST] ...acker/start/mason.nvim/lua/mason-core/installer/init.lua:110: Executing installer for Package(name=verible)
[ERROR Mon 10 Oct 2022 05:33:42 PM CEST] ...acker/start/mason.nvim/lua/mason-core/installer/init.lua:146: Installation failed for Package(name=verible) error="...acker/start/mason.nvim/lua/mason-core/installer/init.lua:113: ...start/mason.nvim/lua/mason-core/managers/github/init.lua:89: expected asset_file to be a string"

debug attempt modifications
github/init.lua
```lua
function P(value)
    print(vim.inspect(value))
    return value
end
---@async
---@param opts {repo: string, version: Optional?, asset_file: string|fun(release: string):string}
function M.release_file(opts)
    local source = M.release_version(opts)
    ---@type string
    local asset_file
    print(debug.traceback())
    P(opts)
    if type(opts.asset_file) == "function" then
        asset_file = opts.asset_file(source.release)
    else
        assert(P(type(P(opts.asset_file))) == "string", "expected asset_file to be a string")
        asset_file = opts.asset_file --[[@as string]]
```
output of debugging:
```
stack traceback:
^I...start/mason.nvim/lua/mason-core/managers/github/init.lua:84: in function 'release_file'
^I...start/mason.nvim/lua/mason-core/managers/github/init.lua:130: in function 'untarxz_release_file'
^I...ker/start/mason.nvim/lua/mason-registry/verible/init.lua:22: in function 'when'
^I...ker/start/mason.nvim/lua/mason-registry/verible/init.lua:19: in function <...ker/start/mason.nvim/lua/mason-registry/verible/init.lua:17>
{
  repo = "chipsalliance/verible"
}
nil
"nil"
```
it seams like there is configurations missing in verible/init.lua

### Expected behavior

should install without error

### Installation log

```Text
[INFO  Mon 10 Oct 2022 05:33:42 PM CEST] ...acker/start/mason.nvim/lua/mason-core/installer/init.lua:110: Executing installer for Package(name=verible)
[ERROR Mon 10 Oct 2022 05:33:42 PM CEST] ...acker/start/mason.nvim/lua/mason-core/installer/init.lua:146: Installation failed for Package(name=verible) error="...acker/start/mason.nvim/lua/mason-core/installer/init.lua:113: ...start/mason.nvim/lua/mason-core/managers/github/init.lua:89: expected asset_file to be a string"
```

### Healthcheck

```Text
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - OK: **Go**: `go version go1.19.2 linux/amd64`
  - OK: **cargo**: `cargo 1.64.0 (387270bc7 2022-09-16)`
  - OK: **luarocks**: `/usr/bin/luarocks 3.9.1`
  - OK: **Ruby**: `ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux]`
  - OK: **RubyGem**: `3.3.21`
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.19.2`
  - OK: **node**: `v18.10.0`
  - OK: **python3**: `Python 3.10.7`
  - OK: **pip3**: `pip 22.2.2 from /usr/lib/python3.10/site-packages/pip (python 3.10)`
  - OK: **javac**: `javac 11.0.16.1`
  - OK: **java**: `openjdk version "11.0.16.1" 2022-08-12`
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: **curl**: `curl 7.85.0 (x86_64-pc-linux-gnu) libcurl/7.85.0 OpenSSL/1.1.1q zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.3 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.50.0`
  - OK: **gzip**: `gzip 1.12`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 21. Remaining: 4979. Limit: 5000. Reset: Mon 10 Oct 2022 05:59:55 PM CEST.
```

**Comment by williamboman** [comment]
Hello! Verible is currently only supported on CentOS 7 and Ubuntu systems (due to which prebuilt artifacts are available). The particular error you're receiving (assertion failure) is due to some erroneous logic that was introduced recently. This was recently fixed so the error message you receive when installing should be clearer now.

**Comment by Xyhlon** [comment]
thank you for the information. just out of curiosity: what is necessary to support verible for arch?

**Comment by williamboman** [comment]
So it seems like their binaries should be compatible with any Linux/GNU system, #579 enables support on such systems.
