### ISSUE TITLE
NPM error when installing typescript-language-server

### ISSUE THREAD

**Issue by huge-pancake** [williamboman/mason.nvim#545]
### I've made an initial investigation into the error myself

- [ ] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

After installing mason.nvim with packer.nvim, when installing typescript-language-server, NPM gives an error: Invalid URL.

### Neovim version (>= 0.7)

NVIM v0.7.2
Build type: Release
Compiled by team+vim@tracker.debian.org
Features: +acl +iconv +tui
See ":help feature-compile"
   system vimrc file: "$VIM/sysinit.vim"
   fall-back for $VIM: "/usr/share/nvim"
Run :checkhealth for more info

### Operating system/version

Linux DESKTOP-8V4PU7E 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux

### Affected packages

Only tried typescript-language-server

### Actual behavior

.

### Expected behavior

LSP installed

### Mason output

```Text
in screenshots
```

### Installation log

```Text
npm failed with exit code 1 and signal 0
```

### Healthcheck

```Text
in screenshots
```

### Screenshots

![image](https://user-images.githubusercontent.com/73375859/195327391-692b18a8-0ec9-4bf0-b18c-0a9efeed51b6.png)

![image](https://user-images.githubusercontent.com/73375859/195327166-c27883ff-ca85-4e86-bd37-71ba9a00a3fe.png)

**Comment by williamboman** [comment]
Hello! You probably have a faulty proxy configuration (`$ npm config get proxy`).

**Comment by huge-pancake** [comment]
I have just found my proxy rules was updated many hours ago, so they were out of date, thank you.
