### ISSUE TITLE
The clangd cannot be downloaded

### ISSUE THREAD

**Issue by kbpoyo** [williamboman/mason.nvim#547]
### I've made an initial investigation into the error myself

- [X] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

The plugin clangd download path is incorrect and cannot be downloaded

### Neovim version (>= 0.7)

nvim v0.8
Build type: Release
luaJit 2.3.0

### Operating system/version

Linux vm01 5.15.0-48-generic #54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Affected packages

LSP

### Actual behavior

The plugin clangd download path is incorrect and cannot be downloaded

### Expected behavior

I want to download the clangd.

### Mason output

```Text
the download path is incorrect so there is no output.
```

### Installation log

```Text
This is not actually a bug
```

### Healthcheck

```Text
- OK: neovim version >= 0.7.0
  - WARNING: Go: not available
  - WARNING: cargo: not available
  - WARNING: luarocks: not available
  - WARNING: Ruby: not available
  - WARNING: RubyGem: not available
  - WARNING: Composer: not available
  - WARNING: PHP: not available
  - OK: npm: `8.19.2`
  - OK: node: `v16.18.0`
  - OK: python3: `Python 3.10.6`
  - WARNING: pip3: not available
  - WARNING: javac: not available
  - WARNING: java: not available
  - WARNING: julia: not available
  - OK: wget: `GNU Wget 1.21.2 在 linux-gnu 上编译。`
  - OK: curl: `curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/       2.3 OpenLDAP/2.5.13`
  - OK: gzip: `gzip 1.10`
  - OK: tar: `tar (GNU tar) 1.34`
  - OK: bash: `GNU bash，版本 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: sh: `Ok`
  - OK: GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: 2022年10月13日 星期四 01时02分12秒.
```

### Screenshots

![image](https://user-images.githubusercontent.com/86943232/195373412-9c496f22-de78-4b0f-b12b-0d0989e01eba.png)
![image](https://user-images.githubusercontent.com/86943232/195373803-059faf80-4c38-471a-a504-e5bb64f6a5c7.png)

**Comment by williamboman** [comment]
Hello! The URL is correct, you're probably running into network issues with GitHub.com's CDN. You could try changing the download URL template to use a proxy. You could try fastgit for example:

```lua
require("mason").setup {
  github = {
    download_url_template = "https://download.fastgit.org/%s/releases/download/%s/%s"
  }
}
```

**Comment by kbpoyo** [comment]
Thanks for the solution, it has been downloaded successfully

**Comment by outshow** [comment]
@williamboman 
I change the download URL template to use a proxy like
```
require("mason").setup {
  github = {
    download_url_template = "https://download.fastgit.org/%s/releases/download/%s/%s"
  }
}
```
but it is not working when I run commad :MasonInstall phpactor, it always clones phpactor from ```https://github.com/phpactor/phpactor``` directly.
Would you pls take a look into this?
