### ISSUE TITLE
Get Installation Path

### ISSUE THREAD

**Issue by mehalter** [williamboman/mason.nvim#578]
### I've searched open issues for similar requests

Yes

### Is your feature request related to a problem? Please describe.

When configuring some stuff like `nvim-dap` it is necessary to index into the installation directory of the package. Something like this:

```lua
    local BASHDB_DIR = vim.fn.stdpath "data" .. "/mason/packages/bash-debug-adapter/extension/bashdb_dir"
    dap.adapters.sh = { type = "executable", command = "bash-debug-adapter" }
    dap.configurations.sh = {
      {
        type = "sh",
        request = "launch",
        name = "Launch file",
        program = "${file}",
        cwd = "${fileDirname}",
        pathBashdb = BASHDB_DIR .. "/bashdb",
        pathBashdbLib = BASHDB_DIR,
        pathBash = "bash",
        pathCat = "cat",
        pathMkfifo = "mkfifo",
        pathPkill = "pkill",
        env = {},
        args = {},
      },
    }
```

Hardcoding the path here is not super great for longevity and future proofing if Mason ever goes through any sort of re-architecture or changes to how it manages the internal files and installation paths.

### Describe the solution you'd like

It would be great if when we get the get the package with something like `require("mason-registry").get_package("bash-debug-adapter")` if it also included the install path for the directory. Something like this:

```lua
require("mason-registry").get_package("bash-debug-adapter").install_path
```

which would return the equivalent of `vim.fn.stdpath("data") .. "/mason/packages/bash-debug-adapter"`

**Comment by williamboman** [comment]
Hey! Have you seen the [`Package:get_install_path()`](https://github.com/williamboman/mason.nvim/blob/main/doc/reference.md#packageget_install_path) method?

**Comment by mehalter** [comment]
Ah I looked through the docs and completely missed this. So sorry for the noise!

**Comment by williamboman** [comment]
No worries! That markdown doc is pretty unwieldly with poor formatting. The TOC helps a bit. I think it’d be nice to provide these extra lib files inside normalized `lib/` and `share/` directories, to avoid having to reach into internal package structures. Providing the bashdb dir could then look something like `mason.lib(”bashdbg”)` which would expand to e.g. `~/.local/share/nvim/mason/lib/bashdbg`.
