### ISSUE TITLE
Alow opt-out from using mason-registry.dev for release-info.

### ISSUE THREAD

**Issue by reegnz** [williamboman/mason.nvim#582]
### I've searched open issues for similar requests

Yes

### Is your feature request related to a problem? Please describe.

Please provide a way to opt-out and have the plugin call github and npm directly.

I don't want to use your mason-registry.dev as a middle-man to fetch release info for the few packages regular people install with Mason. (I don't think everyone is using every lsp all the time to max out api limits, except for your tests and some extreme use-cases).

I've encountered this issue (and realized you're using a middle-man service to get release info) when I tried to install a new LSP while being on a corporate VPN. I saw in #566 that other people using VPN-s also ran into this issue. Since I can reach github just fine from my VPN I thought it would make sense to opt-out of this middle-man mechanism and fetch the release infos straight from the source.

When I'm authenticated to github `:checkhealth mason` tells me I have 5000 requests, which should be more than enough for me and most people not wanting to install all tools all at once that mason manages.

I've opened this issue mainly because I'd imagine I'm not the only one who'd want mason to directly fetch release info from npm and github instead of using a middle-man service to do that for me.

### Describe the solution you'd like

Give an option to opt-out of using `mason-registry.dev` and just have the plugin pull release/version info straight to github and npm.

### Describe potential alternatives you've considered

I've considered forking the repo and adding this functionality in my fork so I can eliminate your middle-man service. I think it'd be possible to keep the fork up-to-date with the incoming changes if the mason-registry.dev API doesn't change drastically in the future.

**Comment by williamboman** [comment]
Hey! So mitigating rate limits was actually not one of the reasons behind introducing it, although I'm confident it will help in scenarios where you're behind shared IPs.

Without going into too much details, here are some of the key motivators:
- Aggregating paginated responses.
- Reducing dependency on system tooling.
- Performance and maintenance overhead. The signal-to-noise ratio in terms of the amount of processing required to access relatively simple data points is pretty poor.
- Enable new features, such as automated/structured management of packages which has been highly requested.

I definitely think it makes sense to be able to be able to customize this however, I'll look into decoupling interactions and introduce some data provider interface which would allow you to swap to an entirely client-based implementation!

**Comment by reegnz** [comment]
Thanks for that detailed answer! That does help put things into perspective.

I'm currently still struggling with LSP installers installing from a corporate VPN (your caching server simply doesn't resolve, last time I tried was today). So my primary motivator is not introducing additional URL dependencies, but rely on github only.

I think the paginated response is only for the use-case if you don't want to run the latest LSP versions, as latest shows up on the first response page.

You might reduce dependency on system tooling, but then introduce dependency on a system I have zero control of (while I do have complete control over the software running on my own system). I'd rather have system tools reimplemented in lua vs. reimplementing them in a service I have zero control of.

I do think it would make sense to allow for a 'degraded' mode of operation where I can simply install latest LSP versions even if I have no network access (or I don't want to replace dependance on local tools with dependence on a remotely hosted service outside my control).

**Comment by williamboman** [comment]
Would you mind trying branch `feat/provider-interface` (#601) and see if it resolves things for you? It should work with default settings but you might want to exclude the Mason API provider when setting up:

```lua
require("mason").setup {
  providers = {
    "client-only",
  }
}
```

**Comment by reegnz** [comment]
It's not working, but it was a bug. I filed a PR: #620

**Comment by williamboman** [comment]
Ah thanks! Was due to some last minute naming changes :)
