### ISSUE TITLE
Add package aliases to align with vim-lspconfig

### ISSUE THREAD

**Issue by hermitmaster** [williamboman/mason.nvim#602]
### I've searched open issues for similar requests

Yes

### Is your feature request related to a problem? Please describe.

Historically, I have been able to create a list of packages, in this case LSPs, to install and setup. This worked great with nvim-lsp-installer. However, it seems like several of the packages have been renamed and no longer align with the naming conventions in nvim-lspconfig. This is fine unless you try to use a different extension for installing packages, like [mason-tool-installer.nvim](https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim).

### Describe the solution you'd like

Package aliases that align with the nvim-lspconfig naming conventions would be satisfactory, but I'm open to alternatives. In short, add [this](https://github.com/williamboman/mason-lspconfig.nvim/blob/main/lua/mason-lspconfig/mappings/server.lua) to mason.nvim so other extensions can use it.

### Describe potential alternatives you've considered

I tried creating a table with the names from both sides (Mason and nvim-lspconfig), it would probably work, but gets messy quickly. I'm currently using mason-lspconfig.nvim, but it doesn't handle linters and such.

### Additional context

I want to be able to do something like this, but include linters and dap plugins:
```lua
  use {
    'neovim/nvim-lspconfig',
    requires = {
      'folke/which-key.nvim',
      'hrsh7th/cmp-nvim-lsp',
      'williamboman/mason.nvim',
      'williamboman/mason-lspconfig.nvim',
    },
    config = function()
      local capabilities = require('cmp_nvim_lsp').default_capabilities()
      local lspconfig = require('lspconfig')
      local servers = {
        'bashls',
        'cssls',
        'dockerls',
        'efm',
        'gopls',
        'html',
        'jsonls',
        'jsonnet_ls',
        'pyright',
        'sumneko_lua',
        'terraformls',
        'tflint',
        'tsserver',
        'volar',
        'yamlls',
      }

      require('mason').setup()
      require('mason-lspconfig').setup({
        ensure_installed = servers,
        automatic_installation = true,
      })

      for _, server in ipairs(servers) do
        local config = {
          capabilities = capabilities,
          on_attach = on_attach,
        }

        if server == 'efm' then
          config.filetypes = {}
          config.init_options = { documentFormatting = true }
          config.settings = {
            rootMarkers = { '.git/' },
            languages = {
              markdown = {
                { formatCommand = 'prettier --stdin --stdin-filepath ${INPUT}', formatStdin = true }
              },
              python = {
                { formatCommand = 'isort --profile black --quiet -', formatStdin = true },
                { formatCommand = 'black --quiet -', formatStdin = true },
              },
              sh = {
                { formatCommand = 'shfmt -bn -ci -i 2 -s', formatStdin = true },
                {
                  lintCommand = 'shellcheck -f gcc -x',
                  lintSource = 'shellcheck',
                  lintFormats = {
                    '%f:%l:%c: %trror: %m',
                    '%f:%l:%c: %tarning: %m',
                    '%f:%l:%c: %tote: %m',
                  },
                },
              },
              yaml = {
                { formatCommand = 'prettier --stdin --stdin-filepath ${INPUT}', formatStdin = true }
              },
            },
          }

          -- Get the filetypes from the languages table
          for k, _ in pairs(config.settings.languages) do
            table.insert(config.filetypes, k)
          end
        elseif server == 'sumneko_lua' then
          config.settings = {
            Lua = {
              diagnostics = {
                globals = { 'vim' },
              },
            },
          }
        elseif server == 'terraformls' then
          config.filetypes = { 'hcl', 'terraform' }
        end

        lspconfig[server].setup(config)
      end
    end,
  }
```

**Comment by williamboman** [comment]
Hello! Mason doesn't have any relation with nvim-lspconfig, package names follows the naming convention of the underlying packages. As you mention mason-lspconfig help translate between Mason and nvim-lspconfig - is this not working for you?

> I'm currently using mason-lspconfig.nvim, but it doesn't handle linters and such.

Hm what does linters have to do with nvim-lspconfig?

**Comment by hermitmaster** [comment]
I guess that's my point. As it stands, I'd have to install multiple plugins and write some glue code to be able to have a declarative config that supports installing/configuring LSP, DAP, linters, and formatters.

**Comment by williamboman** [comment]
I'm not sure I'm following how it relates to Mason (Mason will not ever integrate directly with other 3rd party plugins, there are however extension plugins such as `mason-lspconfig.nvim` for this).

If you want to use lspconfig names for auto-installing Mason packages you can do something like:

```lua
local mason_registry = require("mason-registry")
local mason_lspconfig_mappings  require("mason-lspconfig").get_mappings()
local servers = { "sumneko_lua", "tsserver", "rust_analyzer" }

-- Either manually install or use mason-tool-installer
for _, server in ipairs(servers) do
    local pkg = mason_registry.get_package(mason_lspconfig_mappings.lspconfig_to_mason[server])
    if not pkg:is_installed() then
        pkg:install()
    end
end
