### ISSUE TITLE
wgsl-analyzer doesn't start/show up in LspInfo

### ISSUE THREAD

**Issue by RegenJacob** [williamboman/mason.nvim#607]
### I've searched open issues for similar requests

Yes

### I've manually reviewed logs to find potential errors

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

I installed wgsl-analyzer but it doesn't show up in :LspInfo nor does it automatically start when i open a .wgsl file

### Expected behavior

wgsl-analyzer should show up in :LspInfo and automatically attach to the buffer

### Steps to reproduce

1. Install wgsl-analyzer
2. run :LspInfo

### Affected packages

wgsl-analyzer

### Neovim version (>= 0.7)

NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Operating system/version

Linux arch 6.0.5-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Wed, 26 Oct 2022 15:26:02 +0000 x86_64 GNU/Linux

### Healthcheck

```Text
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - WARNING: **Go**: not available
  - OK: **cargo**: `cargo 1.64.0 (387270bc7 2022-09-16)`
  - OK: **luarocks**: `/usr/bin/luarocks 3.9.1`
  - OK: **Ruby**: `ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux]`
  - OK: **RubyGem**: `3.3.23`
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.19.2`
  - OK: **node**: `v16.16.0`
  - OK: **python3**: `Python 3.10.8`
  - OK: **pip3**: `pip 22.3 from /usr/lib/python3.10/site-packages/pip (python 3.10)`
  - OK: **javac**: `javac 17.0.5`
  - OK: **java**: `openjdk version "17.0.5" 2022-10-18`
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: **curl**: `curl 7.86.0 (x86_64-pc-linux-gnu) libcurl/7.86.0 OpenSSL/1.1.1q zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.3 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.50.0`
  - OK: **gzip**: `gzip 1.12`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 7. Remaining: 53. Limit: 60. Reset: Fri 28 Oct 2022 09:46:22 PM CEST.
```

### Screenshots or recordings

![no wgsl](https://user-images.githubusercontent.com/53652728/198713441-4bec88ad-023d-4b6e-a92c-c153e1d75ee0.gif)

**Comment by williamboman** [comment]
How do you set up servers? I assume you're using `require("mason-lspconfig").setup_handlers()`, I saw that it's missing in the server mapping table there

**Comment by williamboman** [comment]
Might be fixed in https://github.com/williamboman/mason-lspconfig.nvim/pull/92

**Comment by RegenJacob** [comment]
Yes it works
