### ISSUE TITLE
ZLS new compression - zst instead of gz

### ISSUE THREAD

**Issue by candrewlee14** [williamboman/mason.nvim#618]
### I've searched open issues for similar requests

Yes

### I've manually reviewed logs to find potential errors

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

The latest version of `zls`, the language server for Zig, cannot be installed.
`zls` changed the release compression format from `*.tar.gz` to `*.tar.zst`.
Right now, when trying to install `zls`, I get a 404 URL error and installation fails.

### Expected behavior

Run `:LspInstall zls` and the download succeeds and decompresses from the right link.

### Steps to reproduce

1. `:LspInstall zls`

### Affected packages

zls

### Neovim version (>= 0.7)

NVIM v0.8.0-1210-gd367ed9b2
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

WSL2 Linux

### Healthcheck

```Text
N/A
```

**Comment by williamboman** [comment]
> All the releases of `zls` prior to 0.10.0 are still `.tar.gz` so I suppose it's easier to just support everything but `>= 0.10.0`? I'm assuming that `zls` team from now on are going to just release pre-build binaries using `zstd`.

Yeah installing versions prior to 0.10.0 won't really work anymore as the installation script doesn't account for historic distribution methods

**Comment by candrewlee14** [comment]
For an unstable language like Zig, installing a previous version of zls wouldn’t make much sense right now so that seems reasonable.

**Comment by chris-av** [comment]
I have this same issue. I would think that that the installation for the zst file would be automatic at this point correct? When I do `:LspInstall zls`, it is still trying to access a non-existent `tar.xz` file. How can I prompt mason to download the zst source instead? Using :

```
nvim: version 0.9.0
OS: Arch Linux
latest mason
```
