### ISSUE TITLE
Mason commands are not working

### ISSUE THREAD

**Issue by LauGaHo** [williamboman/mason.nvim#658]
### Discussed in https://github.com/williamboman/mason.nvim/discussions/357

<div type='discussions-op-text'>

<sup>Originally posted by **cheiktraore** August 30, 2022</sup>
Hi! I don't know why but I installed mason but no command is working. For instance I get this error message:
"E492: Not an editor command: Mason". This is how I installed it:
`  use({ "williamboman/mason.nvim" }) `
  `use({"williamboman/mason-lspconfig.nvim", after="mason.nvim"})` 
	`use({ "neovim/nvim-lspconfig", after="mason-lspconfig.nvim"}) -- enable LSP`</div>

I call the `.setup()` both `mason` and `mason-lspconfig`, but still not work.

```lua
   20 local mason_status, mason = pcall(require, "mason")
   19 if not mason_status then
   18   return
   17 end
   16
   15 local mason_lspconfig_status, mason_lspconfig = pcall(require, "mason_lspconfig")
   14 if not mason_lspconfig_status then
   13   return
   12 end
   11
   10 mason.setup()
    9
    8 mason_lspconfig.setup({
    7   ensure_installed = {
    6     "tsserver",
    5     "html",
    4     "cssls",
    3     "tailwindcss",
    2     "sumneko_lua",
    1   }
  21  })
```

**Comment by williamboman** [comment]
Are you certain that code is actually executing? Where is it located?

**Comment by LauGaHo** [comment]
I found out the problem and soluted it. thank you.

**Comment by Leviathans** [comment]
> ### Discussed in #357
> Originally posted by **cheiktraore** August 30, 2022 Hi! I don't know why but I installed mason but no command is working. For instance I get this error message: "E492: Not an editor command: Mason". This is how I installed it: ` use({ "williamboman/mason.nvim" })` `use({"williamboman/mason-lspconfig.nvim", after="mason.nvim"})` `use({ "neovim/nvim-lspconfig", after="mason-lspconfig.nvim"}) -- enable LSP`
> 
> I call the `.setup()` both `mason` and `mason-lspconfig`, but still not work.
> 
> ```lua
>    20 local mason_status, mason = pcall(require, "mason")
>    19 if not mason_status then
>    18   return
>    17 end
>    16
>    15 local mason_lspconfig_status, mason_lspconfig = pcall(require, "mason_lspconfig")
>    14 if not mason_lspconfig_status then
>    13   return
>    12 end
>    11
>    10 mason.setup()
>     9
>     8 mason_lspconfig.setup({
>     7   ensure_installed = {
>     6     "tsserver",
>     5     "html",
>     4     "cssls",
>     3     "tailwindcss",
>     2     "sumneko_lua",
>     1   }
>   21  })
> ```



> I found out the problem and soluted it. thank you.
same problem, how solute it?? bro
