### ISSUE TITLE
Windows: Spawning language server with cmd: `lua-languag-server`

### ISSUE THREAD

**Issue by cathaysia** [williamboman/mason.nvim#702]
### I've searched open issues for similar requests

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [ ] Yes

### Problem description

env: 
- Windows 11
- nvim 0.8.1 (installed by scoop)

error generation steps:

1. :MasonInstall lua-language-server
2. nvim 1.lua
3. see error

![图片](https://user-images.githubusercontent.com/42114817/204223665-38d48e98-8be4-4758-80a6-8dcb9a305467.png)

![图片](https://user-images.githubusercontent.com/42114817/204223730-93b13637-dac5-4d0d-83ef-c97e5e72b1bf.png)
![图片](https://user-images.githubusercontent.com/42114817/204223798-434e675a-278f-4188-b4a7-3a7fd2073e62.png)

I guess the reason is nvim cannot spawn a .bat script.

### Expected behavior

run lua-language-server normally

### Steps to reproduce

see above

### Neovim version (>= 0.7)

NVIM v0.8.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az30-11

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info

### Operating system/version

Microsoft Windows 11 Professional. 10.0.22621 No build 22621

### Healthcheck output

```shell
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - OK: **Go**: `go version go1.19.3 windows/amd64`
  - OK: **cargo**: `cargo 1.65.0 (4bc8f24d3 2022-10-20)`
  - WARNING: **luarocks**: not available
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.19.3`
  - OK: **node**: `v19.1.0
`
  - OK: **python3**: `Python 3.11.0
`
  - OK: **pip3**: `pip 22.3 from C:\Users\Drago\scoop\apps\python\current\Lib\site-packages\pip (python 3.11)

`
  - OK: **javac**: `javac 11.0.2
`
  - OK: **java**: `openjdk version "11.0.2" 2019-01-15
`
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.3 built on mingw32.
`
  - OK: **curl**: `curl 7.83.1 (Windows) libcurl/7.83.1 Schannel
`
  - OK: **gzip**: `gzip.exe" 1.3.12`
  - OK: **tar**: `bsdtar 3.5.2 - libarchive 3.5.2 zlib/1.2.5.f-ipp bz2lib/1.0.6 
`
  - OK: **python**: `Python 3.11.0
`
  - OK: **pip**: `pip 22.3 from C:\Users\Drago\scoop\apps\python\current\Lib\site-packages\pip (python 3.11)

`
  - OK: **7z**: `7-Zip 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15
`
  - OK: **JAVA_HOME**: `openjdk version "11.0.2" 2019-01-15
`
  - OK: GitHub API rate limit. Used: 1. Remaining: 59. Limit: 60. Reset: 11/28/2022 4:26:21 PM.
```

**Comment by williamboman** [comment]
Hello! I will assume you're not using `mason-lspconfig` (which is strongly recommended for Windows users). Neovim uses [libuv](https://github.com/libuv/libuv) to launch LSP servers. Libuv struggles to recognize `.cmd` and `.bat` scripts as executables in `PATH`. However, Mason will install all executables as `.cmd` scripts on Windows. Do you still experience issues if you install and set up [mason-lspconfg](https://github.com/williamboman/mason-lspconfig.nvim)?

**Comment by cathaysia** [comment]
I install mason-lspconfig, but the problem still.

![图片](https://user-images.githubusercontent.com/42114817/204411521-94d7678b-a238-4339-9dd7-5431b79d73c3.png)
![图片](https://user-images.githubusercontent.com/42114817/204411553-27f390e7-b8b6-42a8-969a-4cb706cc8e5e.png)

**Comment by cathaysia** [comment]
I had install mason on linux before, I remember I just need do

``lua
use {
    "williamboman/mason.nvim",
    "williamboman/mason-lspconfig.nvim",
    "neovim/nvim-lspconfig",
}

require("mason").setup()
require("mason-lspconfig").setup()
require("lspconfig").sumneko_lua.setup {}
```

then it should work. but on windows, I don't know what's the problem. :(

**Comment by williamboman** [comment]
Cool! And is the `lua-language-server` package actually installed?

**Comment by williamboman** [comment]
From the information provided I don't believe this is a Mason error, seeing as the language server is successfully installed. I'd try updating plugin versions (especially `lspconfig` and `mason-lspconfig`) and see if that fixes things. Alternatively you could try overriding the `cmd` when setting up `sumneko_lua`:

```lua
require("lspconfig").sumneko_lua.setup {
    cmd = { vim.fn.exepath("lua-language-server") }
}
```

**Comment by cathaysia** [comment]
emm, may I find the reason. I config sumeko_lua with cmd params:

```lua
    cmd = {
      'lua-language-server',
      '--locale="zh-cn"',
    },
```

but for windows, I need changed to 

```lua
    cmd = {
      'lua-language-server.cmd',
      '--locale="zh-cn"',
    },
```

it works now. But for now, a more good idea is use:

```lua
    cmd = {
      'lua-language-server' .. (function() if vim.fn.has('win32') then return '.cmd' end end)(),
      '--locale="zh-cn"',
    },

```

Thanks for your help. :)

**Comment by cathaysia** [comment]
> From the information provided I don't believe this is a Mason error, seeing as the language server is successfully installed (Mason is not directly involved in launching servers). I'd try updating plugin versions (especially `lspconfig` and `mason-lspconfig`) and see if that fixes things. Alternatively you could try overriding the `cmd` when setting up `sumneko_lua`:
> 
> ```lua
> require("lspconfig").sumneko_lua.setup {
>     cmd = { vim.fn.exepath("lua-language-server") }
> }
> ```

oops! your solution is better than me. :)
