### ISSUE TITLE
Download error (404) while installing zk

### ISSUE THREAD

**Issue by avucic** [williamboman/mason.nvim#753]
### I've searched open issues for similar requests

Yes

### I've manually reviewed logs to find potential errors

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [ ] Yes

### Problem description

        Downloading file "https://github.com/mickael-menu/zk/releases/download/v0.12.0/zk-v0.12.0-macos-x86_64.zip"...
        .../packer/opt/mason.nvim/lua/mason-core/installer/init.lua:122: ...cker/opt/mason.nvim/lua/mason-core/managers/std/init.lua:52: Failed to download file "https://github.com/mickael-menu/zk/releases/download/v0.12.0/zk-v0.12.0-macos-x86_64.zip".
        spawn: wget failed with exit code 8 and signal 0. 

### Expected behavior

to install zk package

### Steps to reproduce

Try to install latest zk package

### Affected packages

zk

### Neovim version (>= 0.7)

NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

Darwin MBP2 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

### Healthcheck

```Text
ERROR: No healthcheck found for "mason" plugin.
```

**Comment by bingocaller** [comment]
I also ran into this issue today. It seems that `zk`, for [version 0.12.0](https://github.com/mickael-menu/zk/releases/tag/v0.12.0), didn't provide a pre-built release for Intel architecture (`x86_64`), only for Apple Silicon (`arm64`).

[It seems this has been a problem in the past](https://github.com/mickael-menu/zk/issues/128) and that the author doesn't have unlimited access to an Intel Mac to build the release on, so [I went ahead and built a zip](https://github.com/mickael-menu/zk/issues/282) that hopefully can be added to the latest release.

**Comment by mickael-menu** [comment]
This should be fixed now. I'll make sure to release with Intel builds next times.

**Comment by bingocaller** [comment]
Awesome. Thanks @mickael-menu!

**Comment by williamboman** [comment]
Cool! Soon Mason will handle these kinds of changes in releases a bit more gracefully, see for example [this part](https://github.com/mason-org/mason-registry/blob/main/packages/zk/package.yaml#L24-L28) of the soon-to-be new package definition for `zk` (it (i) wouldn't prompt `darwin_x64` users to upgrade to the newer version, and (ii) allow them to install older versions just fine).

Out of curiosity, was the user-submitted binary vetted in any way?
