### ISSUE TITLE
[xo/eslint] cannot find package

### ISSUE THREAD

**Issue by alex-popov-tech** [williamboman/mason.nvim#759]
### I've searched open issues for similar requests

Yes

### I've manually reviewed logs to find potential errors

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

Hello!

I wanted to try out `xo` in new project, so i decided to use `mason` and `null-ls` for it.

I've downloaded it through `:Mason` ui, and put corresponding sources in `null-ls`.

Then I've ran `npx xo` in terminal to see some file with errors, and then went there in neovim.

It showed like `null-ls` tried to run `xo` on buffer, but i did not see any diagnostics.

After some debugging i've decided to try out vim's version of `xo` on correctness, and ran `:!xo`.

It showed me strange errors, which i do not know what to do with :(

Notes:
- i recently updated neovim and `mason`, before that was not updating them for few months
- maybe even global nodejs was updated while this time ( tho `eslint_d` and `prettierd` seem to be working fine )

```
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '/Users/oleksandrpopov/.local/share/nvim/mason/packages/xo/node_modules/xo/node_modules/eslint/' imported from /Users/oleksandrpopov/.local/share/nvim/mason/packages/xo/node_modules/xo/index.js
    at new NodeError (node:internal/errors:393:5)
    at legacyMainResolve (node:internal/modules/esm/resolve:235:9)
    at packageResolve (node:internal/modules/esm/resolve:847:14)
    at moduleResolve (node:internal/modules/esm/resolve:909:20)
    at defaultResolve (node:internal/modules/esm/resolve:1124:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.11.0
```

### Expected behavior

vim's executable `xo` should behave moreless same as commandline `npx xo`

### Steps to reproduce

1. install `xo` through `:Mason` ui
2. go to any project with `xo`
3. open js/ts file
4. run `:!xo`

### Affected packages

xo

### Neovim version (>= 0.7)

NVIM v0.9.0-dev-492+g224473546-dirty
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by oleksandrpopov@Oleksandrs-MacBook-Pro.local

### Operating system/version

Darwin Oleksandrs-MacBook-Pro.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64 x86_64

### Healthcheck

```Text
mason: require("mason.health").check()

mason.nvim report ~
- OK neovim version >= 0.7.0
- OK **Go**: `go version go1.19 darwin/amd64`
- OK **cargo**: `cargo 1.64.0 (387270bc7 2022-09-16)`
- OK **luarocks**: `/Users/oleksandrpopov/.asdf/installs/lua/5.3.5/luarocks/bin/luarocks 3.9.1`
- OK **Ruby**: `ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin21]`
- OK **RubyGem**: `3.1.2`
- WARNING **Composer**: not available
- OK **PHP**: `PHP 8.1.11 (cli) (built: Sep 29 2022 20:02:53) (NTS)`
- OK **npm**: `8.19.2`
- OK **node**: `v18.11.0`
- OK **python3**: `Python 3.9.0`
- OK **pip3**: `pip 20.2.3 from /Users/oleksandrpopov/.asdf/installs/python/3.9.0/lib/python3.9/site-packages/pip (python 3.9)`
- OK **javac**: `Ok`
- OK **java**: `openjdk version "1.8.0_282"`
- WARNING **julia**: not available
- OK **wget**: `GNU Wget 1.21.3 built on darwin21.3.0.`
- OK **curl**: `curl 7.84.0 (x86_64-apple-darwin22.0) libcurl/7.84.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.47.0`
- OK **gzip**: `Apple gzip 400`
- OK **tar**: `bsdtar 3.5.3 - libarchive 3.5.3 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
- WARNING **pwsh**: not available
- OK **bash**: `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin22)`
- OK **sh**: `Ok`
- OK **JAVA_HOME**: `openjdk version "1.8.0_282"`
- OK GitHub API rate limit. Used: 5. Remaining: 4995. Limit: 5000. Reset: Wed Dec 14 03:19:56 2022.
```

**Comment by williamboman** [comment]
Hey! So per their official documentation, it seems like `xo` really only should be installed inside the projects in which they're used. @thanhvule0310 first added `xo`, do you know more perhaps? In case it doesn't make sense to install `xo` outside of a project itself, maybe we should remove it from Mason.

**Comment by alex-popov-tech** [comment]
thank you guys!

**Comment by williamboman** [comment]
Deprecation notice finally added here https://github.com/mason-org/mason-registry/pull/2060, which is now displayed in the :Mason window since https://github.com/williamboman/mason.nvim/pull/1391
