### ISSUE TITLE
PWSH explecit error

### ISSUE THREAD

**Issue by ynhhoJ** [williamboman/mason.nvim#764]
### I've searched open issues for similar requests

Yes

### Is your feature request related to a problem? Please describe.

#706 

Is it possible to add a hint during an error related to `pwsh`?

![изображение](https://user-images.githubusercontent.com/22500212/207980456-bb51bc43-459c-4da0-ac90-358aab35365d.png)

Windows 11 has powershell (legacy version) installed by default, but `Mason` requires a newer version of `pwsh`. I could not immediately understand where exactly the error was, and after installing the powershell 7.3 version, everything worked

Code: https://github.com/williamboman/mason.nvim/pull/706/files#diff-1243700016801fd3c68dbc2d65f32bd9e12ae30b09e45031248e6e49065cf168R224-R233

### Describe the solution you'd like

1. Write to the user that he needs a new version of powershell

### Describe potential alternatives you've considered

2. Or add legacy powershell support

**Comment by asmodeus812** [comment]
Faced same issue, why is that such a hard requirement for this specific package, can we not use the older version. I also faced the same issue on shellcheck and lemminx.

**Comment by emPeeGee** [comment]
The same issue for me

**Comment by adriancostin6** [comment]
Facing the same issue here. Can't this just support the legacy version so us boomers don't have to install a brand new Powershell? It's an extra thing to keep in mind. This has to be documented either way, because as mentioned above, the default powershell version is still not `pwsh` for many systems.

**Comment by asmodeus812** [comment]
Not only that, but this kind of completely borks support for win10 and even win11 by default which imo is bad idea. What was wrong with maybe checking which shell is available and use that instead, the more fallback options the better.

**Comment by williamboman** [comment]
Hey! Ah that's interesting, I was under the impression that the old iteration of powershell had been phased out completely by now, seeing as the initial announcement was in 2017 IIRC. There's no particular reason to use `pwsh`, reverting back to `powershell.exe` should be perfectly fine

**Comment by williamboman** [comment]
I believe #769 fixes this by reverting the change. If it does not let's reopen.

**Comment by ynhhoJ** [comment]
@williamboman , it is possible to do like this:
1. If user doesn't have `pwsh` - use `powershell`
2. If user have `pwsh` - use `pwsh`

**Comment by williamboman** [comment]
> @williamboman , it is possible to do like this:
> 
> 1. If user doesn't have `pwsh` - use `powershell`
> 2. If user have `pwsh` - use `pwsh`

I've wanted to avoid doing this, but it seems like it's the only option. I was hoping Windows environment would be more predictable haha. Mason doesn't really call into Powershell that much, and all cmdlet invocations should be fully cross-compatible between Powershell versions (for now..).

**Comment by Cluster7ck** [comment]
Just for documentation purposes:
I created a script at `~/.pwsh.sh` with the following content as a workaround:

```bash
powershell "$@"
```

Wanted to comment, that I had the same issue, but found it was just fixed 😄 Thank you
