### ISSUE TITLE
NPM can't be found.

### ISSUE THREAD

**Issue by A-Lamia** [williamboman/mason.nvim#781]
### I've searched open issues for similar requests

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

LSP servers that use NPM fail to install, It seems Mason can't find NPM even though it is available and the path shown in the error is correct. 

Tree-sitter also has no issue finding and using NPM, and a couple weeks ago i installed node-debug2-addapter and prettierd that uses NPM with no issue or changes to my config or system from that time till now.

At first i was using scoop to install node thought it might be that so i tried the normal install and still the same issue.

### Expected behavior

Packages to install.

### Affected packages

Any that use NPM

### Mason output

```Text
Could not find executable "C:\\Program Files\\nodejs\\npm" in path.
spawn C:\Program Files\nodejs\npm failed with exit code - and signal -.
```

### Installation log

```Text
[ERROR 21/12/2022 3:24:50 PM] ...te\pack\packer\opt\mason.nvim/lua\mason-core\process.lua:152: Failed to spawn process. cmd="C:\\Program Files\\nodejs\\npm", err="ENOENT: no such file or directory"
[INFO  21/12/2022 3:24:54 PM] ...\packer\opt\mason.nvim/lua\mason-core\installer\init.lua:119: Executing installer for Package(name=css-lsp)
[ERROR 21/12/2022 3:24:54 PM] ...te\pack\packer\opt\mason.nvim/lua\mason-core\process.lua:152: Failed to spawn process. cmd="C:\\Program Files\\nodejs\\npm", err="ENOENT: no such file or directory"
[ERROR 21/12/2022 3:24:54 PM] ...\packer\opt\mason.nvim/lua\mason-core\installer\init.lua:155: Installation failed for Package(name=css-lsp) error=spawn: C:\Program Files\nodejs\npm failed with exit code - and signal -.
```

### Neovim version (>= 0.7)

NVIM v0.9.0-dev-530+gde90a8bfe
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system/version

Windows 10

### Healthcheck

```Text
mason.nvim report ~
- OK neovim version >= 0.7.0
- WARNING **Go**: not available
- OK **cargo**: `cargo 1.65.0 (4bc8f24d3 2022-10-20)`
- WARNING **luarocks**: not available
- WARNING **Ruby**: not available
- WARNING **RubyGem**: not available
- WARNING **Composer**: not available
- WARNING **PHP**: not available
- ERROR **npm**: not available
- OK **node**: `v19.3.0
`
- OK **python3**: `Python 3.11.1
`
- OK **pip3**: `pip 22.2.2 from C:\Users\Abdul\scoop\apps\python\current\Lib\site-packages\pip (python 3.11)

`
- WARNING **javac**: not available
- WARNING **java**: not available
- WARNING **julia**: not available
- OK **wget**: `GNU Wget 1.21.3 built on mingw32.
`
- OK **curl**: `curl 7.83.1 (Windows) libcurl/7.83.1 Schannel
`
- OK **gzip**: `gzip.exe" 1.3.12`
- OK **tar**: `bsdtar 3.5.2 - libarchive 3.5.2 zlib/1.2.5.f-ipp 
`
- OK **python**: `Python 3.11.1
`
- OK **pip**: `pip 22.2.2 from C:\Users\Abdul\scoop\apps\python\current\Lib\site-packages\pip (python 3.11)

`
- OK **7z**: `7-Zip 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15
`
- OK GitHub API rate limit. Used: 0. Remaining: 5000. Limit: 5000. Reset: 21/12/2022 4:04:43 PM.
```

**Comment by A-Lamia** [comment]
Also `vim.fn.executable()` returns true on the path it errors on for NPM.

**Comment by Blxckmage** [comment]
im dealing with this issue as well

**Comment by A-Lamia** [comment]
Seems this commit might be the issue https://github.com/williamboman/mason.nvim/commit/dd04b4105e84620685c37efb6ca935d282e11465

**Comment by williamboman** [comment]
`(╯°□°)╯︵ ┻━┻`

Where is your npm located when you execute it in your terminal `> (Get-Command npm).Path`? It looks a bit suspicious, I'd expect it to have a `.cmd` suffix.

**Comment by Blxckmage** [comment]
> `(╯°□°)╯︵ ┻━┻`
> 
> Where is your npm located when you execute it in your terminal `> (Get-Command npm).Path`? It looks a bit suspicious in the logs you provided, I'd expect it to have a `.cmd` suffix. I wonder why.

mine is C:\Program Files\nodejs\npm.cmd

**Comment by A-Lamia** [comment]
mine is currently `C:\Users\Lamia\scoop\apps\nodejs\current\bin\npm.ps1`
but i also tested it with `C:\Program Files\nodejs\npm.ps1` both a no go.

**Comment by williamboman** [comment]
@A-Lamia What's your `PATHEXT` variable inside Neovim? `:echo $PATHEXT` should display it.

**Comment by A-Lamia** [comment]
@williamboman `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL`

**Comment by A-Lamia** [comment]
but there is also .CMD in the path so that is confusing. it should still chose the correct one ?

**Comment by aver-roes** [comment]
I'm facing the same issue, C:\Program Files\nodejs\npm.cmd is already added to the path

**Comment by williamboman** [comment]
I've reverted #783 for now, so latest plugin version should work again. Will have to look into what's up on Windows
