### ISSUE TITLE
Keep getting `mason.nvim/lua/mason-registry/init.lua:67: bad argument #1 to '?' (string expected, got nil)` error in `mason.log`

### ISSUE THREAD

**Issue by xfzv** [williamboman/mason.nvim#789]
### I've searched open issues for similar requests

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

I keep getting the following error in `mason.log`:

```log
[ERROR Thu 22 Dec 2022 11:29:05 AM CET] ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:67: bad argument #1 to '?' (string expected, got nil)
```

It gets printed silently in the log every time I run Neovim. It's also printed in the shell if I run a Neovim command such as `nvim --headless "+Lazy! sync" +qa`.

I tried to delete the following directories, to no avail:

- `~/.local/share/nvim/lazy/mason.nvim`
- `~/.local/share/nvim/mason`

### Expected behavior

No such error is printed in the log.

### Steps to reproduce

1. Run Neovim or a Neovim command from the shell like `nvim --headless "+Lazy! sync" +qa`
2. Check log with `:MasonLog`, the mentioned error is printed every time

### Neovim version (>= 0.7)

NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system/version

Linux gentoo 6.1.1-gentoo-custom

### Healthcheck output

```shell
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - OK: **Go**: `go version go1.19.4 linux/amd64`
  - OK: **cargo**: `cargo 1.66.0 (d65d197ad 2022-11-15)`
  - WARNING: **luarocks**: not available
  - OK: **Ruby**: `ruby 2.7.7p221 (2022-11-24 revision 168ec2b1e5) [x86_64-linux]`
  - OK: **RubyGem**: `3.3.8`
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.19.2`
  - OK: **node**: `v18.12.1`
  - OK: **python3**: `Python 3.10.9`
  - WARNING: **pip3**: not available
  - WARNING: **javac**: not available
  - WARNING: **java**: not available
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: **curl**: `curl 7.87.0 (x86_64-pc-linux-gnu) libcurl/7.87.0 OpenSSL/1.1.1s zlib/1.2.13 c-ares/1.18.1 nghttp2/1.51.0`
  - OK: **gzip**: `gzip 1.12`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - WARNING: **pwsh**: not available
  - OK: **bash**: `GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: Thu 22 Dec 2022 12:25:43 PM CET.
```

**Comment by williamboman** [comment]
Cool! Yeah please report to mason-null-ls.nvim instead.
