### ISSUE TITLE
Help does not show with `g?` command

### ISSUE THREAD

**Issue by rcclemente** [williamboman/mason.nvim#831]
### I've searched open issues for similar requests

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

Help does not show when typing `g?` when the window is open

![Screen Shot 2022-12-31 at 6 07 23 PM](https://user-images.githubusercontent.com/22880578/210132809-611aa6d9-08f3-4413-9ba0-1986298c510c.jpg)

### Expected behavior

to show the help

### Steps to reproduce

1. `:Mason`
2. type `g?` when the window opens

### Neovim version (>= 0.7)

NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

### Operating system/version

Darwin MacBook-Pro-14.local 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000 arm64

### Healthcheck output

```shell
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - WARNING: **Go**: not available
  - OK: **cargo**: `cargo 1.65.0 (4bc8f24d3 2022-10-20)`
  - WARNING: **luarocks**: not available
  - OK: **Ruby**: `ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [-darwin21]`
  - OK: **RubyGem**: `3.1.2`
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `9.2.0`
  - OK: **node**: `v19.3.0`
  - OK: **python3**: `Python 3.10.8`
  - OK: **pip3**: `pip 22.2.2 from /opt/homebrew/lib/python3.10/site-packages/pip (python 3.10)`
  - WARNING: **javac**: not available
  - OK: **java**: `java version "1.8.0_341"`
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.3 built on darwin21.3.0.`
  - OK: **curl**: `curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.5 zlib/1.2.11 nghttp2/1.45.1`
  - OK: **gzip**: `Apple gzip 353.100.22`
  - OK: **tar**: `bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
  - OK: **bash**: `GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 6. Remaining: 4994. Limit: 5000. Reset: Sat Dec 31 18:48:27 2022.
```

**Comment by williamboman** [comment]
Hello! Which terminal emulator are you using (I'd recommend trying/using Wezterm or Kitty). This might also be happening if you're using a keyboard layout that inputs something different when `g?` is pressed.
