### ISSUE TITLE
Conflict packages and version select

### ISSUE THREAD

**Issue by Decodetalkers** [williamboman/mason.nvim#832]
### I've searched open issues for similar requests

Yes

### Is your feature request related to a problem? Please describe.

I think we should provide different version of package for user to download, like csharp-language-server, because it on dotnet platform, and it can only work on target dotnet version, like be compiled with dotnet 6.0, it can only work in dotnet 6.0 project, and with dotnet 7.0, then it can only work on dotnet 7.0 platform, so I think provide confict packages, for user to download different package is needed. 

package from dotnet can be downloaded by use --version option, without `version` option , it will download the latest package. so when user try to download this package , maybe user can choose history package to develop their program

```
dotnet tool install --global csharp-ls --version 0.6.0
```

### Describe the solution you'd like

Conflict package , one is installed and other is uninstalled,

**Comment by williamboman** [comment]
Hello! Requesting a specific version is already supported, like `:MasonInstall csharp-language-server@0.6.0` or `require("mason-registry").get_package("csharp-language-server"):install { version = "0.6.0" }`. Is this what you meant?

**Comment by Decodetalkers** [comment]
> Hello! Requesting a specific version is already supported, like `:MasonInstall csharp-language-server@0.6.0` or `require("mason-registry").get_package("csharp-language-server"):install { version = "0.6.0" }`. Is this what you meant?

I think we can add a list of available key to make user can use special version.. Like I want to add 0.5 and 0.6 , 0.6 is the latest.. 0.6 can work on dotnet 7.0, and 0.5 can work on dotnet 6...

Yes, in my image, if clicked the package of csharp_ls, it can show a list to choose available package. If not point to use which one, mason will not use the version option , and download the lastest version. And since dotnet can not check if the package is out of date, then the special version pin by user will not be updated with other packages.. I think it maybe good

**Comment by tjapa** [comment]
Is it possible to install two different versions of typescript-language-server and use them according to the version of Node.JS that is selected in NVM?

**Comment by stevenctl** [comment]
My attempt to install csharp_ls via the UI fails due to lack of version.. sort of related

<details>

<summary>error message</summary>
```
 Failed
    ◍ csharp-language-server
      /var/folders/lf/dw2_vqxj3239g8c0xxyg8pl40000gn/T/aea1f8fc-8627-4f25-bef5-487299b28860/restore.csproj : error NU1202: Package csharp-ls 0.6.0 is not compatible with net6.0 (.NETCoreApp,Version=v6.0) / any. Package csharp-ls 0.6.0 supports: net7.0 (.NETCoreApp,Version=v7.0) / any
      Tool 'csharp-ls' failed to update due to the following:
      The tool package could not be restored.
      Tool 'csharp-ls' failed to install. This failure may have been caused by:
      
      * You are attempting to install a preview release and did not use the --version option to specify the version.
      * A package by this name was found, but it was not a .NET tool.
      * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
      * You mistyped the name of the tool.
      
      For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
      spawn: dotnet failed with exit code 1 and signal 0. 
      
```

</details>

**Comment by Decodetalkers** [comment]
> My attempt to install csharp_ls via the UI fails due to lack of version.. sort of related
> 
> <details>
> 
> <summary>error message</summary>
> ```
>  Failed
>     ◍ csharp-language-server
>       /var/folders/lf/dw2_vqxj3239g8c0xxyg8pl40000gn/T/aea1f8fc-8627-4f25-bef5-487299b28860/restore.csproj : error NU1202: Package csharp-ls 0.6.0 is not compatible with net6.0 (.NETCoreApp,Version=v6.0) / any. Package csharp-ls 0.6.0 supports: net7.0 (.NETCoreApp,Version=v7.0) / any
>       Tool 'csharp-ls' failed to update due to the following:
>       The tool package could not be restored.
>       Tool 'csharp-ls' failed to install. This failure may have been caused by:
>       
>       * You are attempting to install a preview release and did not use the --version option to specify the version.
>       * A package by this name was found, but it was not a .NET tool.
>       * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
>       * You mistyped the name of the tool.
>       
>       For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
>       spawn: dotnet failed with exit code 1 and signal 0. 
>       
> ```
> 
> </details>

Yes, 6.0 is for dotnet 7.0,you should install pervious version
