### ISSUE TITLE
Lombok ins't working

### ISSUE THREAD

**Issue by daltondiaz** [williamboman/mason.nvim#844]
### I've searched open issues for similar requests

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [x] Yes

### Problem description

Lombok ins't working at any of my java projects. I'm using the default configuration

```local config = {
    cmd = {'/home/dalton/.local/share/nvim/mason/bin/jdtls'},
    root_dir = vim.fs.dirname(vim.fs.find({'.gradlew', '.git', 'mvnw'}, { upward = true })[1]),
}
require('jdtls').start_or_attach(config)
```

The classes that I use `@Data` the methods getter and setter show the error `The method setXyz is undefined` 

All my configurations of nvim are in my github: https://github.com/daltondiaz/init.lua/tree/fix/lombok

I create a new branch fix/lombok with default configuration.

Some picture when I open the class 

![image-title](https://raw.githubusercontent.com/daltondiaz/init.lua/fix/lombok/pictures/2023-01-03_17-13.png)

When finish 

![image-title](https://raw.githubusercontent.com/daltondiaz/init.lua/fix/lombok/pictures/2023-01-03_17-15.png)

### Expected behavior

Lombok work!

### Steps to reproduce

1. nvim .
2. Open Any Class with lombok annotation

### Neovim version (>= 0.7)

NVIM v0.9.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-UEh7si/neovim-0.9.0~ubuntu1+git202212280018-d215dae0e-333b5866f=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -
Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_G
ENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-UEh7si/neovim-0.9.0~ubuntu1+git202212280018-d215dae0e-333b5866f/build/cmake.config -I/build/neovim-UEh7si/neovim-0.9.0~ubuntu1+git202212280018-d215dae0e-333b5866f/src -I/
build/neovim-UEh7si/neovim-0.9.0~ubuntu1+git202212280018-d215dae0e-333b5866f/.deps/usr/include -I/usr/include -I/build/neovim-UEh7si/neovim-0.9.0~ubuntu1+git202212280018-d215dae0e-333b5866f/build/src/nvim/auto -I/build/neovim-UEh7si/neovim-0.9.0~ubuntu1+git202212280018-d215dae0e-333b5866f/bui
ld/include
Compiled by buildd@lcy02-amd64-063

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Operating system/version

Linux dalton 5.16.0-051600rc8-generic #202201022330 SMP PREEMPT Sun Jan 2 23:35:01 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux 

### Healthcheck output

```shell
==============================================================================
mason: require("mason.health").check()

mason.nvim report ~
- OK neovim version >= 0.7.0
- OK **Go**: `go version go1.19.2 linux/amd64`
- OK **cargo**: `cargo 1.65.0 (4bc8f24d3 2022-10-20)`
- WARNING **luarocks**: not available
- WARNING **Ruby**: not available
- WARNING **RubyGem**: not available
- OK **Composer**: `Composer version 2.4.3 2022-10-14 16:56:41`
- OK **PHP**: `PHP 7.4.33 (cli) (built: Nov  8 2022 11:33:53) ( NTS )`
- OK **npm**: `8.19.3`
- OK **node**: `v14.21.1`
- OK **python3**: `Python 3.10.6`
- OK **pip3**: `pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)`
- OK **javac**: `javac 17.0.5`
- OK **java**: `openjdk version "17.0.5" 2022-10-18`
- WARNING **julia**: not available
- OK **wget**: `GNU Wget 1.21.2 built on linux-gnu.`
- OK **curl**: `curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.13`
- OK **gzip**: `gzip 1.10`
- OK **tar**: `tar (GNU tar) 1.34`
- OK **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
- OK **sh**: `Ok`
- OK GitHub API rate limit. Used: 5. Remaining: 55. Limit: 60. Reset: ter 03 jan 2023 17:59:12.
```

**Comment by williamboman** [comment]
Hey! Mason will install the `lombok.jar` inside `require("mason-registry").get_package("jdtls"):get_install_path()`, and you need to tell `jdtls` to use it as a Java agent, for example something like so:

```lua
local config = {
    cmd = {
        "jdtls",
        "--jvm-arg=" .. string.format(
            "-javaagent:%s",
            require("mason-registry").get_package("jdtls"):get_install_path() .. "/lombok.jar"
        ),
    },
    root_dir = vim.fs.dirname(vim.fs.find({'.gradlew', '.git', 'mvnw'}, { upward = true })[1]),
}
require('jdtls').start_or_attach(config)
```

**Comment by daltondiaz** [comment]
I try, but the error continue. There's more steps to discover what is happening?

**Comment by bagel897** [comment]
https://github.com/snjeza/vscode-test/raw/master/lombok-1.18.26.jar
Use this jar instead. Can Mason include this patched version?

**Comment by daltondiaz** [comment]
@bagel897 @williamboman I resolved the problem but its not the better way, what I do is configure everything instead of lombok in manson-registry.

Here the solution: https://github.com/daltondiaz/init.lua/blob/main/ftplugin/java.lua
