### ISSUE TITLE
Editorconfig-checker should use "ec" binary

### ISSUE THREAD

**Issue by jemag** [williamboman/mason.nvim#870]
### I've searched open issues for similar requests

Yes

### I've manually reviewed logs to find potential errors

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

editorconfig-checker should be installed as `ec` binary and not `editorconfig-checker`

### Expected behavior

Installs as `ec` binary

### Steps to reproduce

1. Install editorconfig-checker
2. Notice `ec` is not available but `editorconfig-checker` is

### Affected packages

editorconfig-checker

### Neovim version (>= 0.7)

NVIM v0.9.0-dev-580+g4703e561d
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvl
a -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim/build/cmake.config -I/tmp/neovim/src -I/tmp/neovim/.deps/usr/include -I/usr/include -I/tmp/neovim/build/src/nvi
m/auto -I/tmp/neovim/build/include

### Operating system/version

Linux archhome 6.1.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 21 Dec 2022 22:27:55 +0000 x86_64 GNU/Linux 

### Healthcheck

```Text
==============================================================================
mason: require("mason.health").check()

mason.nvim report ~
- OK neovim version >= 0.7.0
- OK **Go**: `go version go1.19.4 linux/amd64`
- OK **cargo**: `cargo 1.66.0`
- OK **luarocks**: `/usr/bin/luarocks 3.9.1`
- OK **Ruby**: `ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux]`
- OK **RubyGem**: `3.3.25`
- WARNING **Composer**: not available
- WARNING **PHP**: not available
- OK **npm**: `8.19.2`
- OK **node**: `v16.19.0`
- OK **python3**: `Python 3.10.9`
- OK **pip3**: `pip 22.3.1 from /usr/lib/python3.10/site-packages/pip (python 3.10)`
- OK **javac**: `javac 17.0.5`
- OK **java**: `openjdk version "17.0.5" 2022-10-18`
- WARNING **julia**: not available
- OK **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
- OK **curl**: `curl 7.87.0 (x86_64-pc-linux-gnu) libcurl/7.87.0 OpenSSL/3.0.7 zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.4 libpsl/0.21.1 (+libidn2/2.3.4) libssh2/1.10.0 nghttp2/1.51.0`
- OK **gzip**: `gzip 1.12`
- OK **tar**: `tar (GNU tar) 1.34`
- WARNING **pwsh**: not available
- OK **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
- OK **sh**: `Ok`
- OK **JAVA_HOME**: `openjdk version "17.0.5" 2022-10-18`
- OK GitHub API rate limit. Used: 1. Remaining: 4999. Limit: 5000. Reset: Sun 08 Jan 2023 09:55:07 PM EST.
```

**Comment by williamboman** [comment]
Hey! See https://github.com/editorconfig-checker/editorconfig-checker/issues/232. Will wait for recommendation there.

**Comment by jemag** [comment]
Interesting, didn't realize there even was confusion about the name.
From the documentation they do mention `ec` multiple times:

---

1:
![image](https://user-images.githubusercontent.com/7985687/211329250-3d031a82-12cb-4d7a-a61e-d95e79b05b68.png)

---

2:
![image](https://user-images.githubusercontent.com/7985687/211329337-babeab34-0ba5-44ca-9964-7834ea6f9c49.png)

---

3:
![image](https://user-images.githubusercontent.com/7985687/211329388-aa8d5b4d-1ebd-4af9-8de1-5b84e7f20904.png)

---


Also arch's `pacman` install will use `ec` as well.
The container image also uses `ec`.

**Comment by williamboman** [comment]
Yeah I think `ec` might actually be more established. Homebrew and the npm wrapper provides the `editorconfig-checker` executable. Personally I find it more suitable than a two-letter one, but that's irrelevant. Let's see what the maintainers say!

**Comment by jay-babu** [comment]
This can be closed. Full name is official
