### ISSUE TITLE
clangd for Linux_arm64 is not available

### ISSUE THREAD

**Issue by SJonesy** [williamboman/mason.nvim#893]
### I've searched open issues for similar requests

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

I'm using Manjaro ARM Linux aarch64. When I run `:MasonInstall clangd` I get `Most likely the current operating system or architecture is not supported (Linux_arm64).` However, `clangd` is installed on my system and runs without any problems.

### Expected behavior

I would expect to be able to install clangd with `:MasonInstall`.

### Affected packages

clangd

### Mason output

```Text
Most likely the current operating system or architecture is not supported (Linux_arm64).
```

### Installation log

```Text
Installation failed for Package(name=clangd) error="Could not find which release file to download.\nMost likely the current operating system or architecture is not supported (Linux_arm64)."
```

### Neovim version (>= 0.7)

0.8.2

### Operating system/version

Linux pbp 6.1.2-1-MANJARO-ARM #1 SMP PREEMPT Sat Dec 31 14:30:55 UTC 2022 aarch64 GNU/Linux

### Healthcheck

```Text
Ok: Neovim/python3/pip3/wget/curl/gzip/tar/bash/sh/github api rate limit,
Warning: Go/cargo/luarocks/ruby/rubygem/composer/php/javac/java/julia/pwsh not available
Error: npm/node not available
```

**Comment by williamboman** [comment]
Hey! See https://github.com/williamboman/mason.nvim/issues/647#issuecomment-1421374526
