### ISSUE TITLE
`markdonwlint` is not configurable and hence, not working

### ISSUE THREAD

**Issue by fernandocanizo** [williamboman/mason.nvim#917]
### I've searched open issues for similar requests

Yes

### I've manually reviewed logs to find potential errors

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

1) Mason lists and allows to install [`markdownlint`](https://github.com/igorshubovych/markdownlint-cli), however that package isn't auto-configurable via [`mason-lspconfig`](https://github.com/williamboman/mason-lspconfig.nvim) nor is part of [`lspconfig`](https://github.com/neovim/nvim-lspconfig), so cannot be manually setup vía `require('lspconfig')['markdownlint'].setup()`. either.

2) Mason aims to facilitate installation and configuration (vía mason-lspconfig) of packages. It should not provide the means to install a package if later it cannot be used. It produces a false sense, like the "thing is working", but it's not.

### Expected behavior

To have a Markdown linter working by either have it auto-configured and available, or to provide means to make it work.

### Steps to reproduce

1. install Mason
2. using Mason install `markdownlint`
3. open a Markdown file: `nvim whatever.md` and issue an `:LspInfo` command, you'll see "0 client(s) attached to this buffer" message.

### Affected packages

markdownlint

### Neovim version (>= 0.7)

NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Operating system/version

Linux bytor 5.18.17-1-MANJARO #1 SMP PREEMPT_DYNAMIC Thu Aug 11 18:43:37 UTC 2022 x86_64 GNU/Linux

### Healthcheck

```Text
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - OK: **Go**: `go version go1.19.4 linux/amd64`
  - OK: **cargo**: `cargo 1.66.0`
  - OK: **luarocks**: `/usr/bin/luarocks 3.9.1`
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - OK: **PHP**: `PHP 8.1.13 (cli) (built: Dec 12 2022 23:45:33) (NTS)`
  - OK: **npm**: `9.2.0`
  - OK: **node**: `v18.6.0`
  - OK: **python3**: `Python 3.10.8`
  - OK: **pip3**: `pip 22.3.1 from /usr/lib/python3.10/site-packages/pip (python 3.10)`
  - OK: **javac**: `Ok`
  - OK: **java**: `openjdk version "1.8.0_352"`
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: **curl**: `curl 7.87.0 (x86_64-pc-linux-gnu) libcurl/7.87.0 OpenSSL/3.0.7 zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.4 libpsl/0.21.1 (+libidn2/2.3.4) libssh2/1.10.0 nghttp2/1.51.0`
  - OK: **gzip**: `gzip 1.12`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - WARNING: **pwsh**: not available
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 6. Remaining: 54. Limit: 60. Reset: lun 16 ene 2023 17:08:18.
```

### Screenshots or recordings

Not needed

**Comment by williamboman** [comment]
Hey! To my knowledge, markdownlint does not provide a language server. It provides diagnostics (which can be integrated into Neovim through for example:
- https://github.com/jose-elias-alvarez/null-ls.nvim
- https://github.com/mfussenegger/nvim-lint

(you can also see this in the categories of the package, it doesn't include LSP)
![image](https://user-images.githubusercontent.com/6705160/212758500-545f89bc-b93c-4d2f-96f7-e278136b5308.png)

**Comment by fernandocanizo** [comment]
Oh, my bad then. Sorry for the noise.
