### ISSUE TITLE
Suggestions for coexistence of linux_arm64 and linux_arm64-gnu

### ISSUE THREAD

**Issue by garchomp-game** [williamboman/mason.nvim#933]
### I've searched open issues for similar requests

Yes

### Is your feature request related to a problem? Please describe.

Excuse me.

I am currently using it on android termux.

Some mason-registries, including lua-language-server, have changed from linux_arm64 to linux_arm64-gnu.

However, termux doesn't support linux_arm64-gnu, so it doesn't work well (I'm currently using the static-registry branch as a temporary workaround).

### Describe the solution you'd like

Apart from linux_arm64-gnu, I would appreciate it if you could also leave linux_arm64. Thank you for your consideration.

**Comment by williamboman** [comment]
Hello! So the arm64 binary for lua-language-server depends on a GNU system due to being linked glibc via `ld(1)`. This is why it targets `linux_arm64_gnu`, and not any arm64 Linux system. Are you saying you're successfully executing the provided arm64 binary on an Android system?

**Comment by fiplox** [comment]
On apt repositories of termux there is lua-language-server which uses arm64 build, not the gnu one, and it works like a charm :)
