### ISSUE TITLE
Use ssh to run 'git clone repo'

### ISSUE THREAD

**Issue by kdurant** [williamboman/mason.nvim#97]
### Is your feature request related to a problem? Please describe.

Sometime, I can't use http to clone a repo because of network, but ssh can do it. 

### Describe the solution you'd like

I want a option to select `clone by https` or `clone by ssh`
If select `https`, downloading file by
`https://github.com/williamboman/mason.nvim.git`

select `ssh`, downloading file by
`git@github.com:williamboman/mason.nvim.git`

**Comment by kdurant** [comment]
@williamboman 
I will confront some mistakes  when I use `git clone https://github.com/williamboman/mason.nvim.git`, like below:
`curl 16 Error in the HTTP2 framing layer`
I don't know why.

**Comment by williamboman** [comment]
Hm if the problem is with downloading the plugin itself, I'm not sure what could be done as that's something you have to do yourself (or alternatively use a plugin manager like Packer). Try running `git clone git@github.com:williamboman/mason.nvim`?

**Comment by mtawaken** [comment]
@williamboman 
maybe the requirement is similiar to this packer issue: [https://github.com/wbthomason/packer.nvim/issues/326](url)
In some env, ssh is just the only way to download pkg, and packer offers an option.
@kdurant you can check that issue out, alternatively changing global git settings can solve this.
