### ISSUE TITLE
lua-language-server uses incorrect path when downloading package

### ISSUE THREAD

**Issue by WhoIsSethDaniel** [williamboman/mason.nvim#979]
### I've searched open issues for similar requests

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

The most recent changes for `lua-language-server` creates an invalid path that `mason` attempts to download. 

The path `mason` tries to download is:
https://github.com/LuaLS/lua-language-server/releases/download/v3.6.10/lua-language-server-v3.6.10-linux-x64.tar.gz

The actual path for the package is:
https://github.com/LuaLS/lua-language-server/releases/download/3.6.10/lua-language-server-3.6.10-linux-x64.tar.gz

The difference is that the version number should not be preceded by a 'v'.

### Expected behavior

`mason` downloads and installs `lua-language-server`.

### Affected packages

lua-language-server

### Installation log

```Text
[INFO  Thu 09 Feb 2023 08:16:14 PM CST] ...plugins/opt/mason.nvim/lua/mason-core/installer/init.lua:120: Executing installer for Package(name=lua-language-server)
[ERROR Thu 09 Feb 2023 08:16:15 PM CST] ...plugins/opt/mason.nvim/lua/mason-core/installer/init.lua:159: Installation failed for Package(name=lua-language-server) error='...gins/opt/mason.nvim/lua/mason-core/managers/std/init.lua:52: Failed to download file "https://github.com/LuaLS/lua-language-server/releases/download/v3.6.10/lua-language-server-3.6.10-linux-x64.tar.gz".\nspawn: wget failed with exit code 8 and signal 0. '
```

### Neovim version (>= 0.7)

NVIM v0.9.0-dev-903+gecc40660d
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-10 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fno-common -fdiagnostics-color=always -fstack-protector-strong -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DMIN_LOG_LEVEL=3 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/runner/work/neovim/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/runner/work/neovim/neovim/.deps/usr/include -I/home/runner/work/neovim/neovim/.deps/usr/include -I/home/runner/work/neovim/neovim/.deps/usr/include -I/home/runner/work/neovim/neovim/.deps/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include -I/home/runner/work/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/home/runner/work/neovim/neovim/.deps/usr/include -I/home/runner/work/neovim/neovim/.deps/usr/include
Compiled by runner@fv-az243-267

Features: +acl +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info

### Operating system/version

Linux rachel 5.19.16-76051916-generic #202210150742~1666053244~22.04~cf07008~dev-Ubuntu SMP PREEMPT_DY x86_64 x86_64 x86_64 GNU/Linux

### Healthcheck

```Text
mason: require("mason.health").check()

mason.nvim report ~
- OK neovim version >= 0.7.0
- OK **Go**: `go version go1.19.2 linux/amd64`
- OK **cargo**: `cargo 1.61.0`
- OK **luarocks**: `/usr/bin/luarocks 3.8.0`
- OK **Ruby**: `ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux-gnu]`
- OK **RubyGem**: `3.3.15`
- WARNING **Composer**: not available
- WARNING **PHP**: not available
- OK **npm**: `9.4.0`
- OK **node**: `v19.6.0`
- OK **python3**: `Python 3.10.7`
- OK **pip3**: `pip 22.2 from /usr/lib/python3/dist-packages/pip (python 3.10)`
- WARNING **javac**: not available
- WARNING **java**: not available
- WARNING **julia**: not available
- OK **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
- OK **curl**: `curl 7.85.0 (x86_64-pc-linux-gnu) libcurl/7.85.0 OpenSSL/3.0.5 zlib/1.2.11 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.3 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.49.0 librtmp/2.3`
- OK **gzip**: `gzip 1.12`
- OK **tar**: `tar (GNU tar) 1.34`
- WARNING **pwsh**: not available
- OK **bash**: `GNU bash, version 5.2.2(1)-release (x86_64-pc-linux-gnu)`
- OK **sh**: `Ok`
- OK GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: Thu 09 Feb 2023 09:26:35 PM CST.
```

**Comment by williamboman** [comment]
Hey! Hm most likely this is happening because an invalid version is being requested (`v3.6.10` instead of `3.6.10`). I guess you retrieve the new version to install from `Package:check_new_version()`? This is currently a bit problematic if the underlying source changes, like what happened to `lua-language-server` recently. The reason why is because `Package:check_new_version()` uses whatever source was used during installation to track new versions, and may become disconnected with the true source (this will be fixed with https://github.com/mason-org/mason-registry).

**Comment by WhoIsSethDaniel** [comment]
Wiping the old installation from the `mason` dir and reinstalling resolved my particular issue.

**Comment by williamboman** [comment]
Cool! Installing without providing a version specifier should've worked as well (if that indeed was the issue)!
