### ISSUE TITLE
Opt-in for "formatting on save" feature via menu

### ISSUE THREAD

**Issue by osamuaoki** [williamboman/mason.nvim#983]
### I've searched open issues for similar requests

Yes

### Is your feature request related to a problem? Please describe.

Upon installing lua-language-server via mason.nvim, lua files after modification started to be reformatted upon file save.  

This was a bit of surprise.   

This kind of feature should be activated as **opt-in**.

### Describe the solution you'd like

If adding activation/deactivation of "format on save" feature selection can be added to the menu selection of mason.nvim, it is nice.

Can this be something which mason.nvim can address?  Or it is something which needs to be addressed in different layer?  If so, please point it to us.

### Describe potential alternatives you've considered

Of course, we can configure lua-language-server not to format (**opt-out**) and just used only as a diagnostic tool as discussed:

  * https://github.com/AstroNvim/AstroNvim/issues/1572

**Comment by mehalter** [comment]
I think this is a mistake as Mason has no relationship with configuring or setting up language servers, null-ls, formatters etc.
