### ISSUE TITLE
failed to install lua-language-server

### ISSUE THREAD

**Issue by foxyseta** [williamboman/mason.nvim#995]
### I've searched open issues for similar requests

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

1. When I use `:MasonInstall lua-language-server`, I get: `Could not find which release file to download. Most likely the current operating system or architecture is not supported. (Linux_x64).`. Possibly related to #428? Something different altogether?
2. Pretty sure there is a valid release for this.

### Expected behavior

I'd expect the package to be successfully installed.

### Affected packages

lua-language-server

### Mason output

```Text
Could not find which release file to download.
Most likely the current operating system or architecture is not supported. (Linux_x64).
```
```


### Installation log

```Text
[INFO  Wed Feb 15 12:36:15 2023] ...ck/paks/opt/mason.nvim/lua/mason-core/installer/init.lua:120: Executing installer for Package(name=lua-language-server)
[DEBUG Wed Feb 15 12:36:15 2023] ...nvim/site/pack/paks/opt/mason.nvim/lua/mason-core/fs.lua:71: fs: mkdirp /home/foxy/.local/share/nvim/mason/.packages/lua-language-server
[DEBUG Wed Feb 15 12:36:15 2023] ...m/site/pack/paks/opt/mason.nvim/lua/mason-core/fetch.lua:34: Fetching URL "https://api.mason-registry.dev/api/github/LuaLS/lua-language-server/releases/latest"
[DEBUG Wed Feb 15 12:36:15 2023] ...site/pack/paks/opt/mason.nvim/lua/mason-core/process.lua:116: Spawning cmd="curl", spawn_opts={
  args = { "-H", "Accept: application/vnd.mason-registry.v1+json; q=1.0, application/json; q=0.8", "-H", "User-Agent: mason.nvim (+https://github.com/williamboman/mason.nvim)", "-fsSL", "-X", "GET", "https://api.mason-registry.dev/api/github/LuaLS/lua-language-server/releases/latest" }
}
[DEBUG Wed Feb 15 12:36:15 2023] ...site/pack/paks/opt/mason.nvim/lua/mason-core/process.lua:162: Spawned with pid 9010
[DEBUG Wed Feb 15 12:36:15 2023] ...site/pack/paks/opt/mason.nvim/lua/mason-core/process.lua:148: Job pid=9010 exited with exit_code=0, signal=0
[ERROR Wed Feb 15 12:36:15 2023] ...ck/paks/opt/mason.nvim/lua/mason-core/installer/init.lua:159: Installation failed for Package(name=lua-language-server) error="Could not find which release file to download.\nMost likely the current operating system or architecture is not supported (Linux_x64)."
[DEBUG Wed Feb 15 12:36:15 2023] ...nvim/site/pack/paks/opt/mason.nvim/lua/mason-core/fs.lua:47: fs: rmrf /home/foxy/.local/share/nvim/mason/.packages/lua-language-server
[DEBUG Wed Feb 15 12:36:15 2023] .../paks/opt/mason.nvim/lua/mason-core/installer/linker.lua:21: Unlinking Package(name=lua-language-server)
```
```


### Neovim version (>= 0.7)

NVIM v0.8.3
Build type: MinSizeRel
LuaJIT 2.1.0-beta3
Compiled by buildozer@build-edge-x86_64

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Operating system/version

Linux foxy-thinkpad 6.1.11-0-lts #1-Alpine SMP PREEMPT_DYNAMIC Thu, 09 Feb 2023 15:21:13 +0000 x86_64 Linux

### Healthcheck

```Text
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - OK: **Go**: `go version go1.20 linux/amd64`
  - WARNING: **cargo**: not available
  - WARNING: **luarocks**: not available
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `9.4.2`
  - OK: **node**: `v18.14.0`
  - OK: **python3**: `Python 3.11.2`
  - WARNING: **pip3**: not available
  - WARNING: **javac**: not available
  - WARNING: **java**: not available
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-musl.`
  - OK: **curl**: `curl 7.87.0 (x86_64-alpine-linux-musl) libcurl/7.87.0 OpenSSL/3.0.8 zlib/1.2.13 brotli/1.0.9 nghttp2/1.51.0`
  - OK: **gzip**: `gzip 1.12`
  - OK: **tar**: `tar (busybox) 1.36.0`
  - WARNING: **pwsh**: not available
  - OK: **bash**: `GNU bash, version 5.2.15(1)-release (x86_64-alpine-linux-musl)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: Wed Feb 15 13:41:41 2023.
```

**Comment by foxyseta** [comment]
Makes total sense. As I have a plain Alpine Linux setup, I only have muslc installed at the moment. glibc isn't packaged on Alpine, so I should really build it from source. Will see if I'm up for the task.

By the way, the gcompat compatibility layer (which is currently not installed on my system, but is available for several muslc-based distros) may not set the GNU_LIBC_VERSION, but it does make gnu_get_libc_version return a plausible value. Maybe that could be used as a fallback if no configuration option is set for mason and GNU_LIBC_VERSION is not set?

**Comment by williamboman** [comment]
Hm I think I closed the wrong issue before. So the reason it's not installing is because the binaries installed are built for GNU systems (i.e. ld & glibc). Alpine Linux is, by default, not compatible. I believe there's a package called `gcompat` which makes the system GNU-compatible (ish?). You can "force" installation by providing which target to install:

```vim
:MasonInstall --target=linux_x64_gnu lua-language-server
```

**Comment by williamboman** [comment]
> After 210865d, same thing happens to me (still using Alpine Linux).

Hm so this was working fine before? Nothing should've changed.

**Comment by foxyseta** [comment]
> Hm so this was working fine before? Nothing should've changed.

It wasn't before either. Sorry for not explaining myself clearly.
Before said commit, the ecountered behavior was describe in OP.
After the commit, the encountered behavior is explained by @ericwq and in my last message as well.

> I believe there's a package called gcompat which makes the system GNU-compatible (ish?).

Yes, when it comes to glibc applications, `gcompat` is the "go-to compatibility layer for Alpine users". As described [here](https://github.com/williamboman/mason.nvim/issues/995#issuecomment-1462106659), it does not set `GNU_LIBC_VERSION`, so it was of no use to me.

> You can "force" installation by providing which target to install [...].

Thanks! That was it. Any chance we could enhance `platform.lua` so that the platform gets automatically recognized like @ericwq suggested?

**Comment by ericwq** [comment]
@williamboman thanks for the explanation. I will try it with your suggestion.

**Comment by ericwq** [comment]
> Hm I think I closed the wrong issue before. So the reason it's not installing is because the binaries installed are built for GNU systems (i.e. ld & glibc). Alpine Linux is, by default, not compatible. I believe there's a package called `gcompat` which makes the system GNU-compatible (ish?). You can "force" installation by providing which target to install:
> 
> ```viml
> :MasonInstall --target=linux_x64_gnu lua-language-server
> ```
> 
> ```lua
> local pkg = registry.get_package("lua-language-server")
> 
> pkg:install {
>   target = "linux_x64_gnu"
> }
> ```

@williamboman  I tried your suggestion. mason reports "The current platform is unsupported."
```
#28 45.58 [mason] [INFO  00:11:04] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:166: Executing installer for Package(name=lua-language-server) version="latest"
#28 45.59 [mason] [INFO  00:11:04] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:166: Executing installer for Package(name=prettier) version="latest"
#28 45.61 [mason] [ERROR 00:11:04] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:200: Installation failed for Package(name=lua-language-server) error="The current platform is unsupported."
```

**Comment by ericwq** [comment]
> > Hm I think I closed the wrong issue before. So the reason it's not installing is because the binaries installed are built for GNU systems (i.e. ld & glibc). Alpine Linux is, by default, not compatible. I believe there's a package called `gcompat` which makes the system GNU-compatible (ish?). You can "force" installation by providing which target to install:
> > ```viml
> > :MasonInstall --target=linux_x64_gnu lua-language-server
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```lua
> > local pkg = registry.get_package("lua-language-server")
> > 
> > pkg:install {
> >   target = "linux_x64_gnu"
> > }
> > ```
> 
> @williamboman I tried your suggestion. mason reports "The current platform is unsupported."
> 
> ```
> #28 45.58 [mason] [INFO  00:11:04] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:166: Executing installer for Package(name=lua-language-server) version="latest"
> #28 45.59 [mason] [INFO  00:11:04] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:166: Executing installer for Package(name=prettier) version="latest"
> #28 45.61 [mason] [ERROR 00:11:04] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:200: Installation failed for Package(name=lua-language-server) error="The current platform is unsupported."
> ```

If I use the `:MasonInstrall` command, it works. The previous post is the result with the standard mason install method.

**Comment by williamboman** [comment]
> If I use the `:MasonInstrall` command, it works. The previous post is the result with the standard mason install method.

What do you mean by standard mason install method? You'll have to do it manually via `:MasonInstall --target=linux_x64_gnu` for now. Installing via the UI won't apply this flag, so installation will fail if you start it via the UI.

**Comment by ericwq** [comment]
Got it, thanks for your advice.

I will try to provide some tools to build musl binaries version of `lua-language-server` to [lusLS](https://github.com/LuaLS/lua-language-server). That will solve the problem once and for all.

Does mason support the musl version installation?

**Comment by williamboman** [comment]
Yeah if there's a musl binary available it's essentially just a one-liner to add support for it.

**Comment by ericwq** [comment]
Add a [PR](https://github.com/LuaLS/lua-language-server/pull/2049) for x86 `musl` binary of `lua-language-server`. Waiting for approval.
@foxyseta @williamboman

**Comment by ericwq** [comment]
> Yeah if there's a musl binary available it's essentially just a one-liner to add support for it.

The [previous pr](https://github.com/LuaLS/lua-language-server/pull/2049) has been accepted. Please note the example `musl` naming: `lua-language-server-3.6.18-linux-x64-musl.tar.gz`.  And we still need to wait for the next release cycle.
@williamboman

**Comment by ericwq** [comment]
> Yeah if there's a musl binary available it's essentially just a one-liner to add support for it.

@williamboman  could you add support for the musl version binary?

**Comment by sdondley** [comment]
> ```viml
> :MasonInstall --target=linux_x64_gnu lua-language-server
> ```
> 
>  ```lua
> local pkg = registry.get_package("lua-language-server")
> 
> pkg:install {
>   target = "linux_x64_gnu"
> }
> ```

Running the :MasonInstall command above worked.

Not sure what the code below is, however. Is that needed? Where do I put it?
